### ISSUE TITLE
Markup exercise review

### ISSUE THREAD

**Issue by Razpudding** [cmda-be/course-17-18#1]
Je ziet het niet als je em fout inlevert
Bij paragraph exercise kreeg ik geen bevestiging dat ik het goed had gedaan/ leek niet te werken. Kostte extra tijd. Was kennelijk een glitch want de exer daarna deed t wel

Ik krijg niet altijd de FB dat ik het goed heb gedaan hoewel ik technisch wel voldaan heb aan de opdracht. We moeten erbij zetten dat als je geen bevestiging krijgt je op hint moet klikken om te zien wat het verschil is.
-> Als je geen rode bevestiging krijgt is ie nog niet goed. Ga dan terug naar de beschrijving.
-> alles moet rood zijn als je terugklikt, dan weet je zeker dat het goed is.
-> Als je niet ziet wat je nog fout hebt klik dan op hint en je ziet het antwoord.

Completion time: 15 minutes.
Als het mij 15 minuten kost (en ik schrijf al markdown) gaat het studenten zeker 20 kosten om het goed te doen.

**Comment by wooorm** [comment]
Thanks! [Changed the tutorial to another one](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#markup), much nicer, but it’ll take a bit more time.
