### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#10]
R3V1c0RpamtodWlzCg==

**Comment by wooorm** [comment]
Looks good as well, but see my comment in your other issue!

**Comment by GuusDijkhuis** [comment]
Okey, I thought we had a lot more to do. So I am done.

**Comment by wooorm** [comment]
No it’s only about 0:45-1:00 hours of work (right? or was it way less?)

Anyway, did you see this part in the slack prereq?

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.

**Comment by GuusDijkhuis** [comment]
Wait a sec and I send you the link.
