### ISSUE TITLE
Octocat assignment Done

### ISSUE THREAD

**Issue by jesseDijkman1** [cmda-be/course-17-18#100]
### Links to the finished assignments:
- [x] [Introduction to Github](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14390)
  * Introduction to Github assignment was a bit annoying because I had to switch tabs all time, but it was also easy and well explained. 

- [x] [Github pages from the Command Line](https://github.com/githubschool/on-demand-github-pages/blob/master/_pages/jesseDijkman1.yaml)
  * Had some trouble merging the branch with the master and forgot to give username.yaml the right name :man_facepalming:

**Comment by wooorm** [comment]
Super!!!
