### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#102]
Link Introduction to GitHub:
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14397

Link GitHub Pages from the Command Line:
https://guusdijkhuis.github.io/GuusDijkhuis.github.io/

**Comment by rijkvanzanten** [comment]
Awesome! Your GH Pages site is also available on https://guusdijkhuis.github.io/ 😄
