### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by surferfelix** [cmda-be/course-17-18#104]
**bold**
_italics_
**_both_**
#h1
##h2
inline link: [Search for it.](www.google.com)
![]Image
> block-quote
* -
* -
* -
* - = List

·· = Hard space (for skipping lines)

**Comment by wooorm** [comment]
Hi @surferfelix! Is it correct that you didn’t finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for this week? Especially note this part of the slack prereq:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.

**Comment by wooorm** [comment]
P.S., nice that you’re working ahead! We’ll start work on the markup assignment in class tomorrow, but you can of course start with the next one then!

**Comment by wooorm** [comment]
Woohoo, finally!
