### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by DanielvandeVelde** [cmda-be/course-17-18#11]
Markdown is actually more useful than I thought it would be.
It's not just some weird BBcode alternative like I expected.

Anyway,
1. [This website] is kind of a scam since there isn't a daily upload schedule.
2. Making lists doesn't seem to _work_ all the time.
3. Apparently while making this it automatically makes the line-break, so no need to double-space at the end of a sentence!

I hope we're going to learn about making tables, footnotes and such later.
Here's a nice picture for your trouble.

![Of course I added alt-text. That's what I learned in the little course](https://imgs.xkcd.com/comics/real_programmers.png)

PS: I'm **_definitely_** going to appreciate the 3am deadlines. Those will come in handy for sure.

[This website]:http://www.dailykitten.com

**Comment by wooorm** [comment]
Thanks Daniel! And thank you for the write up!

> This website is kind of a scam since there isn't a daily upload schedule.

**Yes**!!! Definitely a scam!

> Making lists doesn't seem to work all the time.

Weird, what?

> Apparently while making this it automatically makes the line-break, so no need to double-space at the end of a sentence!

Yeah, that’s a thing that’s different with issues in GH and normal markdown!

> PS: I'm definitely going to appreciate the 3am deadlines. Those will come in handy for sure.

Good ;)

---

P.S., you only need to finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for now. We’ll start the assignments in class. Did you see this part in the slack one?

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.
