### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Karinliu** [cmda-be/course-17-18#114]
Opdracht complete. Was te doen, maar als ik alles zelf uit mijn hoofd moet schrijven, dan was het wel lastiger geweest.

**Comment by benvl** [comment]
Mee eens. Mischien helpt dit.

![760px-git_operations svg](https://user-images.githubusercontent.com/3481331/35970237-e955e8ea-0cc9-11e8-9764-fe06b7290537.png)

**Comment by benvl** [comment]
Oops... bronvermelding       [en.wikipedia.org/wiki/git](https://en.wikipedia.org/wiki/Git)

**Comment by rijkvanzanten** [comment]
Hopefully the Octocat assignment will clear things up some more 😄 👍
