### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Timilof** [cmda-be/course-17-18#128]
![schermafbeelding 2018-02-08 om 13 10 10](https://user-images.githubusercontent.com/35301857/35972288-7e79f694-0cd1-11e8-9073-68455a8dc595.png)

**Comment by rijkvanzanten** [comment]
Hey @Timilof!

What did you think of the assignment? Did you like? Was it useful in any way?

Lemme know 😄

**Comment by wooorm** [comment]
Awesome! Thanks for sending your GH username!
