### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by Karinliu** [cmda-be/course-17-18#13]
c2ggdHV0b3JpYWwuc2gK
karins-mbp:backend karinliu$

**Comment by wooorm** [comment]
Thanks!

P.S., you only need to finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for now. We’ll start the assignments in class. Did you see this part in the slack one?

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.
