### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#132]
# Markdown assignment
## Lists
* unordered lists
* are made
* with asterixes

1. Ordered lists
2. are made
3. with numbers

## Blockquotes
> Why call it *markdown* when you can be **markup**

[Check my github page](https://github.com/fjvdpol)

## Random image:
![Random image from unsplash.com][unsplash]

[unsplash]: https://unsplash.it/800/600 "Random image from unsplash.com"

**Comment by rijkvanzanten** [comment]
**_Well done 😄_**
