### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by daoneandonly** [cmda-be/course-17-18#137]
ZGFvbmVhbmRvbmx5Cg==

Ik hoop dat het klopt. Kopiëren werkt namelijk niet.

**Comment by rijkvanzanten** [comment]
Thanks!

Copying seems to work for most others though.. Could you share some information on your specific setup so we can try to figure out what's causing this? Most notably your operating system + version and what terminal emulator (program) you use. Thanks in advance! 😄 

> Kopiëren werkt namelijk niet.

@wooorm ☝️

**Comment by wooorm** [comment]
I think you’re using cmd on Windows right? It’s possible, but it involves some weird things, and you can find out more on Google. But, maybe just try <http://cmder.net>?

**Comment by daoneandonly** [comment]
I have switched to cdmer. This is much better, thanks!
