### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#14]
# Markdown 

**_Sed posuere consectetur est at lobortis_**. Curabitur blandit tempus porttitor. 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.

#### Lists
* Milk
  * [Campina](https://www.campina.nl)
* Sausage
* Water

### Leuke foto van een hond
![Pug](https://user-images.githubusercontent.com/10829926/35857373-44f6ac8a-0b39-11e8-9fc6-6b79876ac77a.jpg)

**Comment by wooorm** [comment]
Thanks Tim!

P.S. We’ll start with the assignments in class, no need to work ahead!
