### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by MonikaaS** [cmda-be/course-17-18#145]
Gelukt!

<img width="1440" alt="screen shot 2018-02-08 at 13 58 05" src="https://user-images.githubusercontent.com/36171561/35974167-3d9dd09e-0cd8-11e8-9a60-502549a653b3.png">

Still find it hard to understand how everything works.

**Comment by rijkvanzanten** [comment]
Hopefully the Octocat assignment will clear things up a bit 😄
