### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#146]
> ## Gelukt goede tutorial 

> https://marijnone.github.io/marijnone/

**Comment by rijkvanzanten** [comment]
Hey @Marijnone!

Could you please share the link of the closed PR of the Introduction to GitHub assignment?

> Include two links in your issue: one to the closed PR from the Introduction to GitHub exercise, the other to the GitHub Pages website from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.

**Comment by Marijnone** [comment]
Here you go https://github.com/githubschool/on-demand-github-pages/pull/2194

**Comment by rijkvanzanten** [comment]
Awesome! Thanks 😄
