### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by WolveBorn** [cmda-be/course-17-18#147]
# level 1 heading
  ## level 2 heading
  ### level 3 heading
  #### level 4 heading
  ##### level 5 heading
  ###### level 4 heading

  A normal paragraph

  * An
  * Unordered
  * List

  1. An
  2. Ordered
  3. List

  ####Blockquote&code

  A paragraph

  > A block quote

  Another paragraph

  ```js
  and.aBit({of: 'JavaScript'});
  ```

  ####Inline

  A paragraph with *italics*, **bold face**, **_bold italic_** and `inlineCode()`.

  A [link](http://example.com).

  And an ![image](http://example.com/image.png).

  Do you want to [see something fun][a fun place]?

  Well, do I have [the website for you][another fun place]!

  [a fun place]: www.zombo.com
  [another fun place]: www.stumbleupon.com

  ![The first father][First Father]
  ![The second first father][Second Father]

  [First Father]: http://octodex.github.com/images/founding-father.jpg
  [Second Father]: http://octodex.github.com/images/foundingfather_v2.png

  Twee spaties zorgen dat je een nieuwe regel begint zonder wit ruimte.

**Comment by rijkvanzanten** [comment]
Awesome stuff!

Quick tip: links in Markdown without `https://` are _relative_. Try clicking on one of the links in your example! The link links to `https://github.com/cmda-be/course-17-18/issues/www.zombo.com` instead of `www.zombo.com`.

🎉
