### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#148]
# Feedback Try Git assignment
## Goeie dingen
* Uitgebreide hoeveelheid commando's
* Werkt op zich smooth als je de juiste commando's probeert uit te voeren
## Minder fijne dingen
* Soms als je een commando uitprobeerd in een venster waar je bezig bent een ander commando te leren krijg je rare feedback
* De uitleg over diff en wat je daar vervolgens mee kan doen vind ik persoonlijk wat vaag en snel gaan.

**Comment by rijkvanzanten** [comment]
Awesome! If you want to learn more about `git diff`, checkout this nice article on the subject 🙂 
https://www.git-tower.com/learn/git/ebook/en/command-line/advanced-topics/diffs
