### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by LocNguyen1994** [cmda-be/course-17-18#149]
Moet hier de files in de directory verwijderen, maar het enige wat er in directory zit is tutorial.sh
![image](https://user-images.githubusercontent.com/36054537/35974855-ebe5709c-0cda-11e8-8716-08d1fd75c4f7.png)

**Comment by LocNguyen1994** [comment]
help

**Comment by wooorm** [comment]
@LocNguyen1994 did you figure this out yet? If not, maybe start over?

**Comment by rijkvanzanten** [comment]
[Too late; didn't grade.](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#synopsis-3)
