### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by WolveBorn** [cmda-be/course-17-18#150]
#### Git Commandline
  - git init                  = Create repository
  - git status                = Current state
  - git add (new)             = Track file
  - git add (existing)        = Stage file
  - git commit -m "string"    = commit with a message with what you changed
  - git log                   = Show progress (logboek)
  - git remote add origin     = Legt de link met de offline en online branch (zelfde branch alleen off en on)
  - git push -u origin master = Pushed offline branch naar online branch (later git push)
  - git push                  = Pushed naar GitHub na 1 keer ^ gebruikt te hebben.
  - git pull origin master    = Pulled online branch naar je offline branches.
  - git pull                  = Pull van GitHub na 1 keer ^ gebruikt te hebben.
  - git diff HEAD             = Shows what is different since our last commit. use HEAD for most recent commit.
  - git diff --staged         = See the changes you just staged
  - git reset                 = Unstage files
  - git checkout -- _         = Changes the file back since to the state of the last commit.
  
  -    '*.txt'                = Verwijder alle .txt bestanden ( * = alles)
  
  
#### Git Branch 

  - git branch _              = Create a branch 
  
  - git checkout -b _         = Create a branch
  - git checkout _            = Switch to a branch
  - git branch                = Show branches
  - git merge _               = Apply changes
  - git branch -d _           = Remove a branch

  - -m    --message           = Comment
  - -d    --delete            = Remove

**Comment by rijkvanzanten** [comment]
```
git add assignment.md
git commit -m 'Add git cheatsheet'
```

Nice cheatsheet! 😄
