### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by daoneandonly** [cmda-be/course-17-18#151]
I've completed the 'Try Git' tutorial. However ,I am curious how you switch between commits. This was not explained in the tutorial.

**Comment by rijkvanzanten** [comment]
Hey @daoneandonly!

Going back and forth between commits is very prone to weird situations, as it's quite easy to mess up your project if you're not very careful.

I recommend you take a look at working with branches instead. That's a more "safe" way of working with different states of your codebase.

A good tutorial for learning branches: https://learngitbranching.js.org/

That being said, reverting to older commits is a very powerful tool. If you want to play around with it, this StackOverflow answer describes it pretty well IMO: https://stackoverflow.com/a/4114122/4859211

**Comment by daoneandonly** [comment]
Thank you for the response! @rijkvanzanten
