### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#152]
# Octocat Assignment
## Links to the assignments
[Link to the PR](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14461)
[Link to the github pages website](https://fjvdpol.github.io/)

## Feedback
Ik vond niet alle uitleg even duidelijk en bij het switchen van een persoonlijke respository naar de gezamelijke github repository tijdens de github pages from the cli was dat erg onduidelijk aangegeven.

**Comment by rijkvanzanten** [comment]
Awesome, thanks!
