### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by DanielvandeVelde** [cmda-be/course-17-18#153]
Pull requests:
https://github.com/githubschool/on-demand-github-pages/pull/2200
https://github.com/DanielvandeVelde/DANIELVANDEVELDE.GITHUB.IO
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14454

My yaml addition:
https://github.com/githubschool/on-demand-github-pages/blob/master/_pages/DanielvandeVelde.yaml

My website:
https://danielvandevelde.github.io/

**Comment by rijkvanzanten** [comment]
Well done 😄
