### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by civvx** [cmda-be/course-17-18#154]
Done

**Comment by rijkvanzanten** [comment]
Hey @civvx!

What did you learn from this assignment?

> If you completed the markdown tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. In your issue, include some of the markdown you learned (like headings, lists, and more).

👋

**Comment by civvx** [comment]
It was easy and not very hard to remember the commands. I did get stuck for a while at question 6.

**Comment by wooorm** [comment]
@civvx Cool cool! Still no answer though:

> In your issue, include some of the markdown you learned
