### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#157]
https://github.com/timruiterkamp/dotfiles

Good exercise to learn the possibilities of tweaking the command line, the articles where great value for the start of the project! Overall it was a bit odd in the beginning because due to the fact i didn't have any knowledge about it, but after seeing the results of making use of aliases the terminal is getting more easy to use. Maybe it would come in handy to add the code for refreshing the .bash_profile ```. .bash_profile```.

**Comment by wooorm** [comment]
Wow this is awesome! And you’re the first to hand in the dot files repo!

As you’re the first, and I have no idea what other people will hand in, some random thoughts:

1. Did you actually spend the allotted time? (almost 4 hours)? I feel this is a bare minimum of results, but maybe it’s just a very hard assignment
2. Could you share the reload thing in slack? I personally have `alias reload="exec $SHELL -l"` in my bash profile, and it does exactly that, maybe you like that as well!
3. where did you find some of the aliases? Maybe it’s handy to link the the place you found them for future reference 😉
4. Maybe add `.DS_Store` to your global `.gitignore`?

/CC @rijkvanzanten @Razpudding What do you think?

**Comment by timruiterkamp** [comment]
@wooorm Thanks!
1. I did spend a lot of time get it al up and running, i did not really know in the beginning which file i should've been editing as i had a .bash_profile, .profile, .bashrc and what for codes used to edit the terminal commands. Beside that it took quite some time to figure out how to install rupa's Z and cowsay as i had to look in multiple places to get it up and running. The rest of the time i spend on analysing articles and trying out codes i could use during development.  
2. Cool! I'll add the references to my bash file and i will share the solution i found in slack!  
3. I will add the references to the files 👍   
4. Thanks, that's a good one!

**Comment by rijkvanzanten** [comment]
The `myip` alias is pretty handy! I might add that one to my own `.zshrc` soon 😄
