### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by daoneandonly** [cmda-be/course-17-18#160]
Completed both tutorials. These were really useful!

Both PRs are now closed.
[Github introduction](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14464)

[On demand Github Pages](https://github.com/githubschool/on-demand-github-pages/pull/2207)

_(Chinese spambot included)_

**Comment by wooorm** [comment]
Very nice! I like the Chinese spambot, and that you thumbs-up’ed the comment 😂
