### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by Rowin206** [cmda-be/course-17-18#161]
# I've done it

_Who am I_? 
* Rowin
* Student 
* 21 years old 

<img width="1436" alt="screen shot 2018-02-08 at 17 08 41" src="https://user-images.githubusercontent.com/33234293/35983672-c85a7042-0cf2-11e8-8225-2cd469b1e073.png">

**Comment by wooorm** [comment]
Very nice!
