### ISSUE TITLE
Learn Markdown assignment 

### ISSUE THREAD

**Issue by superstephan1** [cmda-be/course-17-18#166]
# Markdown opdracht af

> echte nerds maken hun huiswerk vlak na de les  

![kat met bril](https://ae01.alicdn.com/kf/HTB15_vyOXXXXXblXVXXq6xXFXXXH/Hot-Selling-Kat-Foto-Antislip-Laptop-PC-Muizen-Pad-Mat-Mousepad-Voor-Optical-Mouse-Stralingsbescherming-Rubber.jpg_640x640.jpg)

Nu is het tijd voor boodschappen...  
dus eerst maar een lijstje maken  

* eieren
* kip
* pizza

**Comment by wooorm** [comment]
Thanks for the cat! 🎉
