### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by matsfeber** [cmda-be/course-17-18#168]
# Markdown assignment

A tutorial to learn the **basics of markdown**.

I learned : 
* How to make headers
* How to make lists
* How to add a link
* How to add an image

![Markdown logo](https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Markdown-mark.svg/416px-Markdown-mark.svg.png)

**Comment by rijkvanzanten** [comment]
**_Awesome stuff 💯_**
