### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Maikxx** [cmda-be/course-17-18#169]
# Finished both assignments

[**Introduction to GitHub**](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14470)

[**GitHub Pages from the Command Line**](https://github.com/Maikxx/github-pages-assignment)

Using these both, was so **frustrating**. For some reason the course is **really** choppy (Mac, safari). It continuously kept crashing my browser.

**Comment by rijkvanzanten** [comment]
Hey @Maikxx!

Could you please send over the link to your GitHub Pages website?? Thanks!

> If you completed the exercises, mark this assignment as complete by opening an issue on our GitHub issue tracker. Include two links in your issue: one to the closed PR from the Introduction to GitHub exercise, the other to the GitHub Pages website from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.

As for the course being choppy, that's probably due to the fact that they use gigantic `.gif`s instead of videos in the screencasts 😨

**Comment by Maikxx** [comment]
[This should work](https://maikxx.github.io/github-pages-assignment/)

**Comment by rijkvanzanten** [comment]
Thanks! Nice [brutalist](http://brutalistwebsites.com/) design 😜

Have you tried one of the provided GitHub pages themes?

**Comment by Maikxx** [comment]
Ah that is great! Hahaha. Did not know there was such a thing still in 2018. Looks like some great inspiration there. Yeah, I did, but found none to be of any particular value for this assignment haha.
