### ISSUE TITLE
Try Git assigment

### ISSUE THREAD

**Issue by SlodderWolf** [cmda-be/course-17-18#175]
<img width="825" alt="schermafbeelding 2018-02-08 om 21 02 00" src="https://user-images.githubusercontent.com/23551707/35995364-5e1a4b5a-0d13-11e8-8176-ebbf16e4b4de.png">

Duidelijke interface, verder wist ik niet bij alle commando's wat ik nou precies aan het doen was. De eerste keer dat ik Git/ Github gebruik dus het is nog een beetje uitvinden hoe het werkt en hoe het in elkaar steekt.

**Comment by rijkvanzanten** [comment]
Hi @SlodderWolf!

Hopefully the Octocat assignment will clear things up for you 😄
