### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Mimaaa** [cmda-be/course-17-18#177]
A good one to fresh up on some git knowledge.

<img width="821" alt="screen shot 2018-02-08 at 22 16 22" src="https://user-images.githubusercontent.com/12242967/35998758-7b7196f2-0d15-11e8-87a1-5745afad263f.png">

**Comment by rijkvanzanten** [comment]
`git commit -am 'lekker bezig Mimaaa'`
