### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by deannabosschert** [cmda-be/course-17-18#178]
Assignment finished.

I've had help testing out Git last monday so it all came across as fairly familiar.
As there's also an option to just repeatedly press the answer button it's a bit of a 'giveaway' at some points though.

**Comment by rijkvanzanten** [comment]
What did you think of the assignment @deannabosschert? Was it any useful?

> That’s it! Well done you! If you completed the tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. Let us know in the issue if you liked this assignment, and give us any feedback.

**Comment by deannabosschert** [comment]
Edited!

**Comment by wooorm** [comment]
Thanks @deannabosschert, looks good now!
