### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by deannabosschert** [cmda-be/course-17-18#179]
######Assignment finished.

Markdown learned:

#Headings
*italic*
**bold**
_**or both!**_

1. Ordered
  2. Lists
* Unordered
  * Lists

Images:
![Images](http://i0.kym-cdn.com/entries/icons/original/000/021/807/4d7.png)
[Links](http://www.hva.nl/praktisch/algemeen/hva-breed/ac-hr/uitschrijven/uitschrijven.html?origin=gbS4rg%2FDTZuxQ6lGVF%2BN1A)

> Blockquotes

Individual lines 
Mostly used 
For poetry

**Comment by rijkvanzanten** [comment]
Hey @deannabosschert! Could you please show us some of the different markdown skills you've learned?

> If you completed the markdown tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. In your issue, include some of the markdown you learned (like headings, lists, and more).

**Comment by wooorm** [comment]
@deannabosschert Awesome!! Hackerman!
