### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by SoulaimaneEC** [cmda-be/course-17-18#180]
# Done!
Nu alleen nog de opdrachten:
* Try Git
* Octocat
* Profile

![Cat](https://images.unsplash.com/photo-1509195605820-8eb07b921387?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cef41b325aa1f84d694aa4d831fb4852&auto=format&fit=crop&w=1000&q=80)

**Comment by rijkvanzanten** [comment]
Awesome! 😸 Good luck with the other assignments!

**Comment by wooorm** [comment]
Woohoo thanks for the cat! 💚
