### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by tomoversluizen** [cmda-be/course-17-18#182]
#### [Introduction to GitHub](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14482)
>It was very refreshing to know how to initiate pull requests again.
  
#### [GitHub Command Lines](https://tomoversluizen.github.io)
> This was a nice representation of how to use git and GitHub to the fullest with the combination of command lines and using the pull request feature with Travis CI to validate the code.

**Comment by wooorm** [comment]
@tomoversluizen Superrr!
