### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by ninavanbergen** [cmda-be/course-17-18#186]
Ik heb geleerd hoe ik headings, lijstjes, bold / italic, linkjes en foto's moet aangeven in Markup. Ik vond het niet heel moeilijk gelukkig, ik begreep het ook meteen. Ik had nog twee manieren van hoe je een reference link kan doen gevonden, maar de manier die Markup voorstelt is wel makkelijker dus ik houd die aan.

**Comment by rijkvanzanten** [comment]
**_Cooolio 😄_**
