### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by LindadeHaan** [cmda-be/course-17-18#187]
Ik heb bij deze opdracht geleerd hoe ik tekst italic en bold kan maken. Hoe ik lijstjes kan maken unordered en ordered. Ik heb ook geleerd hoe ik headings toe kan voegen en hoe ik linkjes en images kan toevoegen. 
Het was makkelijker dan ik had gedacht en ik begreep het goed. Ik snap nu wel beter hoe het moet, doordat ik er echt een oefening bij heb gedaan.

**Comment by rijkvanzanten** [comment]
**_Cooolio 😄_**
