### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by matsfeber** [cmda-be/course-17-18#188]
# Octocat

- ## [Introduction to GitHub](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14504)

- ## [GitHub from the command line](https://github.com/githubschool/on-demand-github-pages/pull/2221)

- ## [Hello World!](https://matsfeber.github.io/matsfeber.github.io/)

**Comment by rijkvanzanten** [comment]
Well done 👍
