### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by Mimaaa** [cmda-be/course-17-18#19]
:tada:

**Comment by wooorm** [comment]
👋

Looks good but:

> In your issue, include some of the markdown you learned (like headings, lists, and more).

**Comment by Mimaaa** [comment]
:+1:

**Comment by wooorm** [comment]
Ohhh, I don’t know the deuce or billions. So they’re good?

And thanks for the dolphin!

**Comment by dandevri** [comment]
Just gonna leave this here 🙅🏼‍♂️

https://www.youtube.com/watch?v=eTVe52UT9YU

**Comment by wooorm** [comment]
🤮

**Comment by Mimaaa** [comment]
They are. If you watched the Wire, then you'll like the Deuce as well. It's from the same creator.
