### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by maybuzz** [cmda-be/course-17-18#191]
Hi,

Ik vond de assignment wat eenvoudig, alles is bepaald en hoeft eigenlijk nieteens uitgetypt te worden. Het idee en de taal is wat duidelijker, maar ik heb eigenlijk nog weinig tot geen idee wat ik nou allemaal gedaan heb.

Groetjes,
May

**Comment by rijkvanzanten** [comment]
Hopefully the Octocat assignment will clear things up some more 😄
