### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by naomiaz** [cmda-be/course-17-18#195]
# I did it!

Ik heb vandaag **_Markup_** geleerd. Dat betekent dat ik nu:

* Tekst kan opmaken, _italics_ en **bold**. 
* Linkjes kan maken, bijvoorbeeld naar de website van van de [NOS](http://www.nos.nl), want het is erg belangrijk te weten wat er speelt op de wereld.
* Plaatjes kan toevoegen:

![duim](http://www.mis-specialists.co.uk/images/thumbsup.png)

Groetjes,
Naomi

**Comment by wooorm** [comment]
Superrr!
