### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Kalemis** [cmda-be/course-17-18#196]
## Tutorial 1
[Closed Pull Request](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14513)

## Tutorial 2
[Github Pages website](https://kalemis.github.io/Kalemis.GITHUB.IO/)

Bij de tweede tutorial werd twee keer de pull request niet goedgekeurd maar ik heb het weten op te lossen.

**Comment by rijkvanzanten** [comment]
Well done! 🎉
