### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Maikxx** [cmda-be/course-17-18#198]
# Finished this assignment
Finishing this, for me, means having done all the necessities from the assignment, while not changing _too_ much of my current workflow. 
All the details are in the README and file additions.

The repository can be found [here](https://github.com/Maikxx/dotfiles).

It was fun doing this assignment, looking at other people their setup in development.
Although I did not change much, I think I understand more, **why** people modify their dotfiles now. Developing is a full time job (or hobby, or both (like me)), where you need to have the best of your tools. I like to have my themes and terminal relatively clean, hence why I don't want too much noise.

**Comment by rijkvanzanten** [comment]
Hey @Maikxx!

Is there a specific reason for excluding the other dotfiles mentioned in the readme? 

Out of my own interest, could you maybe share a screenshot of your iTerm setup? I'm always interested in trying out new combinations of themes and prompts 😄

**Comment by Maikxx** [comment]
Well yes, since I mapped the terminal to open code if it asks me to enter text (instead of vim) .vimrc, is for me of no use. As for curl, I don't find myself having the urge to change things. I like things the way as they are haha. I don't like to change my current workflow too much ;)

The screenshot is located here: [screenshot](https://imgur.com/g2qgkoE).
Had to blur some private data out, but the part after the time is the name of my computer in turquoise.

**Comment by wooorm** [comment]
Awesome! Cool dot files @Maikxx!

For this line: https://github.com/Maikxx/dotfiles/blob/1ec1ac5c20297486ca4098f37859e98543aa4df0/.zshrc#L115

You can also add more references: `alias ...="cd ../.."`, maybe that’s also helpful!

**Comment by Maikxx** [comment]
Thanks @wooorm! Great addition! Adding that now to my machine haha.

**Comment by wooorm** [comment]
Don’t forget to push to GH 😉
