### ISSUE TITLE
Run exercise review

### ISSUE THREAD

**Issue by Razpudding** [cmda-be/course-17-18#2]
MSs makkelijker om dat script in een blob te zetten, beetje irritant selecteren voor studenten (ja kan ook met devtools etc).
Hmm een paginalang shellscript runnen dat ik niet gelezen heb 🤔

Niet alle stappen hebben een logische link. Zo heb je in stap C niks aan stap B. Ik heb eerder gemerkt dat dat soort dingen verwarrend is voor studenten. KAn opgelost worden door iets toe te voegen zoals: je hebt dit profiel nu nog niet nodig maar later wel. We gaan eerst lokaal op jouw computer een programma draaien. oid.

Weten ze bij stap D al hoe de terminal werkt? Of waar die te vinden is? Kan wel even duren voor ze bij Extra resources kijken. Aan de andere kant, mss is het wel goed dat ze dat dan een keer doen.

AWESOME. Een interactive terminal tutorial in de terminal 👏

Ik krijg niet altijd feedback als ik het goed gedaan heb. Niet heel erg want je ziet de vinkjes.

Als ik man type gebeurt er niks? Ook nietbij man ls. Werkt alleen buiten jouw programma.

Als het "per ongeluk" lukt om de goede code te runnen gaat ie meteen naar de main screen. Dat is wel weinig feedback.

Ik denk dat de redirect opdracht wat lastig is, je moet daar veel in een keer doen en je kan niet de gebruikelijke commands (zoals ls) gebruiken om te zien wat er al bestaat. HEt is bovendien erg lastig voor ze dat "alpha" tussen ahalingstekens moet maar de naam van de file bijv weer niet. Ik zou deze in stappen opknippen.

Move a file -> Het zal mss niet helder zijn dat je move kan gebruiken om te renamen zoals hier. Niet logisch voor beginners.

25 minuten na beginnen had ik de code (incl. dit schrijven).

UmF6cHVkZGluZwo

**Comment by wooorm** [comment]
#### Man

That’s mentioned in the tutorial already, but yeah we should mention that in class.

#### Perongeluk

> Als het "per ongeluk" lukt om de goede code te runnen gaat ie meteen naar de main screen. Dat is wel weinig feedback.

¿Qué? Wat bedoel je?

#### Redirect

> Ik denk dat de redirect opdracht wat lastig is, je moet daar veel in een keer doen en je kan niet de gebruikelijke commands (zoals ls) gebruiken om te zien wat er al bestaat. HEt is bovendien erg lastig voor ze dat "alpha" tussen ahalingstekens moet maar de naam van de file bijv weer niet. Ik zou deze in stappen opknippen.

Quotes aren't needed, `echo Alpha > foo.txt` is fine, and so is `echo "Alpha" > "foo.txt"`! Why would you need to `ls`? The only addition for this step is the `> foo.txt` part, the echo is already done before. And it’s mentioned in the slides already, and demo’d there as well. Dunno, I feel it’s not harder than other steps?

**Comment by Razpudding** [comment]
> ¿Qué? Wat bedoel je?
What I'm trying to say here is that because you don't get FB on completion of a sub task, a couple things go wrong.
1. You don't know you've actually completed the task
2. You don't get positive FB (helps with motivation)
3. You don't get a chance to review or even realize the right answer. Sometimes I rapidly changed my attempt and then 💥 main screen. 

> Why would you need to ls
Because you're a beginner and `ls` is like your sanity check. I tried to use it in this ass. because I didn't know if the files you were talking about had already been created or not. It feels like Im working blind or that my actions don't have actual results in the file system and you're just checking wether the commands are correct (which is prob the case).
It's not crucial but it would be nice if you outputted ls by default in the description or smt like that :)

Redirect felt harder because I thought I had to take multiple steps. This was because of "working blind".
