### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Rowin206** [cmda-be/course-17-18#200]
# Octocat

## Tutorial 1 

[closed PR](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14510)

## Tutorial 2 
[Pages Website](https://rowin206.github.io/)
[closed PR](https://github.com/githubschool/on-demand-github-pages/pull/2234) 

Problemen gehad met tutorial 2, verschillende foutmeldingen, waaronder het probleem met silver surfer(?). Uiteindelijk zelf kunnen uitvinden deze te verwijderen en meerdere syntax/merge/pull request problemen.

**Comment by rijkvanzanten** [comment]
Cool! Silver Surfer?
