### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by SoulaimaneEC** [cmda-be/course-17-18#201]
Vond het goed dat ze niet alleen uitleg gaven maar dat je ook zelf steeds de regel code moest typen, soms nog wel een beetje onduidelijk hoe het precies werkt. Wel hielp het soms dat ze tips of wat meer uitleg gaven rechtsonder

**Comment by rijkvanzanten** [comment]
Aight! Hopefully the Octocat assignment clears things up a bit.
