### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by Asprengers** [cmda-be/course-17-18#202]
Markdown

_italic_
**bold**

Headings
#Header one
##Header two
###Header three
####Header four
#####Header five
######Header six

Links
[Visit GitHub!](www.link)

Reference link
Do you want to [see something fun][a fun place]?

Well, do I have [the website for you][another fun place]!

[a fun place]: www.link
[another fun place]:www.link

Images:

Inline image link
![alt](link)

Blockquote 
> 

Unordered list
*

Ordered list
1. 

Soft break
Double space

**Comment by rijkvanzanten** [comment]
**_Awesome!_**

Note that a space is required between the `#` and the actual title. You can use the _Preview_ tab on GitHub to check if your markdown results in the output you want 🙂
