### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Asprengers** [cmda-be/course-17-18#203]
Er stond veel informatie wat er gebeuren moest en welke code er gebruikt moest worden, maar ik vond het wel onduidelijk te zien wat er nou eigenlijk gebeurde. Na een aantal keer heen en weer klikken zag ik pas wat er gedaan werd.

**Comment by rijkvanzanten** [comment]
Aight! Hopefully the Octocat assignment clears up what is going on while executing these commands
