### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by jessiemasonx** [cmda-be/course-17-18#204]
Ik vond het echt leuk om te doen. Ik had deze manier van schrijven voor deze opdracht nog nooit gebruikt. Ik heb geleerd hoe je woorden _italic_ of  **bold** kan maken. Dit kan ook  _**samen**_. Verder heb ik de verschillende niveaus van headings geleerd. Zoals:
# Heading 1
### Heading 3

Het leukste vond ik het linken. Dit zag er dan zo uit: [hai deze link werkt niet maar het gaat om het idee](hoi).

Verder heb ik nog geleerd hoe je ordered en unordered lists maakt en hoe je afbeeldingen invoegt. 

Dit alles was nog maar een deel van wat ik door deze opdracht allemaal weet.

**Comment by rijkvanzanten** [comment]
**_Awesome!_**

You can use backticks (``)  to display pieces of code without having markdown parse them 🙂 

`[haii](hoi.com)`

**Comment by jessiemasonx** [comment]
Oh good to know! '**Thanks!**'
