### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by LindadeHaan** [cmda-be/course-17-18#205]
De oefening was erg nuttig, maar ik vind dit nog wel een lastig onderdeel. Ik moet er nog wel wat meer mee oefenen, maar ik vind het heel erg interessant. 
Ik vond het ook leuk dat er een paar nieuwe dingen in voor kwamen die niet in het hoorcollege waren genoemd naar mijn weten.

**Comment by rijkvanzanten** [comment]
Heya! Hopefully the Octocat assignment gives you some more practice 👍
