### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Mennauu** [cmda-be/course-17-18#207]
### Introduction to GitHub

https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14525

### GitHub Pages from the Command Line exercise

https://mennauu.github.io/

### What did I think of the assignment?

They are fine 'tutorials' for beginners. You follow the given steps and that's it!

**Comment by rijkvanzanten** [comment]
Cooolio 👍
