### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by Mennauu** [cmda-be/course-17-18#209]
# This is a BIG header
### This header isn't that big, but it's still bigger than regular text

This is normal text
**This is bold text**
_This is italic text_

> This quote is AMAZING

[This text links to my **Github** _website_!](https://mennauu.github.io/)

- This is a list
- Hi

1. This is also a list
2. Hi

![Cat](https://wallscover.com/images/cool-6.jpg)

**Comment by rijkvanzanten** [comment]
**_Awesomeeeeeeeee 😸_**
