### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by jessiemasonx** [cmda-be/course-17-18#212]
I thought this was a great assignment. It was quick and simple, and a good way to see what all the code actually does. The explanations were very clear. It couldn't really go wrong.

<img width="849" alt="schermafbeelding 2018-02-10 om 12 18 33" src="https://user-images.githubusercontent.com/31730836/36061603-8ee9dbca-0e5c-11e8-9cd3-98853486a0e4.png">

**Comment by wooorm** [comment]
Nice!
