### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by superstephan1** [cmda-be/course-17-18#213]
1e deel
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14523

2e deel
https://superstephan1.github.io/

leuke opdrachten ben alleen langer dan nodig bezig geweest met het 2e deel omdat ik problemen had om de pull request groen te krijgen. uiteindelijk gelukt en bleek typfout te zijn

**Comment by wooorm** [comment]
Out of curiosity, how much time did the second part take?

Nice btw! Why is your website so barebones though? 😉

**Comment by superstephan1** [comment]
hmmm about an hour i guess. I just have to learn how to read 👍 
yeah sorry, will add some cat's on my site next time.
