### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by SoulaimaneEC** [cmda-be/course-17-18#216]
[Introduction to Github](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14544)
[Github pages](https://soulaimaneec.github.io/)

**Mening**
De eerste tutorial sprak wel voor zich, bij de tweede heb ik wel meer geleerd en ik vond het ook wel goed dat ze weinig uitleg gaven bij de laatste stappen en je alleen vertelde wat je moest doen en niet hoe.

**Comment by wooorm** [comment]
Well done, I’m glad to hear that @SoulaimaneEC!
