### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by BasPieren** [cmda-be/course-17-18#217]
**Introduction to GitHub:** https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14550

**GitHub Pages from the Command Line:** https://github.com/githubschool/on-demand-github-pages/pull/2249

https://baspieren.github.io/

Tutorials waren duidelijk te volgen dankzij de combinatie van tekst en beeld. Het duurde alleen wel een tijd voordat ik door alle checks kwam van de "GitHub pages form the Command Line" oefening maar ik heb dit kunnen oplossen door de andere PR's te bekijken.

**Comment by wooorm** [comment]
Super! I like your website design! 🤔😉
