### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by Roene** [cmda-be/course-17-18#218]
# Markdown
## Opdracht

>Blockquote

*Italic text*
**Bold text**
*Combine **this** text*

### List
* Item 1
* Item 2

1. Item 1
2. Item 2

#### Link & image
[Ajax](http://www.ajax.nl/streams/actueel.htm)
![ajax](https://user-images.githubusercontent.com/31709511/36062987-e97b2a7a-0e76-11e8-8c49-bb8249c14d6d.jpg)

**Comment by wooorm** [comment]
Awesome @Roene!
