### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Roene** [cmda-be/course-17-18#219]
[Opdracht 1](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14559)
[Opdracht 2](https://github.com/githubschool/on-demand-github-pages/pull/2253)
[Github pages](https://roene.github.io/)

**Mening** 
De 1e opdracht  is eenvoudig en niet heel leerzaam. 
De 2e opdracht is leerzamer + je moet meer zelf uitzoeken 😎

**Comment by wooorm** [comment]
Great work! Out of curiosity, do you think we should skip the first part next year? Or maybe the try git assignment (related to GH220)?
