### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Roene** [cmda-be/course-17-18#220]
![opdracht_git](https://user-images.githubusercontent.com/31709511/36064197-846c65ca-0e87-11e8-8ab8-0674fc910372.PNG)

**Mening**
Denk dat deze opdracht niet heel nuttig is. Het is vooral over typen, van het zelf uitzoeken / uitproberen leer je naar mijn mening meer.

**Comment by wooorm** [comment]
Hmm, yeah I get that! Anyway, glad you got it!
