### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by theonejonahgold** [cmda-be/course-17-18#223]
[Here](https://github.com/theonejonahgold/dotfiles) is my dotfiles repo! 😊

**Comment by wooorm** [comment]
Awesome @theonejonahgold! Hey, do you have a screenshot of how it looks in your terminal?

**Comment by theonejonahgold** [comment]
@wooorm I pushed an update with a screenshot inside the readme 😊

**Comment by theonejonahgold** [comment]
I forgot to push the commit.. 😓  It's on the repo page now

**Comment by wooorm** [comment]
lol, yes I was wondering about that! 😉
It looks marvellous! Which terminal emulator is that?

**Comment by theonejonahgold** [comment]
It's called [iTerm2](https://www.iterm2.com/). I've added some links below the screenshot to get the exact same look :)

**Comment by wooorm** [comment]
Super awesome dot files @theonejonahgold!
