### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by Jmbjojo** [cmda-be/course-17-18#231]
am1iam9qbwo=

**Comment by wooorm** [comment]
Hi @Jmbjojo! It looks like you didn’t finish the [prereqs of this week](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#slack), mostly this part:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.

**Comment by wooorm** [comment]
Awesome! 🎉
