### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#234]
https://github.com/Marijnone/dotfiles01

>I think it has to do with windows on ubuntu but both my cmder and hyper do not work with the profile or >.bashrc file. if anyone knows how to fix this i would love to hear how.

Untill then it works by typing in . .bashrc inside my shell

**Comment by wooorm** [comment]
You should ask this in Slack! I’m sure other Windows users have had this problem as well, but I’ve seen people where it works!

**Comment by wooorm** [comment]
Also, why is `btc` commented out? 🤔
