### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Roene** [cmda-be/course-17-18#235]
[.Profile opdracht](https://github.com/Roene/dotfiles)

![Bash](https://user-images.githubusercontent.com/31709511/36076270-293b29c4-0f5a-11e8-98d2-6a5ed8cbdfbe.PNG)
![pong](https://user-images.githubusercontent.com/31709511/36076367-8418d2fa-0f5b-11e8-94a9-5f8bf06c68e2.PNG)

**Mening**
Leuke opdracht, veel zelf uitzoeken vooral over aliases 😎.
Promt aanpassen vond ik persoonlijk niet echt nuttig (ik wilde dit eigenlijk niet doen 👎 ). Je wordt wel extra uitgedaagd om naar nuttige (en wat minder nuttige) dingen te zoeken 👍

**Comment by wooorm** [comment]
Awesome! I think that adding git info to your prompt like so will be more useful in the future:

<img width="762" alt="screen shot 2018-02-11 at 18 54 29" src="https://user-images.githubusercontent.com/944406/36076488-0819c2fc-0f5d-11e8-9adc-cad46106f497.png">

P.S. It looks like some aliases are pretty standard, maybe it makes sense to, in your profile, link to the sources you got them from?
