### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Jmbjojo** [cmda-be/course-17-18#239]
**note:**  
__Eerste__ opdracht is overbodig aangezien dat aan het einde van de __tweede__ opdracht moet je dezelfde stappen doen. 
1. https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14595
2. https://jmbjojo.github.io/

**Comment by wooorm** [comment]
Nice work! Could you link to the GitHub Pages PR though?

**Comment by Jmbjojo** [comment]
You mean this one right? https://github.com/githubschool/on-demand-github-pages/pull/2266

**Comment by wooorm** [comment]
Yup! thanks @Jmbjojo!
