### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by Jmbjojo** [cmda-be/course-17-18#240]
**Markdown**

Italic & Bold
Italic: _Text_
Bold: **Text**

**Headers**
“#” makes text a header
Header one: # Text
Header two: ## Text 
Etc

Inline and reference links
Inline links: [Link text] (link.com)
Reference link: [Link Text] [Link reference]
[Link reference]: link.com

**Images**
Inline image: ![A representation of Octdrey Catburn](http://octodex.github.com/images/octdrey-catburn.jpg)
Reference image: ![The first father][First Father]
[First Father]:http://octodex.github.com/images/founding-father.jpg

**Blockquotes**
With the “greater than” caret you can make text/quote a blockquote.
When the text extends to multiple paragraphs the caret needs to be putted on every line including white space

Example: > text……..

**Lists**
unordered list: To create an unordered list, you'll want to preface each item in the list with an asterisk ( * ). Each list item also gets its own line
Ordered list: An ordered list is prefaced with numbers, instead of asterisks.

To make a list with more depth, or, to nest one list within another indent each asterisk one space more than the preceding item
* Milk
 *Submilk

1. Crack three eggs over a bowl.
Now, you're going to want to crack the eggs in such a way that you don't make a mess.
If you do make a mess, use a towel to clean it up!
To create this sort of text, your paragraph must start on a line all by itself underneath the bullet point, and it must be indented by at least one space.

**Paragraphs**
hard break: Putting white space between two lines
Soft break: Putting two spaces after each line

**Comment by wooorm** [comment]
Awesome! Well done!
