### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by BasPieren** [cmda-be/course-17-18#241]
Repository Link: https://github.com/BasPieren/dotfiles

Ik vond dit een erg leuke opdracht om aan te werken vooral omdat ik merkte dat ik steeds beter werd in het onthouden van verschillende basis dingetjes van Markdown, Git en Bash. 

Ik vond de vrijheid die je kreeg bij deze opdracht erg prettig omdat je dan zelf opzoek kan gaan naar verschillende informatie en dingen pas kan gaan toepassen als je ze ook echt snapt en weet wat ze doen.

**Comment by wooorm** [comment]
Great to hear @BasPieren! I’m super glad you liked it! 🎉

**Comment by wooorm** [comment]
Hey, so what’s a `motd` file? 🤔

**Comment by wooorm** [comment]
P.S. it looks like your alias is a relative path, right? maybe use an absolute path, then it would work everywhere!

**Comment by wooorm** [comment]
You should look into combining fortune and cowsay into a nice welcome message!

**Comment by wooorm** [comment]
Anyway, awesome work @BasPieren!
