### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Techdemo** [cmda-be/course-17-18#242]
![schermafbeelding 2018-02-11 om 21 56 14](https://user-images.githubusercontent.com/25225099/36078479-1fb9bc68-0f77-11e8-8b84-9dd86c2ae7dd.png)

Ging aardig. Echter, ik merk nog wel dat ik wat meters moet maken wil ik voor mijn gevoel lekker door een Command line heen fietsen. Practice makes perfect!

**Comment by wooorm** [comment]
Whoop whoop! Well done, I think the octocat assignment will be more useful if you’re trying to bike on the command line 🚲🤔😉
