### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by Timilof** [cmda-be/course-17-18#243]
assignment complete!
headings: #headieng1, ##heading2, ###heading3 etc...
Blockquotes: >This is a blockquote
Italics: *this is schuingedrukt*
Bold: __this is going to appear dikgedrukt__
images beginnen met een uitroepteken en in je [brackets] kun je je alt text schrijven, daarna zet je twee (haakjes) met de url van je afbeelding (inline): !(dit is een afbeelding)[www.voorbeeld.nl/afbeelding.jpeg]
images (referntie): 
![dit is een banaan][banaan]
[banaan]: www.voorbeeld.nl/banaan.jpeg

**Comment by rijkvanzanten** [comment]
**_Awesome!_**
