### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Timilof** [cmda-be/course-17-18#244]
eerste opdracht (dit was moeilijk)
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14455

tweede opdracht (deze was moeilijker)
https://github.com/githubschool/on-demand-github-pages/pull/2209

Tim Foli 
500741018
klas 208 / tech2

**Comment by rijkvanzanten** [comment]
Hey @Timilof! What parts of the assignment were hard in particular?
