### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by LocNguyen1994** [cmda-be/course-17-18#245]
Learned a lot!!
Link  GitHub Pages website:  https://locnguyen1994.github.io/

**Comment by LocNguyen1994** [comment]
![image](https://user-images.githubusercontent.com/36054537/36079301-e82d2fcc-0f81-11e8-98ef-8c131dfb87b7.png)

**Comment by wooorm** [comment]
@LocNguyen1994 Have you asked for help about that (in Slack)? I think several people have already figured it out!

**Comment by rijkvanzanten** [comment]
[Too late; didn't grade.](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#synopsis-5)
