### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by remcopasma** [cmda-be/course-17-18#246]
1: 
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14400 

2:
https://github.com/githubschool/on-demand-github-pages/pull/2208 

Ik vond de tweede opdracht lastig om te maken maar wel goed om de commando's goed te leren

**Comment by rijkvanzanten** [comment]
Awesome! I think you'll use most of these commands a lot more during the course, so you'll get some more valuable experience over time 😉
