### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by MonikaaS** [cmda-be/course-17-18#247]
- [https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14606](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14606)

- [https://github.com/githubschool/on-demand-github-pages/pull/2275](https://github.com/githubschool/on-demand-github-pages/pull/2275)

This is all new for me, so i find it still hard (but it's getting better). I thought these exercises were more usefull than the *try git* tutorial, I learned a lot from these asignments. 

![image](https://user-images.githubusercontent.com/36171561/36079469-7e51fee6-0f83-11e8-8a16-9600d5d4d759.png)

**Comment by rijkvanzanten** [comment]
Good job! 🐶
