### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Mimaaa** [cmda-be/course-17-18#248]
I already configured my development environment before starting this course, so I didn't do most of the stuff because the oh-my-zsh framework which I'm using for the zsh shell already has, for example, built-in aliases which I'm accustomed to. I don't want to mess too much with the configs, because I'm content with the current ones.

My .files and explanations for those can be found right [hereeee](https://github.com/Mimaaa/dotfiles).

I did find find the https://github.com/drduh/macOS-Security-and-Privacy-Guide quite interesting and am implementing some measures to protec my device.

**Comment by wooorm** [comment]
Super, awesome work @Mimaaa! I hope the macOS guide is useful, it’s a lot to take in! 🎉

**Comment by wooorm** [comment]
Ohh and could you add a screenshot of your terminal? I’d like to see how it looks! 👍

**Comment by Mimaaa** [comment]
Of course!

<img width="1043" alt="screen shot 2018-02-12 at 09 14 51" src="https://user-images.githubusercontent.com/12242967/36087936-d39bd8ba-0fcc-11e8-8ca4-1c37ed469787.png">

**Comment by wooorm** [comment]
```js
JSON.parse(fs.readFileSync('hello_titus.json'))
//=> [SyntaxError: JSON Parse error: Unexpected EOF]
```

😢
