### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by jessiemasonx** [cmda-be/course-17-18#250]
Closed PR from the Introduction to GitHub exercise: 
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14557

The GitHub Pages website from GitHub Pages from the Command Line exercise:
https://github.com/githubschool/on-demand-github-pages

I'm not sure if these are the links you asked for?

The second exercise was definitely more difficult than the first. Especially in the end when I didn't understand what my syntax error meant. I was very happy that the teacher could help me out, otherwise I wouldn't have had a clue what to do. I did find the exercises very interesting and I feel like i've learned a lot.

**Comment by wooorm** [comment]
For the last part I was looking for this url: https://github.com/githubschool/on-demand-github-pages/pull/2276

I’m glad you learned a lot! Good luck with the profile assignment! :)
