### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by RobinStut** [cmda-be/course-17-18#251]
De uitleg voor markup was duidelijk en makkelijk te volgen. Het nut van Markup is me nog niet helemaal duidelijk, maar daar kom ik komende dagen wel achter

**Comment by wooorm** [comment]
Could you show us something you learned?

> In your issue, include some of the markdown you have learned (like headings, lists, and more).

— https://github.com/cmda-be/course-17-18/blob/master/week-1.md#markup

**Comment by rijkvanzanten** [comment]
[Too late; didn't grade.](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#synopsis-2)
