### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by RobinStut** [cmda-be/course-17-18#252]
Het overtypen van bepaalde commands was voor mij niet echt leerzaam, het idee achter git is me wel duidelijk geworden

**Comment by wooorm** [comment]
@RobinStut What code did you get?

**Comment by wooorm** [comment]
Oh whoops, sorry, I thought this was run. Nevermind. This looks good!
P.S. I think you’ll like octocat, it’s way more practical!
