### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by AnneleenK** [cmda-be/course-17-18#253]
#Markup

**Dit is de _Markup_ opdracht van Anneleen Kramer.**

###Mijn Hond
Dit is een foto van mijn hond Satu.
![Satu](https://www.instagram.com/p/xJkC-7tXgopAMijlGZMgHKWf_4Wz1-uUsFH3Y0/?taken-by=anneleenkramer)
Soms post ik foto's van hem op [Instagram](http://instagram.com)

**Comment by wooorm** [comment]
Super! P.S. you need to type a space between the hashes and the contents for them to turn into headings!
