### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by sterrevangeest** [cmda-be/course-17-18#254]
### Introduction to GitHub
Very detailed instructions, which makes it almost impossible to fail :) First my pin didn't seem to appear. But found it now. 
![screencapture-github-githubschool-open-enrollment-classes-introduction-to-github-pull-14627-1518428917254](https://user-images.githubusercontent.com/32976396/36094835-0a441a76-0ff0-11e8-957d-0b884ec44f10.png)
<img width="1158" alt="schermafbeelding 2018-02-12 om 12 27 39" src="https://user-images.githubusercontent.com/32976396/36094875-2cd9a5e2-0ff0-11e8-8d3a-c7d75869a901.png">

### GitHub Pages from the Command Line
Learned a lot from the last part of the exercise, where they give you less detailed instructions. 
![screencapture-github-githubschool-on-demand-github-pages-pull-2294-1518435052301](https://user-images.githubusercontent.com/32976396/36094998-a3b064ee-0ff0-11e8-93ea-548a7d8012f7.png)

**Comment by wooorm** [comment]
Super, well done @sterrevangeest! P.S. Don’t forget the try git assignment btw!

**Comment by wooorm** [comment]
Oh whoops, I see missed the try git issue! 😬
