### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by jelub2** [cmda-be/course-17-18#255]
# My First piece of Markdown in a header 1
## And this is a header 2 

short summary of things I learned in markdown.
1. Headings
2. Lists
3. Images / Links
4. Blockquotes

list with things we use for this project
* Slack
* Git
* **GitHub** Bold
* Bash _Shell_ italic

> This is a blockquote with it's own style

[Jelmer's Github](https://github.com/jelub2)

![Potato](https://cdn.shopify.com/s/files/1/1017/2183/t/2/assets/live-preview-potato.png?8184428047766126492)

**Comment by wooorm** [comment]
Awesome work @jelub2!
