### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by ninavanbergen** [cmda-be/course-17-18#257]
Deel 1 link: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14556 
Deel 2 link: https://github.com/githubschool/on-demand-github-pages/pull/2277 

Ik vond de opdrachten interessant maar wel soms ingewikkeld, gelukkig kwam ik er uiteindelijk wel uit.

**Comment by wooorm** [comment]
Well done @ninavanbergen! Super awesome!
