### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by aman233** [cmda-be/course-17-18#258]
Completed 2018-02-11

**Comment by wooorm** [comment]
Nice! Could you give me some info on what you learned though?

> If you completed the markdown tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. In your issue, include some of the markdown you have learned (like headings, lists, and more).

— https://github.com/cmda-be/course-17-18/blob/master/week-1.md#markup

**Comment by aman233** [comment]
The tutorial is a bit buggy but really forces you to learn and use your newfound technique multiple times to remember them. Although I do think I'll have to look them up again occasionally.

**Comment by rijkvanzanten** [comment]
**_Cooooooooooooooooolio_**
