### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by jesseDijkman1** [cmda-be/course-17-18#259]
![schermafbeelding 2018-02-12 om 12 41 35](https://user-images.githubusercontent.com/36187451/36095379-4aea48f0-0ff2-11e8-8089-c32ddf9e173c.png)

The assignment was (like you said) incredibly vague. Google was my best bud while doing this assignment. I kept my prompt small and had some trouble choosing the right color. (Didn't change the background, I tried it in the preferences but didn't go well with the prompt. I might change it later)

**Comment by wooorm** [comment]
Awesome!!! Hey, could you link to your dot files though?!

**Comment by jesseDijkman1** [comment]
Definitely

https://github.com/jesseDijkman1/dotfiles

**Comment by wooorm** [comment]
Awesome stuff! I like the `vbp` and `fresh` aliases a lot!
