### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by aman233** [cmda-be/course-17-18#260]
Completed 2018-02-06

**Comment by wooorm** [comment]
Very good, what did you think though?

> That’s it! Well done you! If you completed the tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. Let us know in the issue if you liked this assignment, and give us any feedback.

— https://github.com/cmda-be/course-17-18/blob/master/week-1.md#description-1

**Comment by aman233** [comment]
I think learning code through use is the best way to learn it. Even though the tutorial itself is very easy since it makes you write down whatever it is showing, the assignment familiarised me with git code and how to use it.

**Comment by rijkvanzanten** [comment]
Awesome! 🎉
