### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by gitelig** [cmda-be/course-17-18#261]
# Markup 

1. ## Headers, italic and bold:

* **Bold**
* _Italic_ 
* #### Heading H4

2. ## Links
[I love Moodle!](https://moodle.cmd.hva.nl/my/) _(inline link)_
![Cross between an octopus and a cat](https://i.imgur.com/SvwTNIy.jpg) _(inline image link)_

3. ## Blockquotes
> "The assignments need to be done before 00.03 PM, I need to hurry!!!"
>
> "Keep in mind that the blank lines must contain the caret character **>**"
>
> "This ensures that the entire blockquote is grouped together."

4. ## Lists 
Ordered:
1. One
2. Two
3. Three

Unordered:
* Butter
* Cheese
* Egg

5. ## Paragraphs

in his white light dreams  ··
at Discovery Hut  ··
Herbert Ponting meets  ··
the Siberian ponies  ··
he’d once photographed  ··
on the Terra Nova  ··

the ponies no longer flexible  ··
refuse to wear  ··
equine pajamas  ··
or trap their hooves  ··
in bamboo snowshoes  ··
for his Royal Collection  ··

inside the stomach of ice  ··
the ponies more still  ··
than life soften ·· 
the silver shadows  ··
of Scott and his team  ··
and turn from Herbert’s bromide ·· 

into the drift ··  
and whiff of themselves  **(Each dot stands for a space. This '·' character is called an interpoint)**

**Comment by wooorm** [comment]
Superrr! haha, interpoints!
