### ISSUE TITLE
Markup assignment 

### ISSUE THREAD

**Issue by sterrevangeest** [cmda-be/course-17-18#262]
#### _What I learned_

1. Make a list
2. With ordered items

[Made a link to :rabbit: images](https://www.google.nl/search?biw=1058&bih=690&tbm=isch&sa=1&ei=ZYKBWujgJ8yVkwWyhpLoAw&q=rabbit&oq=rabbit&gs_l=psy-ab.3..0i67k1j0l9.827.827.0.1241.1.1.0.0.0.0.61.61.1.1.0....0...1c.1.64.psy-ab..0.1.60....0.8z36WEH6Dd8)
And found [this](https://gist.github.com/rxaviers/7360908) :nerd_face: 

~~**bit late, sorry**~~

**Comment by wooorm** [comment]
Very nice!! 🤓 And thanks for all the cute rabbits, and for the emoji!
