### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by jeroentvb** [cmda-be/course-17-18#264]
I learned more with this assignment than with the "try git" one 👍 

[Introduction to git closed pull request](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14371)

[My github pages website](https://jeroentvb.github.io/)

**Comment by wooorm** [comment]
Nice! Could you link to the PR that was closed for the pages part?

**Comment by jeroentvb** [comment]
(Yup)[https://github.com/githubschool/on-demand-github-pages/pull/2171]

**Comment by rijkvanzanten** [comment]
Cooolio!

@jeroentvb It's the other way around 😉  `[alt](url)` instead of `(alt)[url]`

**Comment by jeroentvb** [comment]
I noticed, was a little too quick when posting that link
