### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Techdemo** [cmda-be/course-17-18#265]
First part of the assignment: 
[Introduction to GitHub](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14631)
[Link to my Github pages](https://techdemo.github.io)

I've enjoyed this assignment. Learned a lot.

**Comment by wooorm** [comment]
Sweet! could you link to the PR that was closed for the pages part?

**Comment by Techdemo** [comment]
@wooorm you mean [this link?](https://github.com/githubschool/on-demand-github-pages/pull/2301)

**Comment by rijkvanzanten** [comment]
Yep! That's the one 🙂
