### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by khualu** [cmda-be/course-17-18#266]
**Dit is van de eerste helft van de opdracht**
closed PR: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14630

** Dit is van de Command Line gedeelte **

https://github.com/khualu/khualu.github.io/pull/1
https://github.com/githubschool/on-demand-github-pages/pull/2302

**Comment by wooorm** [comment]
Super! Hey, I saw you didn’t hand in the markup / try git assignment! Don’t forget those!

**Comment by khualu** [comment]
Ik wil even mezelf verbeteren, want ik heb blijkbaar de username.yaml aangepast. **Oops**
https://github.com/githubschool/on-demand-github-pages/pull/2313 hier is de andere.
