### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by RobinStut** [cmda-be/course-17-18#268]
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14555
https://github.com/githubschool/on-demand-github-pages/pull/2299

Die eerste ging wel prima, die tweede had ik over het hoofd gezien maar had hier wat meer problemen mee, had niet de juiste bestandsnamen gebruikt.

**Comment by rijkvanzanten** [comment]
Well done 👍
