### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by khualu** [cmda-be/course-17-18#269]
# h1
### h3

enzovoort  <- dit zou dan een paragraaf zijn (super meta om er zo over te praten omdat dit ook een paragraaf is)

*dit maakt een tekst italic* (één asterisk of één underscore)

**dit maakt een tekst bold** (dus twee asterisken of twee underscores)

Je kan een lijstje maken van dingen die ongeordend zijn
* Paarden
* Pferden
* Horses

of van dingen die geordend zijn
1. Goud
2. Zilver
3. Brons

En images linken

Zoals deze van grote vriend _H E N K_ ![Henkieeeee](https://50pluspartij.nl/images/2016/mensen/mensen_henk_krol.jpg)

en naar een ander adres linken, zoals deze [super vette partij](https://50pluspartij.nl/)

**Comment by rijkvanzanten** [comment]
**_Awesome stuff 😄_**

**Comment by khualu** [comment]
_A E S T H E N K I C S_
