### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by RobinStut** [cmda-be/course-17-18#270]
https://github.com/RobinStut/dotfiles

Ik heb deze week vooral gebruikt om zo veel mogelijk te oefenen in bash en heb daarbij deze tutorial gevolgd: https://www.youtube.com/watch?v=oxuRxtrO2Ag
Ik had problemen met het installeren van cowsay of lolcat, dus heb een ander welkomsbericht gemaakt. Qua aliases heb ik er nu een aantal, maar nog niet veel toegevoegd, omdat shortcuts voor mij op dit moment nog niet het belangrijkste zijn. Dit wil ik komende weken wel gaan doen.

![schermafbeelding 2018-02-12 om 14 52 48](https://user-images.githubusercontent.com/24225619/36099872-775a7952-1004-11e8-9a93-c96acc43bc82.png)

**Comment by rijkvanzanten** [comment]
Awesome stuff! 🎉
