### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by NathanKeyzer** [cmda-be/course-17-18#271]
# Tutorial Completed

I think this tutorial is very helpful to try out git!

I followed every step but not every step is saved in my head, so i have to look back for some steps.

Learned:
* Checking status
* Committing
* Differences
* Pushing remotely
* Resetting
* Merge

I will develop during these projects.

**Comment by rijkvanzanten** [comment]
`git commit -am 'Well done'`
