### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by MonikaaS** [cmda-be/course-17-18#272]
[Dotfiles](https://github.com/MonikaaS/dotfiles)

Learned a lot!

**Comment by rijkvanzanten** [comment]
Awesome!

I noticed the screenshot in your readme seems to be broken.. :( Could you fix that? I'd love to see your personal setup 🙂

**Comment by wooorm** [comment]
@MonikaaS You can also upload images to github! So, if you upload `screenshot.png` to GitHub, you can link to it in your readme like so: `[screenshot of my terminal](screenshot.png)`!

**Comment by MonikaaS** [comment]
Thanks for the tip @wooorm . I hope it's working now? 🤔

**Comment by wooorm** [comment]
https://github.com/MonikaaS/dotfiles yes it does!
