### ISSUE TITLE
Octocat assigment

### ISSUE THREAD

**Issue by SlodderWolf** [cmda-be/course-17-18#274]
https://github.com/githubschool/on-demand-github-pages/pull/2285
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14615
https://github.com/githubschool/on-demand-github-pages/pull/2279

Training stappen waren gemakkelijk te volgen en vrij duidelijk. Echter verliep niet alles precies hoe het hoorde maar uiteindelijk is dit opgelost met behulp van @wooorm 🚀. Wanneer je nieuw bent met git en github was dit wel een lastige opgave maar daar leren we gelukkig weer van 🤓

**Comment by rijkvanzanten** [comment]
Good job! 🎉
