### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by admirai** [cmda-be/course-17-18#278]
**_Wat heb ik geleerd?_**
Bij de _markdown_ opdracht heb ik de basics aangeleerd van het stylen van een tekst met behulp van markdown. Zo weet ik onder andere nu hoe ik: 
1. (Un)ordered lists maak.
2. Tekst **bold** maak.
3. Images en tekst kan [linken].

[linken]: https://www.markdowntutorial.com

**Comment by rijkvanzanten** [comment]
**_Awesome stuff ✨_**
