### ISSUE TITLE
markdown tutorial

### ISSUE THREAD

**Issue by MartijnReeuwijk** [cmda-be/course-17-18#279]
Tutorial van markdown.
Lessons learnt volgende keer een issue aan maken met de juiste namen

**Comment by wooorm** [comment]
> If you completed the markdown tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. In your issue, include some of the markdown you have learned (like headings, lists, and more).

— https://github.com/cmda-be/course-17-18/blob/master/week-1.md#markup

**Comment by MartijnReeuwijk** [comment]
_*Volgende keer zal ik beter lezen! *_
[Oops](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

* Martijn's reading skills.
   * Bad.
   * Needs improvement.

> Lekker bezig martijn
>Quote: Martijn Reeuwijk

**Comment by rijkvanzanten** [comment]
**_Purrfect! 🐈_**
