### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by admirai** [cmda-be/course-17-18#282]
Hi, admirai! 👋
All done!  You’re now ready to continue with the steps found on GitHub.

You'll need this code:

  YWRtaXJhaQo=
MBP-van-Isabel:run Isabel$

**Comment by admirai** [comment]
Hi, admirai! 👋
All done!  You’re now ready to continue with the steps found on GitHub.

You'll need this code:

  YWRtaXJhaQo=
MBP-van-Isabel:run Isabel$

**Comment by admirai** [comment]
Hi, admirai! 👋
All done!  You’re now ready to continue with the steps found on GitHub.

You'll need this code:

  YWRtaXJhaQo=
MBP-van-Isabel:run Isabel$

**Comment by wooorm** [comment]
Nice! Thanks @admirai!
