### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by labraksam** [cmda-be/course-17-18#283]
Here is the [link](https://github.com/labraksam/dotfiles) to my dotfiles. 

I learned a lot of this course! 
I did the standard changes, will add some more later on :)

**Comment by wooorm** [comment]
Woohoo!
P.S. Could you add a screenshot to your readme? I’d like to know how it looks!

**Comment by wooorm** [comment]
Oh, and don’t forget the octocat assignment!

**Comment by labraksam** [comment]
i'll do! 
Had some issues at the second assignment of the octocat, will upload it in a bit :)

**Comment by labraksam** [comment]
![schermafbeelding 2018-02-12 om 21 41 38](https://user-images.githubusercontent.com/35467938/36118529-a49ffcc8-103d-11e8-8f85-2ac354b136fb.png)
