### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by gijslaarman** [cmda-be/course-17-18#286]
Introduction to GitHub exercise: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14638

GitHub Pages exercise: https://github.com/githubschool/on-demand-github-pages/pull/2312

Doable, had some trouble with the pages exercise, because I forgot to make a new branch. But I managed to fix that as far as I know.

**Comment by rijkvanzanten** [comment]
Coolio 👍
