### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by khualu** [cmda-be/course-17-18#288]
So I did finish the assignment during the lab last week. But I didnt make a screenshot or anything. Is this a problem?

**Comment by wooorm** [comment]
Just describe what you remember from the assignment!

**Comment by khualu** [comment]
To be very honest, I don't remember a lot of stuff, since I feel like I didn't learn a lot because it was mostly just giving the input that was displayed above. Although I feel like the sheet we got is very useful.  It did just help me finish the octocat assignement.

The tutorial tried to teach basic git commands as making a branch, making a file using git status to see what the difference is between the branch you're currently working on & the master. Furthermore, how to push these files to the masters. 

I hope this is enough.

**Comment by rijkvanzanten** [comment]
> since I feel like I didn't learn a lot because it was mostly just giving the input that was displayed above

This is very valid feedback! 👍
