### ISSUE TITLE
Octocat assignment 

### ISSUE THREAD

**Issue by civvx** [cmda-be/course-17-18#289]
Introduction to GitHub exercise: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14590

GitHub Pages exercise: https://github.com/githubschool/on-demand-github-pages/pull/2314

Very good exercise to learn the GitHub workflow! i did have some trouble with the last exercise with adding a file to the _pages folder but its fixed now!

**Comment by rijkvanzanten** [comment]
Good job! 👍
