### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by annettehoijtink** [cmda-be/course-17-18#290]
<img width="1920" alt="screen shot 2018-02-11 at 23 07 15" src="https://user-images.githubusercontent.com/22293353/36116668-5937a476-1037-11e8-9fae-d89a81c30032.png">

**Comment by rijkvanzanten** [comment]
Hey @annettehoijtink!

Could you show us some *Markdown* you've learned during this course?

> If you completed the markdown tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. In your issue, include some of the markdown you have learned (like headings, lists, and more).

**Comment by rijkvanzanten** [comment]
[Too late; didn't grade.](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#synopsis-2)
