### ISSUE TITLE
Dotfiles opdracht

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#293]
https://github.com/GuusDijkhuis/dotfiles

Dotfiles opdracht

**Comment by rijkvanzanten** [comment]
Coolio 😄 

Btw, some lines in the readme seem out of place?

**Comment by wooorm** [comment]
@GuusDijkhuis Looks like you meant to use code instead of block quotes? https://help.github.com/articles/creating-and-highlighting-code-blocks/
