### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by admirai** [cmda-be/course-17-18#294]
Bij [het laatste deel van de tweede octocat opdracht] liep ik vast en snapte ik het even niet meer.
 Het eerste deel ging mij daarentegen wel goed af. Ik vond het tweede deel van de octocat opdracht wel wat ingewikkeld en onduidelijker uitgelegd.

[Add coördinaten opdracht, octocat deel 1]
[Mijn website, octocat deel 2]

[het laatste deel van de tweede octocat opdracht]:https://services.github.com/on-demand/github-cli/github-flow-cli
[Mijn website, octocat deel 2]: https://admirai.github.io/
[Add coördinaten opdracht, octocat deel 1]: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14657

**Comment by rijkvanzanten** [comment]
Awesome! 🎉
