### ISSUE TITLE
Introduction to Git

### ISSUE THREAD

**Issue by SadisticSun** [cmda-be/course-17-18#296]
### Closed PR for *Introduction To Github*
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14625

### Link to Github Pages
https://sadisticsun.github.io/

**Comment by SadisticSun** [comment]
Fun to do and easy enough for beginners, but I already have experience with GitHub/GitLab and Git in general.

**Comment by rijkvanzanten** [comment]
Awesome 🙌
