### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by aman233** [cmda-be/course-17-18#297]
Introduction: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14596

Command line exercise: https://github.com/githubschool/on-demand-github-pages/pull/2296

The first exercise taught some straight forward features that can be used on github like editting a file within github itself.

The second exercise was hammering the nail down on the things i learned in the first exercise and a bit more

The only thing I'm bothered by is that the instructions make it a bit too simple. The instructions taught me how to do something not learn something.

**Comment by rijkvanzanten** [comment]
>  The instructions taught me how to do something not learn something.

Interesting point! If I understand you correctly, you know _how_ to do it, but not necessarily _why_ or _what_ exactly?

**Comment by aman233** [comment]
Yes that’s exactly what I meant.

**Comment by rijkvanzanten** [comment]
Hopefully by using it during the rest of the course, things start clearing up a bit :)

**Comment by wooorm** [comment]
@aman233 Yeah, I get that, I think several people feel that way. My theory is that, if you first start doing a bunch of things, even if you don’t get why you do them certain ways, it makes it easier to grasp why you do them that way later on, when you’re building useful things? Does that make sense? Maybe it’s wrong, but I hope I’m right :)
