### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by remcopasma** [cmda-be/course-17-18#298]
Ik vond dit een best lastige opdracht waarbij je veel zelf moest uitzoeken. Op deze manier leer je wel veel dus ik vond dit een goede opdracht!

https://github.com/remcopasma/remcopasma.dotfiles

**Comment by rijkvanzanten** [comment]
Aight! The actual dotfile is pretty minimal.. Did you spend the allotted 3.45h on this assignment?
