### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by GitGitGitta** [cmda-be/course-17-18#299]
Thanks to the interactive tutorial I learned quite a bit about Markdown.

### Examples
Here's a quick overview of the things I picked up on through the tutorial and definitely will be using here on GitHub or other text files.

#### Headers 
> #< h1 > tag
> ##< h2 > tag
> ###< h3 > tag

#### Emphasis
Put emphasis on text, by making it either _italic_ or **bold**.

##### Unordered lists
* Thing 1
* Thing 2
  * Thing 2.1
  * Thing 2.2

##### Ordered lists
1. Thing 1
2. Thing 2
3. Thing 3

#### Images and Links
What is GitHub without it’s beloved octocat, find your favourite figurines [here](https://www.google.nl/search?q=octocat&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjxsuPno6HZAhWJiiwKHV2sAsAQ_AUICigB&biw=1395&bih=803&dpr=2)!

But, because I like cats and dogs equally: here’s a photo of a cute chew-wha-wah with matching octocat harness.

![Chihuahua dog with octocat harness](https://pbs.twimg.com/media/CQVzxvVUEAAf6Er.jpg)

_Boa Noite!_

**Comment by rijkvanzanten** [comment]
**_Tchau!_** 🌝

**Comment by GitGitGitta** [comment]
:octopus:

**Comment by rijkvanzanten** [comment]
🐡
