### ISSUE TITLE
Run assignment 

### ISSUE THREAD

**Issue by Techdemo** [cmda-be/course-17-18#30]
Ik heb de Run assignment gedaan.
> VGVjaGRlbW8K

**Comment by wooorm** [comment]
Did you do the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites)? We don’t have your username in our records.

**Comment by Techdemo** [comment]
Hey Titus, 


My GitHub username is:  Techdemo

**Comment by wooorm** [comment]
Thanks @Techdemo! P.S., if you respond here (with email), that response is posted on GitHub. You’re not talking to me, you’re talking to everyone!
