### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by iSirThijs** [cmda-be/course-17-18#301]
Here you go -> [dotfiles](https://github.com/iSirThijs/dotfiles)

enjoy 😃

**Comment by rijkvanzanten** [comment]
Awesome stuff! Did you come up with all this yourself or did you find a good tutorial? 🙂 

(Not that that's a bad thing, just curious ^^) (If so, might be worth adding it in a comment for future reference)

**Comment by iSirThijs** [comment]
Mostly made it myself trough trial and error. Only some minor issues where googled, mostly syntax. 😄. Also had some minor experience with it due to other "hobbies"
