### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by jessiegouw** [cmda-be/course-17-18#303]
## Nice challange 💪 
Here is the link to my **[dotfiles](https://github.com/jessiegouw/dotfiles)**

This assignment was a good challenge, it's good that you let us wrestle with the terminal so we get to learn by ourselves to learn commands fast. Some aliases save a lot of time!!

**Comment by rijkvanzanten** [comment]
Awesome stuff!

Quick note though, you have the [`git` ZSH plugin](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git) activated which adds a bunch of git aliases for you! The git aliases you added in there are duplicates 🙂

**Comment by jessiegouw** [comment]
Aaah if I get it right, I basically can delete the whole 'git' map?

**Comment by rijkvanzanten** [comment]
Nonono, I was referring to your `git` aliasses in your `.zshrc`. Specifically these ones:

https://github.com/jessiegouw/dotfiles/blob/master/zsh/.zshrc#L40-L53

**Comment by jessiegouw** [comment]
Aaaah I see, I will fix it tomorrow morning.

Thanks for providing this feedback!
