### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by lauraesmee** [cmda-be/course-17-18#304]
https://services.github.com/on-demand/intro-to-github/you-completed-github-flow
https://services.github.com/on-demand/github-cli/merge-pull-request-github-showcase
https://lauraesmee.github.io

dit vond ik echt heeeeel lastig...

**Comment by rijkvanzanten** [comment]
> dit vond ik echt heeeeel lastig...
You did it tho, congrats 😄 

Could you please share the link of the closed PR though 🙂 ?

> If you completed the exercises, mark this assignment as complete by opening an issue on our GitHub issue tracker. Include two links in your issue: **one to the closed PR from the Introduction to GitHub exercise**, the other to the GitHub Pages website from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.

**Comment by lauraesmee** [comment]
@rijkvanzanten sorry! Here is the link of the closed PR.
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14658

**Comment by rijkvanzanten** [comment]
Technically, the submission was too late... But since your PR already got merged before the deadline, I'll count it as passed 👍
