### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by tomoversluizen** [cmda-be/course-17-18#307]
[Dotfiles Repository](https://github.com/tomoversluizen/dotfiles)

I sometimes stumbled upo to some difficulties, but I was able to solve them myself. I am going to alter my dotfiles a bit more, but I think that this is a perfect beginning!

**Comment by rijkvanzanten** [comment]
Certainly a nice start 🙂 

Might be worth to combine `.bashrc` and `.bash_profile` into one file to prevent confusion in the long run!
