### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Timilof** [cmda-be/course-17-18#308]
https://github.com/Timilof/Timilof.dotfiles/tree/master

:)

**Comment by rijkvanzanten** [comment]
Well done 🥇 🎉

**Comment by wooorm** [comment]
AWESOME @Timilof!

**Comment by wooorm** [comment]
But who is Hetty? 🤔

**Comment by Timilof** [comment]
Mijn vriendin die me heeft geholpen

**Comment by Timilof** [comment]
shoutout Hetty <3

**Comment by wooorm** [comment]
haha vet :)
