### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by iSirThijs** [cmda-be/course-17-18#31]
Dit was wel handig, maar was wel gewoon overtypen ipv zelf uitvinden. 
<img width="827" alt="schermafbeelding 2018-02-06 om 13 21 30" src="https://user-images.githubusercontent.com/23125314/35859517-b0b2c77c-0b40-11e8-86d0-de72ec3ac1d5.png">

**Comment by wooorm** [comment]
Good! Maybe you’d like this as well! https://learngitbranching.js.org
