### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by sterrevangeest** [cmda-be/course-17-18#311]
[Link to dotfiles](https://github.com/sterrevangeest/dotfiles.git)
## struggles 
Had some troubles with permissions and rights when editing `.bash_profile` or `.bashrc`. 
Everytime editing the code I have to do: `chmod 777 .bash_profile` before doing: `source ~/.bash_profile`.

**Comment by rijkvanzanten** [comment]
Awesome! `z` does need some time to figure out what directories you frequent most, but after 2 or 3 manual `cd`s, it should start working with `z` too!
