### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by KjellRuiter** [cmda-be/course-17-18#312]
https://github.com/KjellRuiter/kjellruiter.dotfiles

Oooohh shit i did it 🌝 it's cool to personalize it

**Comment by rijkvanzanten** [comment]
Well done! 🌚 

Tip for next time; put the credits in the file / line where you actually got some help or where you used someone else's code. There is no way of knowing who did what in your dotfiles right now 😅

**Comment by KjellRuiter** [comment]
Oke zal er aan denken.👌🏼 Het is ook meer een SO eigenlijk omdat we aan het skype waren toen we het gemaakt hebben.
