### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by LocNguyen1994** [cmda-be/course-17-18#314]
https://github.com/LocNguyen1994/dotfiles

HET LUKT HELL YEAH

**Comment by rijkvanzanten** [comment]
Hey @LocNguyen1994!

Could you please add the credits to where you found the code? I notice the first 117 lines of your `.bashrc` are exactly the same as @JimvandeVen's.

https://github.com/LocNguyen1994/dotfiles/blob/master/.bashrc#L1-L117
https://github.com/JimvandeVen/dotfiles/blob/master/.bashrc#L1-L117

Ref #285

**Comment by wooorm** [comment]
Hey, gentlemen, what’s going on here? This looks a lot like plagiarism. Could you both DM me on Slack with what’s up?
