### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by labraksam** [cmda-be/course-17-18#316]
- [Introduction to Github exercise](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14376)

- [GitHub Pages from the Command Line](https://github.com/githubschool/on-demand-github-pages/pull/2332)

After 10million hours, it finally worked! 
Great course, step by step explanation is useful.  
Goes better with some more sleep I think. :)

**Comment by rijkvanzanten** [comment]
Good job and good night! 🌝
