### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Techdemo** [cmda-be/course-17-18#317]
![schermafbeelding 2018-02-12 om 23 59 33](https://user-images.githubusercontent.com/25225099/36124575-d804fd26-1050-11e8-8495-dd169609102b.png)
My first attempt at bashprofile

https://github.com/Techdemo/dotfiles

**Comment by rijkvanzanten** [comment]
Good job! That green on black has some very hacky vibesss 😎 

![Matrix](https://media.giphy.com/media/A06UFEx8jxEwU/giphy.gif)
