### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by sarkis1997** [cmda-be/course-17-18#319]
https://github.com/sarkis1997/dotfiles

Learned a lot.

**Comment by rijkvanzanten** [comment]
Hey @sarkis1997! I'm getting a 404 on that repo.. Did you make a typo?

**Comment by rijkvanzanten** [comment]
It's not on [your profile page](https://github.com/sarkis1997?tab=repositories) either..

**Comment by sarkis1997** [comment]
@rijkvanzanten Should work now, I was still busy getting the dotfile right in my depository.

**Comment by rijkvanzanten** [comment]
Hey @sarkis1997, thanks for uploading the repo. Next time, please do the assignment _before_ handing it in, since we will often grade right away when a notification comes in 😉 

Your dotfile is very _very_ minimal.. Whaddaya think @wooorm?

**Comment by wooorm** [comment]
Yeah it’s not a lot! I think it’s okay for this assignment though, but I would like to ask you to keep thinking about your dotfiles the coming weeks and adding more aliases in the future!
