### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by jeroentvb** [cmda-be/course-17-18#32]
# _This_ is some **text** written with **_markdown_**.
## This is a level 2 heading

**_Markdown_** is 
1. Lightweight
* a markup language 

Some  
text

This is an image of a cat: 
![A cat](https://s7d1.scene7.com/is/image/PETCO/cat-category-090617-369w-269h-hero-cutout-d?fmt=png-alpha)

[I'm a link to a cat image][cat]

[cat]: https://s7d1.scene7.com/is/image/PETCO/cat-category-090617-369w-269h-hero-cutout-d?fmt=png-alpha

**Comment by wooorm** [comment]
Very nice!
