### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by NathanKeyzer** [cmda-be/course-17-18#324]
# Completed

First i have completed de [Introduction to Github](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14667). This exercise was very easy to follow.

The second Exercise [Github Pages from the Command Line](https://github.com/githubschool/on-demand-github-pages/pull/2334) was a bit difficult and took me a lot of tie to complete this one. 
For some reason there is a URL of an other person inside my branch.

**Comment by rijkvanzanten** [comment]
Awesome! You must've cloned the repo at a point where there was already a failing test in place. Your PR and submission looks perfect
