### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by bengtbennink** [cmda-be/course-17-18#327]
https://services.github.com/on-demand/intro-to-github/you-completed-github-flow
https://services.github.com/on-demand/github-cli/merge-pull-request-github-showcase

**Comment by rijkvanzanten** [comment]
Hey @bengtbennink!

These are not the requested links..

> Include two links in your issue: **one to the closed PR from the Introduction to GitHub exercise**, **the other to the GitHub Pages website** from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.

Also, please keep [the deadline](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#synopsis-5) in mind when submitting the next assignments.
