### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by chelseadoeleman** [cmda-be/course-17-18#331]
[Github intro](https://services.github.com/on-demand/intro-to-github/you-completed-github-flow)

[Github add page](https://services.github.com/on-demand/github-cli/merge-pull-request-github-showcase)

Duidelijke en leerzame opdrachten! Was soms nog wel even zoeken.

**Comment by rijkvanzanten** [comment]
Hey @chelseadoeleman!

Could you please share the links to the Pull Request, as requested in the assignment? 🙂 

> If you completed the exercises, mark this assignment as complete by opening an issue on our GitHub issue tracker. Include two links in your issue: **one to the closed PR from the Introduction to GitHub exercise, the other to the GitHub Pages website** from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.

**Comment by chelseadoeleman** [comment]
This one?

https://chelseadoeleman.github.io/chelseadoeleman.GITHUB.IO/

**Comment by chelseadoeleman** [comment]
@wooorm 
https://github.com/githubschool/on-demand-github-pages/issues/2269
https://github.com/githubschool/on-demand-github-pages/pull/2270

**Comment by wooorm** [comment]
@chelseadoeleman Awesome! Thanks and well done! 🎉
