### ISSUE TITLE
Profile Assignment

### ISSUE THREAD

**Issue by superstephan1** [cmda-be/course-17-18#335]
[Klik voor mijn Github](https://github.com/superstephan1/profiles)

Had beetje moeite met op gang komen en wist niet wat ik met de dotfiles aan moest. Na het lezen van de tip artikelen kwam ik er wel uit.
<img width="572" alt="screen shot 2018-02-14 at 11 40 43" src="https://user-images.githubusercontent.com/33251720/36201607-cd64bd94-1180-11e8-9e65-b471e16ecc5d.png">

**Comment by Rowin206** [comment]
Very nice and clear!

**Comment by rijkvanzanten** [comment]
Good job! 😄
