### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by maanlamp** [cmda-be/course-17-18#337]
Done 💪
![Gekke badge](https://d13jv82ekraqyq.cloudfront.net/assets/badge-course-a3b204c1384a3b43b332f66c5fe9d96b.png)

**Comment by rijkvanzanten** [comment]
Hey @maanlamp! What did you think of the assignment? 🙂 

> That’s it! Well done you! If you completed the tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. **Let us know in the issue if you liked this assignment, and give us any feedback.**

**Comment by maanlamp** [comment]
Was wel gaaf. Vind het zelf net iets té losjes om er echt van te leren. Vooral dat je de command gewoon kan "inklikken" zonder iets te doen vond ik een beetje tegenstrijdig. Gelukkig had ik al een beetje verstand van git.

**Comment by rijkvanzanten** [comment]
Coolio 👍
