### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by maybuzz** [cmda-be/course-17-18#338]
# Markdown opdracht

**Markdown** is so much _fun_ !

I learned how to create

* Textdecorations
* Headings
* Links
* Images
* Blockquotes
* Lists

See ya!

![YES WE CODE](http://xaharts.org/funny/i/gitopuss/github-octocat_yes-we-code.jpg)

**Comment by rijkvanzanten** [comment]
**_Awesome! 💯_**
