### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by chrisbruin94** [cmda-be/course-17-18#339]
italic, bold, header, links, images, blockquots, lists, paragraphs.

**Comment by wooorm** [comment]
Hi @chrisbruin94! You’re not in your admin files. Are you registered with us?

**Comment by wooorm** [comment]
@chrisbruin94 Ping!

**Comment by wooorm** [comment]
Hi @chrisbruin94! Unfortunately, the deadline has passes quite some days ago, but you haven’t worked to fix the issue pointed out above. I’m marking this assignment as not on time.
