### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by maybuzz** [cmda-be/course-17-18#340]
Here is the link to my closed PR: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14518

Here is the link to my GitHub Pages website: https://maybuzz.github.io/GITHUB.IO/

De eerste opdracht ging prima, nog een beetje onduidelijk af en toe maar dat komt doordat het nieuw is. 
De tweede opdracht snapte ik eigenlijk vrij weinig van... Volgens mij doe ik het ook niet helemaal goed maar ik heb ook geen idee wat ik dan niet goed doe :(
Bij de laatste stappen waarbij je de laatste pull request aanmaakt gaat het fout, hij wil deze niet goedkeuren ofso...

**Comment by rijkvanzanten** [comment]
Hey @maybuzz! Could you please share the link to the second PR? Lets try to figure out why it's not working 😄

**Comment by maybuzz** [comment]
https://github.com/githubschool/on-demand-github-pages/pull/2354

**Comment by rijkvanzanten** [comment]
It seems like the testing suite is checking other peoples their PRs at the same time, which makes yours fail for some reason... Anyway, your file looks good, the GitHub pages site is live so LGTM 😄

**Comment by maybuzz** [comment]
Thank god :)
