### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by AutoGeak** [cmda-be/course-17-18#341]
![bewijs van het afronden](https://i.imgur.com/702Rdrk.png)

**Comment by rijkvanzanten** [comment]
Hey @AutoGeak! Could you show us some markdown you've learned during the course? 🙂 

> If you completed the markdown tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. **In your issue, include some of the markdown you have learned (like headings, lists, and more).**

**Comment by wooorm** [comment]
Hi @AutoGeak! Unfortunately, the deadline has passes quite some days ago, but you haven’t worked to fix the issue pointed out above. I’m marking this assignment as not on time.
