### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Rowin206** [cmda-be/course-17-18#342]
# Profile repository
[Repository](https://github.com/Rowin206/Rowin206-dotfiles)

# My thoughts 
It was very fun to see the things you've changed. Also very challenging. In addition to the exercise itself, the adjustments also help to keep an overview. Please see my screenshot of the final result: 

<img width="761" alt="screen shot 2018-02-14 at 18 58 31" src="https://user-images.githubusercontent.com/33234293/36219881-1c83c248-11b9-11e8-8d54-fc3075303932.png">

**Comment by rijkvanzanten** [comment]
Awesome! 🚗💨
