### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by AutoGeak** [cmda-be/course-17-18#344]
![bewijs van het afronden](https://i.imgur.com/nm6JqSE.png)

**Comment by rijkvanzanten** [comment]
Hey @AutoGeak! What did you think of the assignment? 🙂 

> That’s it! Well done you! If you completed the tutorial, mark your assignment as complete by opening an issue on our GitHub issue tracker. **Let us know in the issue if you liked this assignment, and give us any feedback.**

**Comment by wooorm** [comment]
Hi @AutoGeak! Unfortunately, the deadline has passes quite some days ago, but you haven’t worked to fix the issue pointed out above. I’m marking this assignment as not on time.
