### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by AutoGeak** [cmda-be/course-17-18#345]
![bewijs van het afronden](https://i.imgur.com/nm6JqSE.png)
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14736
https://autogeak.github.io/

**Comment by rijkvanzanten** [comment]
Hey @AutoGeak! It seems like the pull request has been denied due to the fact that you have trailing spaces after the values in your yaml file. Could you try removing those?

Also, what did you think of the assignment? 🙂

**Comment by wooorm** [comment]
@AutoGeak Could you try and fix this, and reply to this?

**Comment by wooorm** [comment]
Hi @AutoGeak! Unfortunately, the deadline has passes quite some days ago, but you haven’t worked to fix the issue pointed out above. I’m marking this assignment as not on time.
