### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#346]
# Profile assignment
## Files
[Dotfiles Repository](https://github.com/FJvdPol/dotfiles)

## Screenshot
![Bash terminal with multiple commands](https://oege.ie.hva.nl/~polf002/images/screenshot_terminal.png)

## Recap
Ik vond de opdracht zowel interessant als frustrerend, aangezien je echt helemaal zelf moet uitvinden hoe je je prompt aan past. Pas na anderhalf uur begon er wat resultaat te komen en uiteindelijk ben ik erg blij met mijn aanpassingen. 
Ik heb wat code uit bronnen gehaald maar deze eigenlijk grotendeels aangepast en eigen gemaakt.

**Comment by rijkvanzanten** [comment]
Awesome! 🎉 

What is that font btw? Looks very clean!

**Comment by FJvdPol** [comment]
The font is called Segoe UI! It is a microsoft font, so available by default on windows I think
