### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Kalemis** [cmda-be/course-17-18#348]
**Link to repository:**
[click here](https://github.com/Kalemis/dotfiles/blob/master/README.md)

De opdracht was heel erg vrij, wat het ook wat moeilijker maakt. Maar er was genoeg documentatie te vinden om zelf op onderzoek te gaan. Nadat ik door had dat ik zelf de .bash_profile file moest aanmaken, aangezien ik die niet had, heb ik niet echt problemen meer gehad.

**Comment by rijkvanzanten** [comment]
Thanks!
