### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by surferfelix** [cmda-be/course-17-18#349]
![screen shot 2018-02-14 at 17 01 42](https://user-images.githubusercontent.com/17074940/36214083-c49b9034-11a8-11e8-8bc2-9c92aa1c7ab1.png)

https://github.com/surferfelix/dotfiles

Uploading the file with git took a very long time as I had encountered some authentication issues. Actually being able to solve these issues on my own taught me a lot. The assignment itself was fun, I am really happy with how I got my terminal to look. I still have some questions about applying the alias, and I am slightly scared of doing something wrong and destroying my computer if I try to let it run automatically when my bash_profile is being opened when I launch terminal.

**Comment by wooorm** [comment]
Sweet! Don’t forget the octocat assignment!
