### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by joostflick** [cmda-be/course-17-18#352]
link to pages
https://github.com/joostflick/JOOSTFLICK.GITHUB.IO
link to pull request
https://github.com/joostflick/JOOSTFLICK.GITHUB.IO/pull/2

Good excercises, little tough sometimes but good learning experience

**Comment by wooorm** [comment]
Hey @joostflick! You didn’t link to the pull requests you needed to make to GitHub. Could you do that?

> If you completed the exercises, mark this assignment as complete by opening an issue on our GitHub issue tracker. Include two links in your issue: one to the closed PR from the Introduction to GitHub exercise, the other to the GitHub Pages website from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.

**Comment by joostflick** [comment]
My bad, here is the link to the closed PR:
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14644
forgot to include it.

**Comment by wooorm** [comment]
Thanks, but i also meant the one to https://github.com/githubschool/on-demand-github-pages

**Comment by wooorm** [comment]
Hi @joostflick! Unfortunately, the deadline has passes quite some days ago, but you haven’t worked to fix the issue pointed out above. I’m marking this assignment as not on time.
