### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Root-ish** [cmda-be/course-17-18#353]
Hoi, ik heb de Try git opdracht gemaakt,

In het begin vond ik het nog een beetje vaag maar toen ik voor de tweede keer door alle stappen heen liep werd het al een stuk duidelijker. 

Dit is de badge voor het voltooien van de opdracht
![badge-course-a3b204c1384a3b43b332f66c5fe9d96b](https://user-images.githubusercontent.com/25663646/36228212-f11c8c64-11d3-11e8-9f04-9d5826602e58.png)

**Comment by wooorm** [comment]
Super! Cool to hear that you did it twice!
