### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by Root-ish** [cmda-be/course-17-18#354]
Hoi, ik heb de Octocat opdracht gemaakt.

Dit is een linkje naar mijn pages website  https://root-ish.github.io
En dit een linkje naar de closed Pull request https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14730

Ik vond git in deze opdracht een stuk duidelijk worden door dat je de commands daadwerkelijk uitvoert. Ook was er gelijk een feedback waarin je kon zien of je het goed deed of niet echter miste ik wel het grafische overzicht uit de try git opdracht

**Comment by wooorm** [comment]
Nice! Could you just link to the PR on githubschool that adds your website?

> If you completed the exercises, mark this assignment as complete by opening an issue on our GitHub issue tracker. Include two links in your issue: one to the closed PR from the Introduction to GitHub exercise, the other to the GitHub Pages website from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.

**Comment by Root-ish** [comment]
Do you mean this PR ? https://github.com/githubschool/on-demand-github-pages/pull/2357

**Comment by rijkvanzanten** [comment]
Yup! 🎉
