### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by Root-ish** [cmda-be/course-17-18#355]
> Hoi, ik heb de **Markup opdracht** gedaan.

Ik vind het momenteel nog even lastig maar ik denk dat wanneer ik het meer ga _gebruiken/schrijven_ het zo heb geleerd. Het heeft niet veel weg van HTML en het is best logisch allemaal.

Een list maken is zelfs nog beter te doen dan in HTML: voor een unordered list gebruik je een Asterix * en voor een ordered list een 1. 2. 3. enz...

![19148112_431171063948388_7327212068082286592_n](https://user-images.githubusercontent.com/25663646/36228415-7203b546-11d4-11e8-94c0-7f0afbe55ec4.gif)
Tadaaa een gifje 

 Of een filmpje
 [![Carl Cox DJSounds Show](http://img.youtube.com/vi/UTHEQNdLcUI/0.jpg)](http://www.youtube.com/watch?v=UTHEQNdLcUI)

**Comment by wooorm** [comment]
Thanks for the images! That looks very nice! And it’s cool that you linked and image to something!
