### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by maanlamp** [cmda-be/course-17-18#357]
https://github.com/maanlamp/dotfiles

Ik wil wel een screenshot maken maar mijn Bash shell op ubuntu for windows ondersteunt geen emoji. Sad. Maar windows is nog steeds cooler dan mac 😠

Assignment was wel grappig. Bash is wel echt een lelijke taal... gatverdamme. WAAR HOREN NOU WEL OF GEEN PUNTKOMMA'S?!
AAARGGH;

**Comment by wooorm** [comment]
aargh!;;;;

Super cool, @maanlamp!

P.S. did you know that you almost never need semi-colons in JavaScript?

**Comment by wooorm** [comment]
P.S. Be careful with rm / rm -r, maybe use [trash](https://www.npmjs.com/package/trash-cli) when you get the hang of node and npm!
