### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by maanlamp** [cmda-be/course-17-18#358]
Closed pr:
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/issues/14747

Pages from command line:
https://github.com/githubschool/on-demand-github-pages/pull/2367

https://maanlamp.github.io

Edit:
Chrome Canary heeft blijkbaar extreme moeite met het laden van de contributions tabel. Helemaal de 'stable' standaard versie moeten downloaden... Je zou haast denken dat het gebruiken van een development versie niet slim is :/

**Comment by wooorm** [comment]
@maanlamp How do you mean it doesn’t work? This sounds like you haven’t finished this assignment.
Maybe ask a specific question on Slack?

**Comment by maanlamp** [comment]
Aangepast. Was ff helemaal klaar met Google Chrome 👎

**Comment by rijkvanzanten** [comment]
> Je zou haast denken dat het gebruiken van een development versie niet slim is :/

Hmmmmmmmmmmmmmmmmm 🤔 

Assignment LGTM tho 😄
