### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by surferfelix** [cmda-be/course-17-18#359]
Closed PR: https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14585

Github pages website: https://github.com/githubschool/on-demand-github-pages/pull/2359
Bij de pages website wil travis ci het niet goedkeuren. Dus ik heb iets fout gedaan en kan de oplossing hiervoor niet vinden. De rest lukte allemaal wel vrij gemakkelijk. Het eerste onderdeel ging vrij snel en ik had hier geen moeilijkheden mee. De opdracht was best nuttig om goed te kunnen begrijpen hoe je bestanden bewerkt en in je repository zet via de terminal.

**Comment by rijkvanzanten** [comment]
@surferfelix It gives this as reason for the reason it didn't pass:

```
Checking 1 external link...
- 
  *  External link surferfelix.github.io failed: 404 No error
```

It seems like your GitHub pages website isn't up and running, which makes it fail

**Comment by wooorm** [comment]
@surferfelix did you fix this yet?

**Comment by wooorm** [comment]
Hi @surferfelix! Unfortunately, the deadline has passes quite some days ago, but you haven’t worked to fix the issue pointed out above. I’m marking this assignment as not on time.
