### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Root-ish** [cmda-be/course-17-18#360]
Hoi, ik heb de Profile opdracht gemaakt.

Dit is het linkje er naar toe https://github.com/Root-ish/dot-files

> Who sees the human face correclty : the photographer, the mirror or the painter ? 
> -- Pablo Picasso---

**Comment by rijkvanzanten** [comment]
Awesome! 🎉 

> "The problem with quotes on the Internet is that it is hard to verify their authenticity."
~ Abraham Lincoln
