### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by DanielvandeVelde** [cmda-be/course-17-18#361]
https://github.com/DanielvandeVelde/dotfiles

Please don't read my readme.

**Comment by rijkvanzanten** [comment]
> Please don't read my readme.

The [urge to read your readme](http://www.businessinsider.com/why-people-dont-follow-directions-2013-8) doubled due to this 😂

**Comment by rijkvanzanten** [comment]
> Thats why I made an alias called alias fucking='sudo' so whenever I ask bash to fucking do something it will.

This 👏

**Comment by rijkvanzanten** [comment]
Good job 🎉 

Smart move to keep the aliases and prompt separated. Especially when the amount of aliases grows over the weeks/months/years 🙂
