### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by chelseadoeleman** [cmda-be/course-17-18#362]
https://github.com/chelseadoeleman/dotfiles

Ik vond de opdracht best lastig, vooral omdat je veel moet zoeken en vaak niet weet wat de code van anderen precies doet. 
Maar uiteindelijk was het moeilijkste gedeelte, om de bestanden in een repository krijgen. 
Heb er wel veel van geleerd! Er zijn mega veel mogelijkheden en extra's die nog toegepast kunnen worden!

**Comment by rijkvanzanten** [comment]
Good job!

Small question though, what's the difference between

```bash
  alias ..="cd .."      #Mapje omhoog
  alias .="cd ."        #Map omhoog uit huidige map
```
? And are you sure `cd .` moves you one directory up? 🙂
