### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by maybuzz** [cmda-be/course-17-18#363]
Niet helemaal de bedoeling (eigenlijk helemaal niet) maar heb in ieder geval een repo gemaakt!

https://github.com/maybuzz/dotfiles

Enjoy

**Comment by rijkvanzanten** [comment]
Hi @maybuzz! Appreciate the extra **Markdown** awesomeness, but I don't think I can give you the points for the `profile` assignments..

> Moet er dan ook bij zeggen dat de afgelopen week een overload aan informatie, talen en programma's is geweest en ik heel hard m'n best ga doen om bij te blijven.

This is very true! Godspeed the coming weeks 🙂
