### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by daoneandonly** [cmda-be/course-17-18#364]
I've documented everything in the readme.md.

https://github.com/daoneandonly/Dotfiles

**Comment by rijkvanzanten** [comment]
Hey @daoneandonly! Where did you get most of the files? Are these defaults in `cmder` or something? Bit hard to see what you added yourself or what was already there 🙂

**Comment by rijkvanzanten** [comment]
This .bashrc default is very similar to those other ones @wooorm, but there are some differences? Weird

**Comment by daoneandonly** [comment]
I've used the following sites as guides:
[Link1](https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html)
[Link2](http://www.hostingadvice.com/how-to/set-command-aliases-linuxubuntudebian/)
[Link3](http://ask.xmodulo.com/display-change-welcome-message-linux-terminal.html)

**Comment by daoneandonly** [comment]
I've changed .bashrc as it was, with some trial and error I found the lines I I needed to change.

**Comment by daoneandonly** [comment]
I had some difficulty changing the README.md. I had github initialize one for me and then pulled it to the ~ folder. I could only edit the README.md in vim and not through atom. Is this because of the ~folder? Is it because of atom? Is it me?

**Comment by rijkvanzanten** [comment]
> I've changed .bashrc as it was

This is the part that is causing the confusion. "Normally" there are no defaults in there 😁

**Comment by rijkvanzanten** [comment]
> I could only edit the README.md in vim and not through atom

How did you try opening the file? Atom should have no problem with opening dotfiles or the `~` folder

**Comment by daoneandonly** [comment]
> How did you try opening the file? Atom should have no problem with opening dotfiles or the ~ folder

atom readme.md would open a blank file. And any changes made would not save once opened again with vim. This was also happening for .bashrc and profile.

**Comment by rijkvanzanten** [comment]
What happens if you try opening it with the full path? `atom ~/readme.md`

**Comment by daoneandonly** [comment]
It still shows up empty. I'll ask around with other windows users if they're experiencing the same.

**Comment by daoneandonly** [comment]
Found a solution/work-around:
The bash shell is located in ``C:\Users\USERNAME\AppData\Local\Lxss``. Copying this into a File Explorer window will get you there. If you open the folder ``root`` all files (.bashrc .profile and README.md) are in here. You can edit from here. 

Atom for some reason opens these files as being in ``C:\Users\USERNAME``. This causes you to edit a file that's not the file used in bash.

[Source](https://superuser.com/questions/1110433/where-is-the-windows-bash-directory-in-windows)

**Comment by wooorm** [comment]
I think it’s a mixture of cmder, subshell, and windows! 🤷‍♂️

**Comment by wooorm** [comment]
Anyway, yeah, that’s weird, that you have to use the `appdata` stuff, it’s apparently pretty dangerous :(
