### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Mennauu** [cmda-be/course-17-18#365]
Ik ben nogal lang bezig geweest met het oplossen van permissie problemen (wat trouwens niet gelukt is, ha) in de bash terminal op m'n desktop computer (met windows). Hierdoor kwam ik wat tijd tekort om de opdracht 'volledig' te maken.

Op m'n macbook had ik gelukkig geen problemen en had ik de terminal al snel aangepast. Je kan m'n dotfiles en een afbeelding van m'n terminal via de link hieronder vinden.

https://github.com/Mennauu/dotfiles

**Comment by rijkvanzanten** [comment]
Pfffff don't get me started on those nasty Windows + Bash problems.. Have been wasting a lot of time on those lately myself too!

The dotfile is very minimal as you mentioned, but it's good enough. (And right on time for the deadline 😉)
