### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by theonejonahgold** [cmda-be/course-17-18#366]
Heya, finally done with the workshopper! It was quite fun, and I learnt a lot! Some steps were quite hard, but that's because I didn't RTFM 🤷‍♂️ . I'm quite sad that's it over, but it was fun while it lasted. 
😊 

![Final solution](https://user-images.githubusercontent.com/23699599/36282923-0904c2f4-12a3-11e8-8286-940c4f93392e.png)

![Completion mark](https://user-images.githubusercontent.com/23699599/36283286-57b5e1d4-12a4-11e8-90ff-c98a0c8eb11e.png)

**Comment by theonejonahgold** [comment]
![image](https://user-images.githubusercontent.com/23699599/36283111-ad97db62-12a3-11e8-84f2-c94836c3d55a.png)
Here is a screenshot of the passing mark of `learnyounode` itself

**Comment by wooorm** [comment]
@theonejonahgold OMG awesome! Did you check the other workshoppers? the other extra resources? if you have some extra time, those are awesome!
