### ISSUE TITLE
Learnyounode

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#367]
#339 
 Learnyounode

Finished the Learnyounode course, it was kinda hard due to the lack of experience so it was a lot of trying, using google and try again. But at the end of the course it was really helpful and i learned a lot of (new) stuff that will be very useful in this project. 

The steps follow up in a good tempo, and now that i've finished the course i also understand what they were asking for in the challenge. That was the hardest part of the course, understanding what elements you needed to use to complete the challenge. 

I struggled a bit at exercise 6 (Make it modular) with the filename extension not being modular. After some time It turned out the solution was just to bring the prefix in to the module itself.. Such a simple solution but somehow i overthinked the problem too much.

Also the time server took me quite some time to figure out and was in my understanding one of the more difficult ones to finish due to the formatting of all the timestamps.

I made notes from each challenge where i copied the solution and compared it to my solution to spot the differences. After that i tried to answer what part of the code created the solution on a specific problem given by the challenge.

## Conclusion
Overall a hard but good course which gives a lot of insight in node.js!

## Prove of completion
<img width="541" alt="screen shot 2018-02-15 at 22 38 30" src="https://user-images.githubusercontent.com/10829926/36282299-fed537ca-12a0-11e8-9651-6a84f81b8eb7.png">
<img width="548" alt="screen shot 2018-02-14 at 00 15 08" src="https://user-images.githubusercontent.com/10829926/36282300-fef216c4-12a0-11e8-98f6-a9f601c1e33f.png">

**Comment by wooorm** [comment]
Super well done @timruiterkamp! It’s weird right? How, with workshoppers, it’s so hard to read, but the solutions are often so simple? 🤔
