### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Maikxx** [cmda-be/course-17-18#368]
![Finished screenshot](https://raw.githubusercontent.com/Maikxx/LearnYouNode/master/Screen%20Shot%202018-02-16%20at%2015.15.12.png)

[Github Repo](https://github.com/Maikxx/LearnYouNode)

I found exercises two and thirteen to be the hardest. Two was hard, because I did not understand what they meant with the assignment, not even after reading all the hints. Also because I did not know the concept of checking if things are numbers like that yet (!isNaN && +number).

Thirteen was difficult, because I had to check for and give back on two different routes that got passed to the server. Furthermore, I found it quite fun to see my own innovations pass (if they did...).

I really dislike reading, so this was not particularly fun. Initially I wanted to do the other courses they offered too, but after doing this, I unfortunately don't. I am more of a 'lean-back' learner, I learn by watching video's or reading things which have clear images with them.

**Comment by wooorm** [comment]
Yes, reading is very hard, I know! And the solutions are often so easy!
Weird that two was hard. I mean, it isn’t easy getting into workshoppers, but summing an array? 🤷‍♂️
Anyway, most people in class 2 finished step 2 in the lab already, so if that’s hard, I’m hoping more people will do the other steps!

It’s a bit interesting for me to hear that you learn coding by leaning back. I think coding takes a passion, and the a bunch of work, to fix. I’m sure that basically nobody has learned coding by just watching youtube? You have to do stuff!

**Comment by Maikxx** [comment]
Well I think I need to clarify, I learn to know, what to do and make by watching videos, and then make them myself. Those are often full projects, so hence why this is a bit more difficult, but oh well haha.
