### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by jessiegouw** [cmda-be/course-17-18#369]
Here is the link to my package:
**[jessiegouw/package](https://github.com/jessiegouw/package)**

I liked this assignment, keep up the good work! 💪

**Comment by wooorm** [comment]
Nice work @jessiegouw! This is awesome!

Some things:

* The Installation & Usage example shows requiring `repeat-string`!
* `mocha` should be a dev dependency
* `repeat-string` should be in dependencies
* The line in your LICENSE file should probably read `Copyright (c) 2018 Jessie Gouw <andyouremail@goes.here>`!
* In your editorconfig, you don’t need `[*.json] indent_size = 4`, as the `[*]` already has the same `indent_size`!
* The tests look like a great start! You could use [npm scripts](https://css-tricks.com/why-npm-scripts/) btw so you don’t always need to call mocha on the command line (instead using `npm test`)
* the tests aren’t about the vowel package! 😉 It’s a great start, it really is, but maybe that’s something you’d like to investigate when you have time left! 💪

Anyway, [here’s the project](https://github.com/wooorm/f-ck) the code is from!

**Comment by jessiegouw** [comment]
Thanks for the feedback, it's all very clear! I'm going to investigate it for sure, even if I don't have the time for it lol
