### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by BasPieren** [cmda-be/course-17-18#37]
Dit zijn enkele Markdown elementen die ik heb geleerd:

**Headings:**
Deze worden gemaakt doormiddel van # t/m ###### 
# Heading 1
###### Heading 6

**Italic & Bold:**
Je maakt tekst **Bold** met ** en _italic_ met _  

**Lists:**
ordered list
1. punt 1
2. punt 2
3. punt 3

of

unordered list
* punt 1
* punt 3
* punt 4

**Links:**
Je maakt een link door je tekst in [] te zetten en dan je link in ()
[Een link naar google](www.google.com)

**Images:**
Een image werkt het zelfde als een link alleen gebruik je hier een ! voor alles.
![Het GitHub logo](https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png)

**Blockquotes:**
Je kunt een blockquote maken door > voor je tekst te zetten.

> Zo dus

**Comment by wooorm** [comment]
Sweet!
