### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by Maikxx** [cmda-be/course-17-18#370]
[GitHub Repository](https://github.com/Maikxx/BE1_Vowel)

To give me information I used:
* [repeat-string](https://github.com/jonschlinkert/repeat-string/blob/master/package.json): for fine-tuning the package.json.
* [longest-streak](https://github.com/wooorm/longest-streak/blob/master/package.json): for fine-tuning the package.json.
* [normalize](https://github.com/sindresorhus/normalize-url#readme): for fine-tuning the readme.
* [.editorconfig](http://editorconfig.org): for information about the .editorconfig file.
* [skin-tone](https://github.com/sindresorhus/skin-tone): for writing about licensing. 
* [choosealicence](https://choosealicense.com): for choosing a license.
* [Portfolio_Backend](https://github.com/Maikxx/Portfolio_Backend/blob/master/.gitignore): .gitignore.
* [11 npm tricks](https://nodesource.com/blog/eleven-npm-tricks-that-will-knock-your-wombat-socks-off/): just general reading.

I spent most of my time figuring out what the code given exactly did.

**I found this to be a fun exercise to perform**, because I had never thought about how much work and fine-tuning there was to do in 'making a package npm ready'. This makes me want to write little programs and release them, if I had the time for it haha!

As feedback, I don't have a lot, maybe be a little bit more specific if you need to write code on your own here. I was figuring that out, but I took a decision and did not write a program, except for in the readme.

**Comment by wooorm** [comment]
@Maikxx Awesome! This looks really great :) [Here’s how I did it](https://github.com/wooorm/f-ck), let me know if you see something weird and would like me to elaborate!

What did you think of the other packages used for inspiration? repeat-string, skin-tone, and my own longest-streak? Which did you like better?

> I found this to be a fun exercise to perform, because I had never thought about how much work and fine-tuning there was to do in 'making a package npm ready'. This makes me want to write little programs and release them, if I had the time for it haha!

I’m glad to hear that! And you should! Let me know if you find something interesting and need an SRP 😉

> As feedback, I don't have a lot, maybe be a little bit more specific if you need to write code on your own here. I was figuring that out, but I took a decision and did not write a program, except for in the readme.

Yeah, it’s pretty vague right? This assignment is meant more as a: do something cool, take a look at what exists, and make something awesome! 🎉

**Comment by Maikxx** [comment]
Hahahah, awesome quote on your version:
> Not affiliated with Football Club København.

Well maybe not something that I find weird, just maybe that this package of yours can be used for more appliances than just blurring cuss words (in your README you specifically target cuss words).

> What did you think of the other packages used for inspiration? repeat-string, skin-tone, and my own longest-streak? Which did you like better?
I'm not big on emoji's haha, so I think I like your longest-streak the most. I can see some great uses for that one. I think for most people this is overwhelming enough as it is, and these packages are all at about the same level, which is great! 

> I’m glad to hear that! And you should! Let me know if you find something interesting and need an SRP 😉
Yes, I will do that!
