### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by maanlamp** [cmda-be/course-17-18#371]
![screenshotje](https://i.imgur.com/LquV93S.png)
My computer lives a couple minutes further in the future than learnyounode... It correctly serves all the json based on the url, but the values are wrong somehow. 🤷‍♂️ oh well.

Most of the assignment was pretty easy because I have (some) experience. I'm also very skilled in the art of reading the manual -- that helped a lot.

It was interesting to learn about http servers, hadn't done that before.

I did run into some problems when I used functions that are in a more recent spec of JS than Node supports, so I had to polyfill those. No biggie 👌 

[I added most of the assignment files in a repo](https://github.com/maanlamp/learnyounode), I had overwritten the files I made before those.

**Comment by wooorm** [comment]
@maanlamp OMG awesome! Super well done! Have you looked at the [other workshoppers](https://nodeschool.io/#workshopper-list)? And maybe check out going to [NodeSchool Amsterdam](https://nodeschool.io/amsterdam/) — it’s fun to meet other Node devs to be there (but disclaimer: I help out there as well).

>  I'm also very skilled in the art of reading the manual

Haha, well that’s very important for learnyounode! 📚🤓

> It was interesting to learn about http servers, hadn't done that before.

Cool, we’ll focus on that some more the coming weeks!

> I did run into some problems when I used functions that are in a more recent spec of JS than Node supports, so I had to polyfill those. No biggie 👌

Ohh yeah? What things were you using? Maybe you’d like [this table](https://kangax.github.io/compat-table/es6/).

> I added most of the assignment files in a repo, I had overwritten the files I made before those.

AWESOME! 🎉
