### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#372]
# Learn you Node

I still working on exercise 6 almost done argv[2] seems to be the problem ..🐱‍👓

![image](https://user-images.githubusercontent.com/4256430/36357260-de96f996-14fb-11e8-842e-1690da4b1b75.png)

### The error
![image](https://user-images.githubusercontent.com/4256430/36357275-01fda9fc-14fc-11e8-929d-70f33e0c7f7e.png)

**Comment by wooorm** [comment]
@Marijnone And, did you ask Slack if someone knows what’s up with that error? 😉

**Comment by wooorm** [comment]
Pingggg!
