### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by AnneleenK** [cmda-be/course-17-18#373]
Handige opdracht om aantekeningen bij te maken, maar bij de MarkUp opdracht en de andere git opdracht in de terminal was ik meer met de stof bezig omdat het dan niet zo precies wordt voor gezegd.

**Comment by wooorm** [comment]
Thanks @AnneleenK! I think the octocat assignment is more useful, but I hope this provided a bit of a base.

Anyway, unfortunately the deadline for this assignment was on Thursday, so great that you’re still working on this, but it doesn’t count towards your final grade!
