### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Asprengers** [cmda-be/course-17-18#374]
![schermafbeelding 2018-02-15 om 12 20 52](https://user-images.githubusercontent.com/34510981/36369347-39759692-155b-11e8-95f1-a76e9f2eaf00.png)

very difficult, no idea what I was doing but I guess it's finished now.

**Comment by wooorm** [comment]
Very very very difficult! 😬 I think what you did will become clearer in the coming weeks!
