### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by sarahverkade** [cmda-be/course-17-18#380]
# Markdown Tutorial 

### Ordered lists
1. **Bold text**
2. **_Bold and Italic_**
3. _Italic text_
4. Nesting links with two spaces 

#### Unordered lists 
* [Inline link](https://www.google.com) 
* Reference link [the text for the link][www.google.com]
* ![Inline image links](https://pixabay.com/en/british-shorthair-cat-pet-mieze-3113513/) 
* ![Reference image][https://www.image.ie/]

##### Blockquotes 
> "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut 
aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.”

###### Paragraphs
Hard breaks: Insert a new line 
Soft breaks: add two spaces after each sentence

**Comment by wooorm** [comment]
Thanks @sarahverkade! Welcome aboard! 🚢

Unfortunately late, as you maybe already know (see each assignment for [deadlines](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#markup)), so this won‘t count towards your [final grade](https://github.com/cmda-be/course-17-18#grade).

Anyway, well done! 💪
