### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by valentijnkap** [cmda-be/course-17-18#382]
It was a good exercise but it was really really hard for me. I made a repo for all my solutions for the challenges in the course. You can find it [here](https://github.com/valentijnkap/learnyounode).

(Ofcourse there's a readme and a screenshot of the last step)

**Comment by wooorm** [comment]
Awesome work Valentijn! Super well done!
I know it’s very hard 😬 but I’m glad you pushed through!
