### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by AnneleenK** [cmda-be/course-17-18#383]
1. https://services.github.com/on-demand/intro-to-github/you-completed-github-flow

2. https://anneleenk.github.io/AnneleenKramer/

**Comment by rijkvanzanten** [comment]
Hey @AnneleenK! Could you please share the link to the closed PR?

> If you completed the exercises, mark this assignment as complete by opening an issue on our GitHub issue tracker. Include two links in your issue: **one to the closed PR from the Introduction to GitHub exercise**, the other to the GitHub Pages website from GitHub Pages from the Command Line exercise. Let us know in the issue what you thought of the exercises.
