### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by nguyent047** [cmda-be/course-17-18#384]
Steps 9 and 12 in particular we're very challenging and took me a lot of time. Mainly because the exercises were difficult by nature but also because I did not realize I was missing the though2-map installation. The exercise in general was a bit too hard for me to complete and as a result it took me a bit too long. But liked the challenge it provided.

<img width="487" alt="schermafbeelding 2018-02-19 om 18 28 07" src="https://user-images.githubusercontent.com/32309314/36390263-c658f4d6-15a2-11e8-881a-fe0bbf0e5ff1.png">

**Comment by rijkvanzanten** [comment]
Awesome! 🎉
