### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Karinliu** [cmda-be/course-17-18#385]
The first few steps were doable. But later the exercises became harder which means i had to search many thing up on the internet. Read and write the commands separately it makes sense, but to put all the code together makes it difficult.

<img width="583" alt="screenshot 2018-02-18 23 09 18" src="https://user-images.githubusercontent.com/32538678/36390392-361b7aa0-15a3-11e8-8b2b-967194d0fe07.png">

**Comment by rijkvanzanten** [comment]
Awesome 😄
