### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Denniswegereef** [cmda-be/course-17-18#390]
I spend some hours trying to get some things right, but must admit that I've looked up the answers of lesson 5 and 9. I still fully don't understand what the callback does in lesson 5 and have to maby dive some deeper into that. And about lesson 9 that was a tough one for me to understand. But I'm happy that I've come along wait without knowing that much about node. Gonna continue upcoming week but also wanna give a try to the package assignment today.  

I used the followed tutorial [Node JS Tutorial for beginners](https://www.youtube.com/playlist?list=PL4cUxeGkcC9gcy9lrvMJ75z9maRw4byYp) and I'm now on #19 
Also used this companion to help me get started on the lessons [joecreager learnyounode unofficial companion]( http://joecreager.com/learnyounode-unofficial-companion/)

_The progress I've made:_
<img width="564" alt="screen shot 2018-02-19 at 20 15 24" src="https://user-images.githubusercontent.com/12157616/36393851-ac28299c-15b1-11e8-9372-b14bf877c41d.png">

**Comment by rijkvanzanten** [comment]
Hey @Denniswegereef! Are you having troubles with understanding callbacks in general, or just the one in the assignment? What was the solution you came up with? 🙂

**Comment by Denniswegereef** [comment]
The `callback(null, list);` in the exercise. I understand callbacks in general and how to use them!

**Comment by rijkvanzanten** [comment]
Ahhh! That’s the callback you fire when the reading of files is successful. The first parameter is the error. Since there’s no error (it’s successful) you pass `null` :)
