### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by Mimaaa** [cmda-be/course-17-18#391]
Excellent assigment which gave me a better understanding of constructing proper repo's with their respective documents and information.

[Repoooooo](https://github.com/Mimaaa/backend-package-assigment).

<img src="https://s14-eu5.ixquick.com/cgi-bin/serveimage?url=https:%2F%2Fi.ytimg.com%2Fvi%2FPGDvjG49kLc%2Fmaxresdefault.jpg&sp=cba07ea43442b41ccfc31591f5670ee6" width="450">

Feedback is appreciated.

**Comment by rijkvanzanten** [comment]
Hey @Mimaaa!

Checkout the issues on your repo 😉

**Comment by wooorm** [comment]
Nice work! Some points:

* You don‘t really need `trim_trailing_whitespace = false` for markdown anymore in [editorconfig](https://github.com/Mimaaa/backend-package-assigment/blob/9e3549e91474dfb87eda5a3ad12a77ef778ff44c/.editorconfig#L11), with CommonMark, that GitHub now supports, you can “escape” newlines with a slash and don’t need two spaces anymore, [like the poem here](https://raw.githubusercontent.com/cmda-be/course-17-18/master/week-3.md)
* For the license, maybe add an email address in future licenses?
* Use code blocks for the install section, with a `sh` language flag for syntax highlighting
* In package.json, you can use the short form of users: `"author": "Mirza van Meerwijk <hello@mirza.lol> (www.mirza.lol)"`
* Is [engines](https://github.com/Mimaaa/backend-package-assigment/blob/9e3549e91474dfb87eda5a3ad12a77ef778ff44c/package.json#L14) needed? I’m pretty sure my code runs everywhere

Anyway, [this is](https://github.com/wooorm/f-ck) how I did it!

**Comment by Mimaaa** [comment]
Thanks for the feedback @wooorm. I made the neccessary changes.

>You don‘t really need trim_trailing_whitespace = false for markdown anymore in editorconfig, with CommonMark, that GitHub now supports, you can “escape” newlines with a slash and don’t need two spaces anymore, like the poem here

Awesome, didn't know that! 

>For the license, maybe add an email address in future licenses?

Fixed. I added the license through GitHub; probably why it was not included.

>In package.json, you can use the short form of users: "author": "Mirza van Meerwijk <hello@mirza.lol> (www.mirza.lol)"

Much better.

>Is engines needed? I’m pretty sure my code runs everywhere

Makes sense.
