### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by JimvandeVen** [cmda-be/course-17-18#392]
![image](https://user-images.githubusercontent.com/34744290/36395032-4306b8a6-15b7-11e8-86cc-8ce3877046c9.png)
I finnished exercise 9. I'm going to eat something right now and will try to finnish it tonight..
Most exercises were quit tough, often i needed a little kickstarter to get going, the hints section in learnyounode is often a bit lacking. Also the lack of feedback you get in the terminal you are working in makes it hard to try out your (unfinnished) code. The arguments that learnyounode puts in your program are not always clear.

**Comment by rijkvanzanten** [comment]
Good job! Valid points on the arguments for the input.. That messed my efforts up too!
