### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by lauraesmee** [cmda-be/course-17-18#393]
Better late than never :wink:

[Link to repository](https://github.com/lauraesmee/lauraesmee-dotfiles/blob/master/README.md)

It wasn't that hard, but is costs some time that I didn't have at that moment. I have not created many aliases, because I do not know what I'm gonna use a lot in the terminal.

![screenshot terminal](http://i68.tinypic.com/2gwb6tt.png)

**Comment by rijkvanzanten** [comment]
Hey @lauraesmee! Nice submission. I like the simple prompt 🙂 

Some inspiration for shortcuts:

```
..  = cd ..
... = cd ../..

gst = git status
ga  = git add
gc  = git commit
```
