### ISSUE TITLE
Markup assignment

### ISSUE THREAD

**Issue by nataschazw** [cmda-be/course-17-18#394]
#hi

1. How do you comfort a JavaScript bug? 
You **console** it. 

2. ["hip","hop"]. _hip hop_ **array**.

3. I was having a hard time understanding source control. _but_ i’m starting to **git** it

4. Why was the JavaScript developer sad? Because he didn’t **Node** how to _Express_ himself

![oops](http://i0.kym-cdn.com/photos/images/original/001/323/099/af7.png)

>always late but worth the wait.

**Comment by rijkvanzanten** [comment]
Hey @nataschazw!

Make sure to remember to put a space between the `#` and the actual title 🙂

**Comment by rijkvanzanten** [comment]
Hi @nataschazw! Is it correct that you didn’t finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for the first week week? Especially note this part of the Slack prereq:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.
