### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by admirai** [cmda-be/course-17-18#396]
<img width="617" alt="schermafbeelding 2018-02-19 om 21 34 01" src="https://user-images.githubusercontent.com/36187811/36396171-fb1867aa-15bc-11e8-98ce-293ba66576dd.png">

**Opinion**:
At first I didn't know where to start, because the exercises after the hello world where a bit confusing to me. So after I did the exercise hello world I was a bit demotivated. So I started watching beginner tutorials to understand node.js better.

I watched these video's: 
1. [Node.js Tutorial For Absolute Beginners (24:45) ](https://www.youtube.com/watch?v=U8XF6AFGqlc)
2. [What is Node.js Exactly?  a beginners introduction to Nodejs (13:04)](https://www.youtube.com/watch?v=pU9Q6oiQNd0
)
3. [Node.js Tutorial for Beginners Handling Multiple Requests (14:30)]( https://www.youtube.com/watch?v=KsjrN-T3ZCs)

I also used multiple sites helping me with the assignments:
1. [Node.js - Callbacks Concept](https://www.tutorialspoint.com/nodejs/nodejs_callbacks_concept.htm)
2. [Callback Hell - A guide to writing asynchronous JavaScript programs]( http://callbackhell.com/)
3. [The Art of Node - An introduction to Node.js]( https://github.com/maxogden/art-of-node/blob/master/readme.md#the-art-of-node)
   _etc._

After these tutorials I understood more about node.js and the use of it.

So I started reading the exercises again and writing them down for myself. I discovered that the text that came with the exercises actually gave away a lot of information about what I had to do. As a result, I finally managed to complete the exercises 1, 2, 3, 4 and 5. And I'm actually pretty happy that I figured it out.

**Comment by rijkvanzanten** [comment]
Good job! The assignments are pretty difficult, glad you managed to finish so many of them 🙂
