### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by lauraesmee** [cmda-be/course-17-18#397]
![Screenshot_learnyounode](http://i64.tinypic.com/28anypd.png)

This was hard to understand for me. Mostly of the time I didn't know what to do, because I didn't understand the question. I have made 9 of the 13 assignments. The assignment 'time server' didn't want to succeed. Mostly of the assignments I made with [a tutorial on youtube](https://www.youtube.com/playlist?list=PLlidO7ztn-FENOH8yvg260frkkbb_j-PJ)

I'm gonna stop with learnyounode, because I can't make it succes and I want to check out the packages assignment.

**Comment by rijkvanzanten** [comment]
Did you understand the solutions you used in the workshopper, or was it mostly following along and copying over the examples in the YouTube tutorial?

**Comment by lauraesmee** [comment]
Most of the time I did not understand the solutions. I tried, but my understanding of Javascript is very, very, very low.

**Comment by wooorm** [comment]
Well done Laura! 💪

**Comment by wooorm** [comment]
(even if it’s still hard, you’ll get there)
