### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by nataschazw** [cmda-be/course-17-18#398]
bmF0YXNjaGF6dwo=

**Comment by rijkvanzanten** [comment]
Good job 🙂 Unfortunately, you missed [the deadline](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#synopsis-3)..

**Comment by rijkvanzanten** [comment]
Hi @nataschazw ! Is it correct that you didn’t finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for the first week week? Especially note this part of the Slack prereq:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.
