### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by Denniswegereef** [cmda-be/course-17-18#399]
[Repository](https://github.com/Denniswegereef/package)

I've included all the links that I used the most in the repository at the bottom. I needed some time to know what the assignment was asking from me. But I think I nailed it 'almost' what I was asked to do. Only the code linting XO, I know how it works but didn't find a good case to use it now (there is a script what can lint the index.js for faults right now in the package).

In the end I really liked the exercise and by far I liked my unit tests the most, kinda proud on them since I never wrote one before (I didn't even knew this kind existed) but it was pretty easy and I see why it can help you make something to prevent faults later down the way. 

_Jest test screenshot_
<img width="555" alt="screen shot 2018-02-19 at 22 28 02" src="https://user-images.githubusercontent.com/12157616/36397981-2ff6bb40-15c5-11e8-9cc7-690482d479da.png">

**Comment by rijkvanzanten** [comment]
Awesome work! On linting, it can really help you out to prevent some of the more "common" errors like a `}` too much or other syntax errors. If you're working in a team, it's really helpful to keep the whole team work in the same codestyle. It can actually be very messy if multiple people work on the same piece of code and all use their own personal style 🙂

I've left some issues on your repo with feedback on how to improve your package 👍

**Comment by rijkvanzanten** [comment]
Good job on the unit testing btw 😄

**Comment by wooorm** [comment]
Nice work! Some points:

* Maybe add `.DS_Store` to `.gitignore`
* Add an email to your license file
* `LISENCE` -> `LICENSE`
* In `package.json`, you can drop the `"main": "index.js"` (it’s the default)
* In `package.json`, you can use the shorthand for users `"author": "Dennis Wegereef <denniswegereef@gmail.com> (www.denniswegereef.nl)"`
* In `package.json`, you can use the shorthand for repositories if linking to GitHub: `"repository": "Denniswegereef/package"`
* In `package.json`, For the npm script `"xo-index": "xo index.js"`, I’d suggest `"lint": "xo"` instead. That way, if you start linting with something else, you’d still have the same script name; plus, now xo checks all files, even if you add more
* In `package.json`, I suggest sorting the keys to something that makes sense for you. I do the following: provide the core metadata first, then files, then dependencies and dev dependencies, then scripts, and then other config (such as `"xo"`)

Anyway, [this is](https://github.com/wooorm/f-ck) how I did it!

**Comment by Denniswegereef** [comment]
@wooorm Thanks for your tips, I will try to update it later this week!
