### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by Razpudding** [cmda-be/course-17-18#4]
I've finished this assignment! Nice that you can deeplink to include the title of an issue :)
I also started with the octocat one and read the 'Understanding Github Flow article'
Excellent article. Are they going to use pull requests though? Don't remember if they're covered in the tutorial. If they're not, it might be good for them to see an example.

Ah now I see that PRs are covered in this assignment :) So that's solved.

The GH pages tutorial is excellent! It even covers Vim ✚
I do think it's crucial they take the time to get through this tutorial. Id give em an hour to do so. At one point, they have to make their first PR. There are a lot of 'firsts' in this tut.

As there are a lot of things that can go wrong in this exercise, I think it's perfect for showing the value of asking questions in the course slack channel. For instance,  even if they don't make ANY typos, they might still forget to accept the invitation from the teacherbot on the collaborative GH repo which results in access being denied 5 steps late rin the tutorial when you try to push.
Also my submission was rejected by travis because my yaml file didn't have a newline at the end of the file. I just copy pasted from the tutorial as requested so I'm guessing lots of people will have this problem and since they dont know how to use/read travis yet they prob wont be able to find and fix this problem on their own.

I think it took me about 30 minutes to do the github pages part alone and I skipped through 60% because I already have a GH pages.

**Comment by Razpudding** [comment]
Ah most of this review was actually about Octocat.
One change I would make is to have students link to their closed PR in the issue they subit for our assignment! That way we can see who actually made it to the end.
[Like so](https://github.com/githubschool/on-demand-github-pages/pull/2054)

**Comment by wooorm** [comment]
Sweet, thanks! 👍 And done! https://github.com/cmda-be/course-17-18/commit/b112e443bb1738e41caa75320956a4c5868d14fb
