### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by sterrevangeest** [cmda-be/course-17-18#400]
Whoa, this was a tough one :nerd_face:

Learned from Laurens that it can be useful to write code step by step (and try to understand everything before you move on). I tried to do this as well when solving the exercises. It helped. 

Also, spend my whole saturday watching tutorials and reading articles about Node. This took a lot of time but was helpful! I finished learnyounode only until step 5 (filtered ls). Not so far, but I think I understand the basics of Node better now because of the tutorials etc.

**Comment by rijkvanzanten** [comment]
Thinking in little steps might be the hardest thing about programming! This is a good article that explains why it's a good thing to always work in little steps: https://zellwk.com/blog/think/

Good job on the workshopper!
