### ISSUE TITLE
package assignment

### ISSUE THREAD

**Issue by Murderlon** [cmda-be/course-17-18#401]
https://github.com/Murderlon/deprofanitise

**Comment by rijkvanzanten** [comment]
Perfect 🎉

**Comment by wooorm** [comment]
Awesome work 🧙‍♂️!

To make a package “runnable” from bash anywhere, you can use use the [`bin` property in `package.json`](https://docs.npmjs.com/files/package.json#bin). [Here’s an example](https://github.com/wooorm/osx-learn/blob/master/package.json).
Then, you can use [npx](https://github.com/zkat/npx) (included in more recent versions of npm) to install and run your package from GitHub: `npx Murderlon/deprofanitise`.

You could also investigate how to write man pages by hand ([i do that](https://github.com/wooorm/osx-learn/blob/master/man/learn.1)), or how to generate them from markdown (hint hint, [remark](https://github.com/remarkjs/remark-man)).
