### ISSUE TITLE
Package assigment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#403]
# package assignment
[make the web friendly!](https://github.com/timruiterkamp/make-friendly)

## Feedback
Good practice to get used to working with npm packages and setting up one yourself. I did quite some time spending on figuring out how to get the index.js working due to requiring the package inside the package instead of outside the package.. Also the mocha testing package took some time to figure out how to make it work, but i finally managed to make it work 👍 .

Overall good assignment and i recommend others doing the assignment as it teaches you a lot about packages and integrating them into your own project.

**Comment by rijkvanzanten** [comment]
Good job! 

The only little nit-picky thing is in the readme. You state in the installation instructions to install the package by running `npm install make-friendly `**`--save-dev`**. However, if you use this package in a real-life app, you probably want it to install to `dependencies` instead of `devDependencies`.

Awesome that you've added unit testing!

**Comment by timruiterkamp** [comment]
Thank you, i have edited the readme!

**Comment by wooorm** [comment]
Super nice work! Here’s some points that you may or may not be interested in:

* Don’t add `mocha` to envs in `package.json`, now the other code, that doesn’t run in mocha, can accidentally also have mocha stuff in it, and xo can’t figure out that you’re using unknown variables. I’d suggest using [configuration comments](https://eslint.org/docs/user-guide/configuring) in the code instead!
* `repeat-string` should be a normal dependency, not a dev-dependency!
* Use `"repository": "timruiterkamp/make-friendly"` in `package.json`, much simpler 👍 (only works for github repo’s)
* Use `"bugs": "https://github.com/timruiterkamp/make-friendly/issues"`, also simpler!
* Use a code block for the installation guide with a `sh` flag to enable syntax highlighting
* Why are you combining cases in filenames? `index.js`, `License.txt`, `README.md`? I’d say lowercase everything, with the possible exception of uppercasing everything without an extension
* Does `License.txt` need an extension?
* Add an email to your license
* Add `.DS_Store` to your gitignore
* You don‘t really need `trim_trailing_whitespace = false` for markdown anymore in editorconfig, with CommonMark, that GitHub now supports, you can “escape” newlines with a slash and don’t need two spaces anymore, [like the poem here](https://raw.githubusercontent.com/cmda-be/course-17-18/master/week-3.md)
* Why not `trim_trailing_whitespace` everything in `editorconfig`?
* Why not use 2 spaces for everything? Then you don’t need the exception for js either!
* What’s up with indenting everything except for requires, in tests?

Anyway, [this is](https://github.com/wooorm/f-ck) how I did it!
