### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by deannabosschert** [cmda-be/course-17-18#404]
I've got no idea how to prove it, but I've definitely put >6 hours into this assignment

**Comment by deannabosschert** [comment]
will try again this week.. if my node version is on my side then, that is.

**Comment by wooorm** [comment]
@deannabosschert Soo, how far are you? And what did you do?

**Comment by deannabosschert** [comment]
right now I'm at 3 (I/O), will fix it tomorrow with another student and then finish the assignment asap. Will start with the w3 lab assignments right now so I won't stay too much behind.

**Comment by deannabosschert** [comment]
okay that'll probably not work either (as the first step doesn't work aswell..), can I just delete the whole (c/programfiles/nodejs)  nodejs  directory via the regular file explorer?   and install it again in the terminal (inside bash)?

**Comment by rijkvanzanten** [comment]
@deannabosschert Try installing Node using [`nvm`](https://github.com/creationix/nvm). AFAIK, it sets the alias `node` to whatever version you've installed using `nvm` without you having to delete the system one 🙂

**Comment by wooorm** [comment]
@rijkvanzanten Yeah apparently that doesn’t work in some combination of windows, subshell, cmder, .bashrc’s and .bash_profile’s! 😬

**Comment by wooorm** [comment]
💪
