### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by iSirThijs** [cmda-be/course-17-18#405]
<img width="348" alt="schermafbeelding 2018-02-19 om 23 55 26" src="https://user-images.githubusercontent.com/23125314/36400298-636ba50c-15d0-11e8-9802-3af1a2c6f6bc.png">

Only made it to http file server, but I understand the node principles of callbacks, buffers and streams. 

Most problems I have come from not understanding everything JavaScript can do. But I definitely learning it now by just doing it.

Did google soms stuff, but not the answers, only small bits of the javascript code I didn't know (like how to set a date etc.) 

I will finish the other assignments later. But now I just wanna sleep 😴😴😴😴😴😴

**Comment by rijkvanzanten** [comment]
Good night! 🌝
