### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by lauraesmee** [cmda-be/course-17-18#406]
[Repository](https://github.com/lauraesmee/lauraesmee-package/tree/master)

Have no clue what I did, but at least I tried, because I didn't really understood what the assignment was about. :sweat_smile:
Fix it later, first gonna ask for some help.

**Comment by rijkvanzanten** [comment]
This actually looks pretty solid already @lauraesmee!

What was the part that confused you?

**Comment by rijkvanzanten** [comment]
The only thing that's lacking of your submission is the finished readme. The rest looks perfect 😄

**Comment by lauraesmee** [comment]
I did not understand what to do with the package. In the readme I had to explain how you could use it, but I really had no idea what to explain.

**Comment by wooorm** [comment]
@lauraesmee Nice work! If you’d like to read further about `package.json`, see [these docs by npm](https://docs.npmjs.com/files/package.json), as for readme’s, maybe this project: [`awesome-readme`](https://github.com/matiassingers/awesome-readme)?

**Comment by wooorm** [comment]
Oh, and you can apply those resources in the listing assignment!
