### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#407]
It was hard to do, it was a bit easier after some research on the net. **The descriptions are impossible to understand!!** I didn't finish the full learnyounode but I'm pretty sure I spent more than 6 hours. I spend 6 hours by the first 5 questions, so I guess it takes 2 times the time I got.

<img width="586" alt="schermafbeelding 2018-02-20 om 00 06 19" src="https://user-images.githubusercontent.com/36073502/36400570-f428c9f2-15d1-11e8-9a1e-20b275c9b320.png">

**Comment by GuusDijkhuis** [comment]
<img width="593" alt="schermafbeelding 2018-02-20 om 00 11 34" src="https://user-images.githubusercontent.com/36073502/36400664-a43ba198-15d2-11e8-945f-f795b524336d.png">

**Comment by rijkvanzanten** [comment]
Good job 😄 

> The descriptions are impossible to understand!!

The `learnyounode` workshopper is an open source project too, so if you feel like being awesome for the rest of the world, you could try making the descriptions a bit more human readable 🙂
