### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Techdemo** [cmda-be/course-17-18#408]
![schermafbeelding 2018-02-19 om 23 53 14](https://user-images.githubusercontent.com/25225099/36400259-1e41f71a-15d0-11e8-8de0-320973d8d518.png)

# Learnyounode assignment

In my opinion; this assignment was very hard. At first I didn't know where to start after step 1. So I searched for Node.js tutorials. That didn't help very much because it made things only more confusing for me. After a couple of hours I searched for solutions for the assignment on Github. I found this: 
[learnyounode solutions by Mupkoo](https://github.com/mupkoo/learnyounode-solutions)

Reading the solutions helped me in the right direction. I didn't copy/paste the solutions to my own terminal, but I tried to understand how Mupkoo got to these solutions and how I can come up with another solution for the problem. It isn't the best way to learn node.js but it's better than doing nothing. I really learned from reading and trying to understand his solutions.

After 6+ hours of struggling through the assignments I found this tutorial playlist on youtube 
[Learnyounode solutions by Vanilla Folder](https://www.youtube.com/playlist?list=PLlidO7ztn-FENOH8yvg260frkkbb_j-PJ).
Vanilla Folder live codes the solutions to the assignment. It was even better to hear her think aloud the code. It helped me to better understand what was going on. 

## what did I learn 
I've learned that I really really need to up my Javascript game. I hope to accomplish this by doing more tutorials and small assignments. From there I can better understand the workings of Node js. 
The second thing I've learned is that I need to thoroughly read the texts, provided with the assignments. Some of the solutions where literally in the Hints section of the assignments. Lastly, I familiarized myself with some of the basis syntax of node.js; I finally understand Callbacks and Stream.  

## other resources I've used
1. [The net ninja tutorials on node.js](https://www.thenetninja.co.uk/courses/node-js-tutorial-for-beginners)
2. [The net ninja tutorials on Async javascript](https://www.thenetninja.co.uk/courses/asynchronous-javascript-tutorial)
3. [nodejs.org](https://nodejs.org/en/)
4. [brunops solutions to learnyounode](https://github.com/brunops/nodeschool-solutions/tree/master/learnyounode)

I haven't finished the assignment but I tried my best.

**Comment by rijkvanzanten** [comment]
Good job 😄
