### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Mimaaa** [cmda-be/course-17-18#409]
This was a pretty tough workshopper to get through. There weren't a lot of exercises which I was able to complete by not doing extensive research, checking issues and sometimes even solutions. I also needed to read the provided information over and over to understand what it exactly is they're asking from me - it was vague at times.

<img width="450" alt="screen shot 2018-02-20 at 00 14 14" src="https://user-images.githubusercontent.com/12242967/36400723-ba9b3780-15ca-11e8-9aa5-5aa8aaf8cdb7.png">

When I started this workshopper last week I forgot to make a repo, so I basically don't have most solution saved which I completed throughout the week. To get a better understanding I will re-do the workshopper and make a repo next time, like I did for the javascripting and scope, scope chains and closures workshoppers.

**Comment by rijkvanzanten** [comment]
Awesome bro! The assignments are very strict in what they want as in-/output, but then again, so are computers in general so I think that's a good thing  ^^
