### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by SadisticSun** [cmda-be/course-17-18#410]
Link to repo: https://github.com/SadisticSun/censor-js

**Comment by rijkvanzanten** [comment]
Good job 🙂 

Btw, `--save` doesn't exist anymore. It has been replaced with `--save-prod`, which is also the default now [ref](https://docs.npmjs.com/cli/install) 😄

**Comment by wooorm** [comment]
Hey! I use save! (I have `save=false` in my `~/.npmrc`) I know what I’m doing npm!

**Comment by wooorm** [comment]
Nice work! Here’s some tips:

* Add an email to license
* You could link from the list of functions to their API docs
* The vowel docs contain variables, but the other docs contain strings
* Add an email (and URL) to the author field in `package.json`
* Maybe investigate tests, linting, and npm scripts in the future!

**Comment by wooorm** [comment]
Oh and [here’s](https://github.com/wooorm/f-ck) how I did it.

**Comment by rijkvanzanten** [comment]
@wooorm `--save` is still working? It has been removed from the docs: https://docs.npmjs.com/cli/install

**Comment by wooorm** [comment]
working for me! I guess they “removed it” by removing it from the docs.
