### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by labraksam** [cmda-be/course-17-18#411]
So for me this was one heavy course. 
The hardest part for me were the explanations of the questions itself. 
This caused me the most trouble and took me the most of the time!
Also the base of code writing like this is still a little bit hard to understand sometimes.. i mean sometimes i dont know where you can get the code from you have to use.. 

Im gonna try to finish the course because in my head I now have the idea that I do not quite understand what the intention is, and ive no idea what is asked later in the course.
I like to know how it works so I will on this week! :) 

Finally i came to step six, with help from the internet, tutorials on youtube and some help from classmates.

Below is a screenshot of how far i've come;
![screenshot](https://user-images.githubusercontent.com/35467938/36401213-3788ae20-15d6-11e8-8dad-9ad4c2721aa9.png)

I used the following tutorials: 
- [Vanilla Folder Tutorial playlist](https://www.youtube.com/watch?v=TXzYoP7C5zE&list=PLlidO7ztn-FENOH8yvg260frkkbb_j-PJ&index=1)
- [The Net Ninja tutorial playlist](https://www.youtube.com/watch?v=w-7RQ46RgxU)

**Comment by rijkvanzanten** [comment]
Could you maybe try finishing the 6th assignment `MAKE IT MODULAR`? That one is particularly useful for Node in general 😄 It should also help you out with making the `package` assignment 👍

**Comment by wooorm** [comment]
Well done Sam! 💪
