### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#412]
#Learn You Node
![image](https://user-images.githubusercontent.com/4256430/36401813-53200184-15da-11e8-908a-75f7917559ef.png)

The last exercise and the Async juggling where very hard, but with some Googeling and the help of classmates, manage to finish on time. 🧙‍♂️

>headache
>a continuous pain in the head.

**Comment by rijkvanzanten** [comment]
`[COMPLETED]` 🎉
