### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by nataschazw** [cmda-be/course-17-18#413]
Loving the Octocat. Really helpful tutorial for beginners but its too bad the answer is always visible, i would like something like the 'Run tutorial'. Thats more of a challenge and for me thats a better way to learn because you are writing the commands yourself. But still a very great tutorial. Thanks!

**Comment by rijkvanzanten** [comment]
Hi @nataschazw ! Is it correct that you didn’t finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for the first week week? Especially note this part of the Slack prereq:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.

**Comment by nataschazw** [comment]
@rijkvanzanten Thats correct. Thanks for the reminder, i sent my lecturer a direct message!

**Comment by wooorm** [comment]
Awesome @nataschazw!
