### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by jessiegouw** [cmda-be/course-17-18#414]
## My process
I really need and want to improve writing javascript from 0 to something that actually works, I could've just copy pasted all other answers but I would't learn from that. I'll dive even deeper into node so I can explain every single line of code.

Estimated hours spent on this assignment: +/- 6 hours at least and I finished till MY FIRST ASYNC I/O.

### Sources
* [learnyounode Unofficial Companion](http://joecreager.com/learnyounode-unofficial-companion/)
* [MY FIRST I/O! - learnyounode](https://www.youtube.com/watch?v=bEnVS241wWI)
* [workshopper/learnyounode/excersises](https://github.com/workshopper/learnyounode/tree/master/exercises)
* [Asynschronous tasks and callbacks](https://www.lynda.com/Node-js-tutorials/Asynchronous-tasks-callbacks/612195/677542-4.html?srchtrk=index%3a1%0alinktypeid%3a2%0aq%3anodejs+I%2fO%0apage%3a1%0as%3arelevance%0asa%3atrue%0aproducttypeid%3a2)
* [LEARN NODE!](https://learnnode.com/)
* [Pure JavaScript – Building A Real-World Application From Scratch](https://codingthesmartway.com/pure-javascript-building-a-real-world-application-from-scratch/)
* [Node.js Streams: Everything you need to know](https://medium.freecodecamp.org/node-js-streams-everything-you-need-to-know-c9141306be93)

**Comment by rijkvanzanten** [comment]
> MY FIRST ASYNC I/O

w0000t 🎉
