### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by bengtbennink** [cmda-be/course-17-18#415]
<img width="567" alt="schermafbeelding 2018-02-20 om 09 10 20" src="https://user-images.githubusercontent.com/35565689/36413266-ecc4e2d0-161d-11e8-8b28-4a41f2871bc9.png">

Very hard but I will keep pushing it till I get it :).

Sorry I'm a little late with the issue tracker, I worked on it till late and I somehow forgot the issue tracker.

**Comment by wooorm** [comment]
Nice! 💪
