### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by SadisticSun** [cmda-be/course-17-18#416]
Wasn't able to complete it fully due to time constraints.
Had some struggles with Make It Modular as it seemed to produce some weird errors even though everything was green. Fixed it eventually by rebuilding all packages reinstalling others.

Good exercises! Having had quite some experience with Node already, I learned a few new things along the way, especially about the streams.

<img width="829" alt="schermafbeelding 2018-02-20 om 09 51 29" src="https://user-images.githubusercontent.com/20085458/36414788-ca198974-1623-11e8-815f-368e96e00023.png">

**Comment by wooorm** [comment]
> Fixed it eventually by rebuilding all packages reinstalling others.

Super weird!

> Good exercises! Having had quite some experience with Node already, I learned a few new things along the way, especially about the streams.

I’m glad you did!

💪
