### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by nataschazw** [cmda-be/course-17-18#418]
# learnyounooooo

Now, that was a tough one. Stayed up the whole night and only got to the modular. The provided hints were not veeeery helpful and i had to google **A LOT** and got frustrated most of the time.  Last year i got some coaching from a node-genius friend of mine so i remember quite some things but its still hard to figure out. If you can write code on your one, its do-able. The good thing about these kind of exercises is that you never forget because you struggled so hard to find the right answer. so thumbs up for learnyounode. 

<img width="490" alt="schermafbeelding 2018-02-20 om 01 05 38" src="https://user-images.githubusercontent.com/26382333/36417061-310adf5a-162b-11e8-8081-17d7315f2824.png">

The first two are easy. When you're at the third one you have to think a little bit more and i dont now if its me but the instructions were not very clear. I had to read it multiple times but maybe, just maybe that was because i was behind my screen all night. The fourth and fifth sounded a little bit familiar because i worked with the fs module in the back-end course of last year. The node documentations can help you a lot. But i do not complain. Overall it was a good exercise, not everything can be easy. 

i also saw this screen WAY too many times!!

<img width="482" alt="schermafbeelding 2018-02-20 om 00 25 42" src="https://user-images.githubusercontent.com/26382333/36417683-d98ab014-162c-11e8-832b-bc5c8cea7227.png">

> Always late but worth the wait.

**Comment by nataschazw** [comment]
i meant modular instead of markdown. my bad.

**Comment by wooorm** [comment]
> i also saw this screen WAY too many times!!

I know right?!

👍
