### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by KjellRuiter** [cmda-be/course-17-18#419]
<img width="537" alt="schermafbeelding 2018-02-20 om 12 07 25" src="https://user-images.githubusercontent.com/33932353/36420849-a360651a-1636-11e8-8df1-e4b49f043d1b.png">

Ik ben bezig met opdracht 6 😣 Vind het heel lastig om te doen. Ik heb er al meer dan 6 uur in zitten. Ik ben nu stap voor stap alles met een tutorial op youtube aan het maken. (wil dit nog wel afronden maar gaat mij niet lukken voor de aankomende werkgroep.
Link: https://www.youtube.com/watch?v=WrTFHZ8bRBI&index=5&list=PLlidO7ztn-FENOH8yvg260frkkbb_j-PJ 

Verder ben ik The Node Beginner  Book aan het lezen om er beter in te worden en het meer te begrijpen. Link:  http://www.hylianux.com/downloads/nodebeginner.pdf

**Comment by wooorm** [comment]
Nice! And handy book, maybe share it in Slack! 👍
