### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by matsfeber** [cmda-be/course-17-18#421]
Here is my [repo](https://github.com/matsfeber/package).

I added a package.json file but not sure if it is complete, i will look at it later and finish it. Also i found it hard to understand the index.js but luckily @bauke77 could explain it to me.

**Comment by wooorm** [comment]
@matsfeber Could you ask on slack for feedback and questions about the assignment? There, lot’s of people can help you, I’d like to keep issues clean and just for submissions.
