### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#423]
# Transfer assignment
During this transfer assignment i've learned about statusCodes, HTTP header, HTTP methods and how to use curl to retrieve information from an url. 

## Some good practices were:

To retrieve information of a website you can use
```sh 
curl domainname --verbose
```
 To see what kind of options are available on the domain, you can use
```sh 
curl domainname --verbose --request OPTIONS
```

## HTTP methods
* Get (Get data from a specific source) 
* Post (Submit data to a specific source)

### Other HTTP methods
* HEAD ( Only returns the HEAD information )
* PUT ( Upload information to a specific source )
* PATCH ( Update information from a specific source )
* DELETE (Delete specific source)
* OPTIONS (Get options of a specific source)

### Some great HTTP actions:
To get encoded header info, you can use:
```sh
curl domainname  --verbose --request GET --header 'Accept-Encoding: gzip'
```

To delete an authorized source you can give authorization information with the request to gain acces and delete the source.
```sh
curl  domainname  --verbose --request DELETE --header 'Authorization: token 1b23341b9'
```

## HTTP statusCodes with their meaning:
* 200 OK (Response for a succesfull request)
* 201 Created (Request is succesfull and created a new resource)
* 204 No Content (Request is succesfull but it is not returning any content )
* 400 Bad Request (The server cannot fullfill the request)
* 401 Unauthorized (Authentication is required to fullfill the request)
* 404 Not Found (The requested resource can't be find)
* 405 Method Not Allowed ( Used an unsupported method )
* 410 Gone ( Location doesn't exist anymore )
* 422 Unprocessable Entity (Succesfull request but due to semantic errors can't be processed)

I used [List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) and [W3 schools Methods GET vs POST](https://www.w3schools.com/tags/ref_httpmethods.asp) to get better understanding of the subjects.

![Completion transfer assignment](https://user-images.githubusercontent.com/10829926/36439654-e005279e-166d-11e8-8953-e60c23bc0bd7.png)

**Comment by rijkvanzanten** [comment]
Awesome! 🎉
