### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by jessiegouw** [cmda-be/course-17-18#424]
## Evidence I finished
<img width="745" alt="screen shot 2018-02-20 at 14 34 03" src="https://user-images.githubusercontent.com/22095577/36426732-616ac000-164b-11e8-9ac5-36ec4c2e3bb0.png">

## HTTP
_'Hypertext Transfer Protocol'_, I knew this was the definition but it didn't made things clear. Thanks to this assignment, the definition makes sense. 

1. Because what happens at a HTTP request is that the user is requesting certain files `hypertext`
2. To access those certain files it has to comply with the conditions `protocol`
3. When access is granted your request will be fulfilled and as response you can get  **200 ok** `transfer`

### Cheatsheet
> [**`curl`**](https://curl.haxx.se/) is used in command lines or scripts to transfer data. It is also used in cars, television sets, routers, printers, audio equipment, mobile phones, tablets, settop boxes, media players and is the internet transfer backbone for thousands of software applications affecting billions of humans daily
 

* When `verbose` mode is enabled, curl gets more talkative and will explain and show a lot more of its doings. It will add informational tests and prefix them with '*'
* `GET` is used to send data back
* `HEAD` is like GET but tells the server not to send any data back.
* `POST` is used to add a new element to an array
* `PUT` is used to replace an existing element in an array or to add new element
* `DELETE` is used to remove things
* `PATCH` is used to update, e.g. when an user wants to change his e-mail 
* `OPTION` is used to find out which request methods a server supports

**Comment by rijkvanzanten** [comment]
Awesome work 🎉
