### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#425]
# Learnyounode Assignment
## Screenshot 
![Screenshot of terminal showing final assignment of learnyounode](https://oege.ie.hva.nl/~polf002/images/learnyounnode_proof.png)

## Git repo
[Git repo of learnyounode files](https://github.com/FJvdPol/learnyounode)

## Findings
This assignment was really difficult, but after a good few hours I finally managed to finish it. For some reason some of the middle assignments were the hardest for me to figure out, maybe because the hints at the final assignments were more clear to me.
The most difficult assignment for me was the "Juggling Async" assignment (number 9).
It was really hard to figure out how to get the order of served urls to match the order of outputted results.
All in all, a difficult assignment but I learned a lot about node in the end, so i hope it sticks with me.

**Comment by rijkvanzanten** [comment]
Good work! Juggling async code isn't just hard in homework assignments I'm afraid 😨
