### ISSUE TITLE
Learnyounode

### ISSUE THREAD

**Issue by rbntimes** [cmda-be/course-17-18#429]
![screen shot 2018-02-21 at 17 54 20](https://user-images.githubusercontent.com/10119950/36493987-2788161c-1731-11e8-9da0-63686bc22885.png)

Overall a great exercise.

Didn't manage to finish it due to lack of time but really learned a lot from it. The lack of information made me lookup the solution more often then i like to admit but i still managed to learn a lot from just peeking and getting an idea of what the exercise was about. 

I do believe that a little bit more explanation would have helped but still, learned a lot!

**Comment by rijkvanzanten** [comment]
Well done 🎉
