### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Mimaaa** [cmda-be/course-17-18#430]
# Transfer

An interesting assignment which learned me how to use curl to get certain information or send requests. 

## Examples
* Get the content from a website with `curl`
* Get more information from the server with `--verbose`
* Send HTTP methods with `--request`
* Find out which HTTP methods are supported with `--request OPTIONS`

### HTTP requests
* `GET` to receive data
* `HEAD` to only receive the head data
* `POST` to send data to the server. Add the `--data` flag and the data itself (i.e. `'{"Title": "Wonder Man"}'`
* `PUT` will add the data on the specified location if it exists or not
* `POST` will add something to an existing resource
* `PATCH` will give you the option to modify existing data
* `DELETE` to delete data

### Headers
We can also use more flags to do stuff by adding headers to the request. 
* Get the data in a different data-format we use `--header 'Accept: application/xml'`
* Receive compressed data by adding `--header 'Accept-Encoding: gzip'` to the curl request
* Get authorized for using certain methods by adding `--header 'Authorization: <token>'` to the curl request

### Status codes
* 200: OK
>The request has succeeded.
* 201: Created
>The request has been fulfilled and has resulted in one or more new resources being created.
* 204: No content
>The server has successfully fulfilled the request and that there is no additional content to send in the response payload body.
* 400: Bad Request
>The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
* 401: Unauthorized
>The request has not been applied because it lacks valid authentication credentials for the target resource.
* 405: Method not Allowed
>The method received in the request-line is known by the origin server but not supported by the target resource.
* 410: Gone
>The target resource is no longer available at the origin server and that this condition is likely to be permanent.
* 422: Unproccessable Entity
>The server understands the content type of the request entity (hence a 415 Unsupported Media Type status code is inappropriate), and the syntax of the request entity is correct (thus a 400 Bad Request status code is inappropriate) but was unable to process the contained instructions.

Quotes from [HTTP Statuses](https://httpstatuses.com).

<img width="367" alt="screen shot 2018-02-21 at 18 16 24" src="https://user-images.githubusercontent.com/12242967/36494794-11c4383e-172b-11e8-9f8a-159f90f97d05.png">

**Comment by rijkvanzanten** [comment]
Good job 😄
