### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by daoneandonly** [cmda-be/course-17-18#431]
# Package assignment

Here is [my Package Repo](https://github.com/daoneandonly/package).

I've tried to add as many of the things the assignment listed. However I wasn't sure if i needed to test the file itself with the linter and unit tester. Anyhow I've added them to the package.json

I found out that the MIT License was most commonly used on github because of the open source nature of the license. Therefore, I decided to go with this license. 

Some of the files you need needed add like .gitignore and .editorconfig were a bit confusing. There wasn't a lot of files to use .gitignore for so I've looked up some other .gitignores files and used what seemed appropriate. .Editorconfig looked useful but wasn't sure how to use it correctly. I found I needed a plugin for atom to use it, but I didn't get any further than that. 

---

## Resources

[MIT License](https://opensource.org/licenses/MIT)
[concat-stream](https://github.com/maxogden/concat-stream)
[repeat-string](https://github.com/jonschlinkert/repeat-string/blob/master/package.json)
[longest-streak](https://github.com/wooorm/longest-streak/blob/master/package.json)
[skin-tone](https://github.com/sindresorhus/skin-tone/blob/master/package.json)

**Comment by rijkvanzanten** [comment]
Hey @daoneandonly! Your `package.json` file has a bunch of syntax errors and uses a bunch of properties that don't exist in a `package.json` file:

- `test` should be in `scripts`
- `tags` should be `keywords`
- `scripts` isn't properly closed thus putting all following keys inside it
- The `test` line in `scripts` contains an error
- The `devDependencies` don't get closed

Next to these problems, there are a few things you can do to improve the file:

- The `repository` field can be shortened to `daoneandonly/package` (works only for GitHub)
- You have some dependencies / devDependencies installed but not in use (?)

Could you fix the main problems please? 🙂

**Comment by rijkvanzanten** [comment]
Unfortunately, you missed [the deadline](https://github.com/cmda-be/course-17-18/blob/master/week-2.md#synopsis-3) of this assignment..
