### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by jessiemasonx** [cmda-be/course-17-18#432]
This was sooo difficult for me. I needed a lot of help with this and I only done 1 until 5. There were many times where I just stared at the screen reading everything 10x without knowing what to do. I watched tutorials online too and looked up anything I didn't understand to see if I could find an explanation. I really hope all of this will become easier and more understandable for me after i've been working on it for a while. I'm still motivated to do more work and learn more because I do find it very interesting. 
[learnyounode.zip](https://github.com/cmda-be/course-17-18/files/1745451/learnyounode.zip)

What I used:
https://nodejs.org/
https://www.youtube.com/watch?v=PvWHzcebjjQ&t=1835s
https://www.youtube.com/watch?v=TXzYoP7C5zE&list=PLlidO7ztn-FENOH8yvg260frkkbb_j-PJ

**Comment by rijkvanzanten** [comment]
Good job! 🎉
