### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by LindadeHaan** [cmda-be/course-17-18#433]
Ik heb de learnyounode assignment tot en met stap 5 gemaakt. 
Ik vond het moeilijk om de opdrachten te begrijpen en om de goede JavaScript code te schrijven, omdat er in het eerste jaar van de opleiding echt de basis van JavaScript is gegeven. En als je er daarvoor dus niet mee hebt gewerkt is dit best wel lastig om te begrijpen en ook om te begrijpen welke code je nu precies moet gaan schrijven.

Ik heb de opdracht samen met medestudenten gemaakt en ook zelf, ik heb hiervoor bronnen opgezocht om te begrijpen wat bepaalde onderdelen betekende. Ik heb ook filmpjes van learnyounode gekeken, zodat ik kon begrijpen waarom de code nou op die manier geschreven moet worden.

filmpjes met de uitleg:
https://www.youtube.com/watch?v=TXzYoP7C5zE&list=PLlidO7ztn-FENOH8yvg260frkkbb_j-PJ

om modules te begrijpen:
https://nodejs.org/api/

om forEach te begrijpen:
https://docs.microsoft.com/en-us/scripting/javascript/reference/foreach-method-map-javascript

bestand met de stappen:
[program.js.zip](https://github.com/cmda-be/course-17-18/files/1745462/program.js.zip)

**Comment by rijkvanzanten** [comment]
Good job 😄
