### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by maanlamp** [cmda-be/course-17-18#434]
# Done 💪

I didn't have a real tough time getting the hang of everything, I think it worked out o.k.
[Here's my repo](https://github.com/maanlamp/package)

Most of my time was wasted on trying to both read and understand the entirity of [Node's package.json documentation](https://docs.npmjs.com/files/package.json). I don't think I fully understand every single possible entry, but that'll come I presume.

P.S. Sorry for the generic package name 😆

**Comment by rijkvanzanten** [comment]
Well done @maanlamp!

A few little optimizations:

- You can make the `author` field more useful by including your emailaddress / website: `Rijk van Zanten <rijkvanzanten@me.com> (https://rijks.website)`
- The `files` tab can be removed. You already have `index.js` in main and `readme.md` is included by default.

Other than that, looks good 👍
