### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by AnneleenK** [cmda-be/course-17-18#436]
https://github.com/leochilds/learnyounode-walkthrough heeft mij heel erg geholpen bij het maken, alles wordt hier duidelijk uitgelegd. Probeerde dan zelf een start te maken en als ik vast liep (hoe verder ik kwam hoe sneller dat gebeurde) pakte ik zijn uitleg erbij en deed het zo stap voor stap als hij had uitgelegd.
### exercise 1
Was mij gelukt zonder de uitleg, makkelijk
### exercise 2
Eerst zelf code geschreven daarna de uitleg erbij gepakt en begreep deze ook
### exercise 3
Eerst zelf code geschreven daarna de uitleg erbij gepakt en begreep deze ook, maar moest het wel goed doorlezen
### exercise 4 
Vond deze lastig en heb gelijk de extra uitleg erbij gepakt. Uitleg 3 nog een keer gelezen en toen 4 opnieuw en toen was het gelukt.
### exercise 5
Vond deze lastig en heb gelijk de extra uitleg erbij gepakt, regels meerdere keren doorgelezen om het te volgen.
### exercise 6 
Erg lastig en ben hier vast gelopen
<img width="1440" alt="schermafbeelding 2018-02-21 om 22 51 20" src="https://user-images.githubusercontent.com/33215207/36507383-cb2ae3e4-1759-11e8-87c8-e52855a8ea0a.png">

**Comment by rijkvanzanten** [comment]
Well done 🎉
