### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Bauke777** [cmda-be/course-17-18#437]
When coding the last challenge of the Learn You Node tutorial I've been using [momentjs](https://momentjs.com/docs/) to get the time in the right format. This was way easier than using the standard way of time formatting in Node.

What's interesting about this is that it gave me a better understanding of the power of using existing packages. I've once tried Node before but got deterred because I didn't understand Node packages and didn't see what purpose they have.

Now I've worked with Node modules -and especially custom modules-, I've got a better understanding why a developer would consider using Node and it's ability to use packages.

<img width="752" alt="screen shot 2018-02-21 at 23 03 03" src="https://user-images.githubusercontent.com/10672630/36507943-77032630-175b-11e8-9f3e-fb503e6dc21c.png">

<img width="752" alt="screen shot 2018-02-21 at 23 03 03" src="https://blog.kissmetrics.com/wp-content/uploads/2016/03/i-dont-know-what-im-doing.gif">

**Comment by rijkvanzanten** [comment]
Ha! It looks like you now what you're doing pretty well 😉 

One quick tip about `momentjs` though, the package is huuuugee! So careful when using it on the front-end :)
