### ISSUE TITLE
Learnyounode assignment

### ISSUE THREAD

**Issue by superstephan1** [cmda-be/course-17-18#438]
# Learnyounode

like you can see i haven't finished the assignment yet. You could say that it has been a real struggle. I managed to do the first few parts of the assignment by looking up the answers, discuss them in a group and kind of reverse engineering the code to try to understand it.

# By Exercise

## 1
Well, that wasn't very hard.

## 2
From writing console.log to a loop is a big step in my opinion.

## 3 
This is where i needed the googled answers to get the job done.

## 4 
Same as the last one. I kind of understood the result but couldn't really write it on my own based on the assignment. 

## Questions for the workgroup? 

What do you use process.argv for? I understand that it makes an array but it's usage makes me confused. 
How do we learn to read the exercises? this is a big one, because when i'm reading the exercise i really can't figure out what i have to do until i get to see some code what it would have to be like. 

## sources

https://github.com/leochilds/learnyounode-walkthrough
https://github.com/romainwurtz/learnyounode-solutions
file:///Users/Stephan/.nvm/versions/node/v9.5.0/lib/node_modules/learnyounode/node_apidoc/fs.html 
https://github.com/workshopper/learnyounode

<img width="1197" alt="screen shot 2018-02-21 at 23 20 55" src="https://user-images.githubusercontent.com/33251720/36509070-b961bd36-175e-11e8-957a-afd04cc627c7.png">

**Comment by rijkvanzanten** [comment]
> What do you use process.argv for?

It's mostly used when creating command line interface (cli) tools in Node. For example, if you were to recreate `git` you can use `process.argv` to extract the command and flags: `git add -a`. `add` and `-a` would be in `process.argv`

**Comment by rijkvanzanten** [comment]
> How do we learn to read the exercises?

I don't know the answer to this to be honest.. I think it's an experience thing more than anything. Thoughts @wooorm?

**Comment by wooorm** [comment]
Yes, I think it’s experience as well. I think the way their questions are full of jargon. I’m guessing the intended target audience for learnyounode is people who don’t know node, but who do know some other programming language already!
