### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by ninavanbergen** [cmda-be/course-17-18#440]
At first I really didn't know what to do with al the steps. But I got some help and after that it made a little bit more sense. I have done the first 5 steps. I found it very difficult to understand everything and I am still a bit stressed about how I am going to survive this semester.. 
So here is my program.js:
[program.js.zip](https://github.com/cmda-be/course-17-18/files/1746032/program.js.zip)

I did this assignment together with other students, and we used the following links to understand it a bit more:
https://nodejs.org/ 
https://www.youtube.com/watch?v=PvWHzcebjjQ&t=1835s
https://www.youtube.com/watch?v=TXzYoP7C5zE&list=PLlidO7ztn-FENOH8yvg260frkkbb_j-PJ

**Comment by rijkvanzanten** [comment]
Good job 😄 

Hang in there 💪
