### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by chelseadoeleman** [cmda-be/course-17-18#441]
[Link to repository](https://github.com/chelseadoeleman/Package)

Resources used
1. https://docs.npmjs.com/files/package.json
2. https://www.youtube.com/watch?v=k1B9VIUkQmg&t=1s
3. https://github.com/maxogden/concat-stream/blob/master/readme.md
4. https://github.com/jonschlinkert/repeat-string/blob/master/package.json

I spend a lot of time figuring out the exercise. Then I had some trouble with dependencies, because I didn't understand what they were. 
But it was a good exercise and I think I understand node a little bit better now!

**Comment by rijkvanzanten** [comment]
Hey @chelseadoeleman!

Some points / recommendations / questions about the readme:

- The install instructions in the readme don't show how to install your package, but show how to install two other packages.
- Why do you need the `semver` package for your package to work?
- The _Use_ section is missing information on 2 of the 3 functions the package has

About `package.json`:

- The `dependencies` key contains a package that your package doesn't use, and misses a package it _does_ use. Make sure [the dependencies that are being used by your package](https://github.com/chelseadoeleman/Package/blob/master/index.js#L3) are listed in this field.
- The [`keywords`](https://github.com/chelseadoeleman/Package/blob/738f7ea0fefc73af9a48b08482e6f26041ed71ec/package.json#L16-L25) section is a bit messy. 
- You can make the `author` field more useful by adding your email address and website: `Rijk van Zanten <rijkvanzanten@me.com> (https://rijks.website)`
- The `repository` field can be shortened to just `chelseadoeleman/Package` (works only for git)

Could you please fix the `dependencies` and `keywords` field and update the readme? 🙂

**Comment by rijkvanzanten** [comment]
Unfortunately, you missed [the deadline](https://github.com/cmda-be/course-17-18/blob/master/week-2.md#synopsis-3) of this assignment..
