### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by Bauke777** [cmda-be/course-17-18#442]
# nobadwords.js

Link to my repo: [nobadwords](https://github.com/Bauke777/nobadwords)

I've now learned to create my own packages and know how to include them in projects for future use.
 💪

**Comment by rijkvanzanten** [comment]
Good job 😄 

There are a few things in `package.json` that could use some more love:

- **Add node_modules to `.gitignore`**. You don't want to end up with thousands of copied files in your repo!
- The `license` field contains the wrong license (MIT vs ISC)
- The `keywords` field is empty
- The `author` field can be improved by adding your email address and website: `Rijk van Zanten <rijkvanzanten@me.com> (https://rijks.website)`

Oh and the `install` instructions in the readme are false.

**Comment by Bauke777** [comment]
Hmmm great tips, thanks! I didn't think about the possibility to leave out/ignore the node_modules. Will change that 🤗

**Comment by rijkvanzanten** [comment]
When working with bigger projects, you'll soon start to realize that node_modules grows incredibly fast. For example, the `node_modules` folder in a project at my job currently contains 2,105 directories and 13,270 files!
