### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by deannabosschert** [cmda-be/course-17-18#443]
##### Only in the other tab.

# Transfer 

To open: type 'localhost:[poort]' into the browser 

**Curl**: CLA that can send HTTP requests. Has more options opposed to how your web browser has. Is a GET request.

HTTP has a head and body. CURL/browser do not display everything.

'*' Setup before HTTP
'>' Request sent to server
'<' Response sent from server

The request head starts with a request line, e.g:

**GET** / HTTP/1.1    This just asks for whatever's on the page. 
```Buildup: httpMethod-path-protocol-version. ``` 

**OPTIONS**: gets out the date/time, what you're allowed to do and sometimes be followed by data.

**(Quick question , what does 'verbose' stand for? Is it just a commando staying that the following command is widely used?)**

**DELETE**: also use ```curl localhost:1901 - - verbose - - request DELETE.``` You'll get an error between 400 and 500 because you're not allowed to to that as a use right now (method not supported).

**HEAD**: same as GET but without the body. Quite boring.

**POST**: add something to a resource. Adding a movie to the list in this case! You'll get an error 400 (client) by just using 'POST', because you're not adding a movie in JSON format.

I tried:  ```curl localhost:1901 --verbose --request POST --data '{}', ``` still gave a client error 422 because the title was missing.

Title was added ```'{"Title":Wonder Woman}'``` , so the movie couldbe added. Response head automatically contains the place of the new resource.

**PUT**: POST was used to add something to the list, with PUT you put something in exactly the same place (resulting in the current resource being overwritten).

**PATCH**: to update something in your array. Used: ```curl localhost:1901/wonder-woman --verbose --request PATCH --data '{"description":"Diana leaves home to fight a war."}'  ```

Then we tried to delete ```/wonder-woman.``` Code 410 will be returned, which means that there is nothing there now, but there used to be.

ATM the API only returns JSON data, but you can **alter** that by e.g. sending    ``` curl localhost:1901/ --verbose --request GET --header 'Accept: application/xml'  ```   **so it'll accept XML files.**

Then I tried it with another kind; ```curl localhost:1901/ --verbose --request GET --header 'Accept-Encoding: application/gzip'. ```

Last but not least, I tried to **delete** ```localhost:1901/evil-dead. ```I **did not have any permission to do so** yet, but after receiving the **token** I could do so; ```curl localhost:1901/evil-dead --verbose --request DELETE --header 'Accept-Encoding: token 5b8822b29' ```

*Sidenote: the tutorial running twice happened AGAIN, for the 8th time after step 19, but as the feed-forward showed it was the last assignment. I hope it really was because there's a small chance I am happy to test it out myself first and running the tutorial for the 8th time with a big chance I'm doing it for nothing :)))*

**Comment by rijkvanzanten** [comment]
Good job 🙂 

## ver·bose
> vərˈbōs (adjective)

using or expressed in more words than are needed.

In a lot of tools, the default output just gives you what you (likely) need. The `--verbose` option is a flag that adds additional info if there is any 🙂
