### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by chelseadoeleman** [cmda-be/course-17-18#444]
<img width="744" alt="schermafbeelding 2018-02-22 om 00 50 35" src="https://user-images.githubusercontent.com/35819277/36512457-c145f2ae-176a-11e8-8fd5-3473e24ce803.png">

I found the exercises really hard and definitely need to work on my Javascript skills. For me reading and understanding the exercise was particularly an issue and took a lot of time. 
I'm going to keep on practicing the exercises! Because I think they're very helpful!

**Comment by rijkvanzanten** [comment]
Good job! 😄
