### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Dutchsilab** [cmda-be/course-17-18#445]
Sadly, I didn't make it to the end. I tried for over 6+ hours, and couldn't find the solution for the other assignments after browsing the web and watching video's. On the bright side, I learned a lot by doing these exercises. I have long way to go with JavaScript, but in the end I will master it :).

<img width="637" alt="terminal" src="https://user-images.githubusercontent.com/11925347/36512946-3737f424-176d-11e8-9d81-fbea83843c84.png">

**Comment by rijkvanzanten** [comment]
Awesome! 😄
