### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by daoneandonly** [cmda-be/course-17-18#446]
# Learnyounode

Here is [my repo containing all my code for learnyounode](https://github.com/daoneandonly/learnyounode).

I found this course really challenging, but really inspiring at the same time. I've finished all the way up to the [makeitmodular course](https://github.com/daoneandonly/learnyounode/tree/master/makeitmodular), which made my head hurt for a bit. Especially the part where you pass a callback function in the module which gets used later in the original .js file. But I eventually worked it out with a whole lot of console.log-ing!

Eventhough I didn't finish it completely, I still plan on finishing this course in the upcomming days/week. 
I quite like the challenge.

**Comment by rijkvanzanten** [comment]
Good job!

Being able to work in small modules is a very nice skill to have which you'll probably use in front-end development too 😄
