### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Rowin206** [cmda-be/course-17-18#447]
Unfortunately, I didn't finish the exercises. Searching and understanding took the most time. I did not get any further than "My first async IO", after 5 a 6 hours of trying. Not even after an appointment with classmates. 

At the end, I think it was a difficult task. Yesterday I got some advice to check several video's to understand the most of it. So, I will check them soon. 

<img width="603" alt="screen shot 2018-02-22 at 11 11 54" src="https://user-images.githubusercontent.com/33234293/36532536-40e3b7ac-17c1-11e8-989a-8d445841edf0.png">

**Comment by rijkvanzanten** [comment]
I know it's a hard assignment to dive into, but please try to finish them if you have the time! The async and HTTP ones are very useful for the assignments for next week 🙂
