### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Maikxx** [cmda-be/course-17-18#448]
# Note: I always write my summaries in Dutch for me to better understand it, so here it is:

## Methodes
**HEAD** is een methode die lijkt op GET, maar die de server verteld om geen data terug te sturen. Er zit dus geen body bij. Het wordt gebruikt om dingen toe te voegen aan een resource.

**OPTIONS** methode kun je sturen naar een URL om er achter te komen wat mogelijkheden zijn die je hebt om iets te doen met deze URL.

**PUT** is een methode die gebruikt wordt om een resource ergens te plaatsen, het zal iets overschrijven als er op deze locatie al iets bestaat.

**PATCH** is een methode die gebruikt wordt om een bepaald ding te updaten, zonder dat je alle andere properties ook hoeft mee te geven.

## Curl opties
* **--verbose**: Laat je curl request zien op een veel uitgebreidere manier, dan normaal.
* **--data**: Zorgt ervoor dat je data mee kunt sturen als eerstvolgende parameter.
* **--request**: Het type request dat je naar de server stuurt (methode).
* **--header**: Gevolgd door een property in de headers die je wilt sturen naar de URL.

## Headers
* **Location**. Plek waar de nieuwe resource gevonden kan worden.
* **Allow**. Zet hier in methodes die toegestaan zijn op de URL.
* **Accept**. Een header die het formaat van je beoogde response weergeeft. Deze staat in directe relatie met Content-Type.
* **Accept-Encoding**. Een manier om te zeggen wat voor compressor de code door moet, om het zo klein mogelijk te verschepen tussen server en client. Deze staat in directe relatie met Content-Encoding.
* **Authorization**. Deze geef je een token mee, waardoor de server kan bevestigen wie jij bent.

## Statuscodes
* **201** - Created. Een succes code die laat weten dat er met succes is aangemaakt.
* **204** - No Content. Alles is goed, maar de server hoefde geen data terug te sturen.
* **400** - Bad request. Client error. Dit gebeurt als je niet de juiste parameters meegeeft met je request.
* **401** - Unauthorized. Hetgeen wat je probeerde te doen, zou mogelijk kunnen zijn, alleen daarvoor moet je toestemming hebben.
* **410** - Gone. Dit betekent dat hier voorheen iets was, maar nu bestaat het niet meer.
* **422** - Unprocessable Entity. De request, die gestuurd is, was valide, maar er was iets fout met de data die naar de server gestuurd werd. 

Clients kunnen een hint naar de server sturen, wat voor type encoding ze willen hebben. Als de server die encoding ondersteunt, wat vaak een compression algorithme is, zal het deze vaak gebruiken en zal de server gecomprimeerde data terugsturen. Een populaire vorm hiervan is gzip.

## Werking
Http is een protocol dat door heel veel verschillende servers gebruikt wordt, om data te kunnen communiceren tussen verschillende servers / computers etc. Als je data wilt hebben stuur je naar een url een get methode en bepaalde headers, zoals ‘Accept: text/html’ , zodat de server weet ik welk format je de data wilt hebben, die de server dus als response teruggeeft in een bepaald format.

**Comment by rijkvanzanten** [comment]
Awesome! 🎉
