### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Karinliu** [cmda-be/course-17-18#449]
`open localhost:1901` open localhost:1901
`curl localhost` http request localhost
`--verbose` http request for more information from the server
`open localhost:1901/sec.page` open localhost with sec. page

# HTTP request
` --request OPTIONS `find out which ones are supported for a resource
`--request DELETE` delete
`--request HEAD`	HEAD is like GET but  tells the server not to send any data back.
`--request POST` to proceed/add something to a resource	
`--data '{"title"}' `uploading some data
`--request PUT` place a resource somewhere whether it exists already or not
`--request PATCH ` change only a few things
`--request GET` inspect the received data

# Header
`--header ‘header : value’`add request in header

# HTTP status 

### Information		
`101` Switching Protocols 

### Success
`200` OK,
`201` Created 

### Redirect
`301` Moved Permanently 

### Client error’
`400` Bad Request
`404` Not Found
`418` I'm a teapot
 
### Server Error
`500` Internal Server Error

**Comment by wooorm** [comment]
Nice @Karinliu! Awesome! 🎉
