### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by SoulaimaneEC** [cmda-be/course-17-18#450]
# HTTP Methods

```OPTIONS``` 
```HEAD```
```GET```
```POST```
```PUT```
```PATCH```
```DELETE``` 

# HTTP STATUS
2XX = SUCCES
4XX = ERROR 

# HTTP HEADERS
```Accept```, ```Accept-Encoding```
```Authorization```
Example:
```--header 'Header-name: value'```

**Comment by wooorm** [comment]
Nice @SoulaimaneEC! 👍
