### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#452]
# HTTP Cheat cheat ⚙

## Putting in JSON Data = 
```curl -i -H 'Content-Type: application/json' -H 'Accept: application/json' DELETE -d '{"key1":"value1"}' "http://hostname/resource"```

Showing detailed information using the -d parameter

## Asking for header information =
 ```curl localhost:1901/ ---verbose --request -H ```

-H short for HEAD

## Accepting XMl = 
```curl -H "Accept: application/xml" -H "Content-Type: application/xml"  GET "http://hostname/resource" ```

## JSON Put = 
```curl -i -H 'Content-Type: application/json' -H 'Accept: application/json' PUT -d '{"updated_field1":"updated_value1"}' "http://hostname/resourcex" ```

**Comment by wooorm** [comment]
Nice! It’s a little bit on the short side, and very incorrect:

* You’re sending both `Content-Type` and `Accept` everywhere. Only the Accept one works. With Accept you tell a server that you accept some type of result back. Content-Type is used to describe the data your sending. So, taking the `Accepting XMl` example, you’re saying that you’re sending XML to the server (Content-Type), and requesting XML back (Accept)
* The `Asking for header information` example doesn’t work. `-H` does not stand for HEAD, it stands for a header, which you’re omitting.
* The `Accepting XMl` example doesn’t work. You can use `--request GET`, or omit it, but just `GET` doesn’t work.
* `XMl` -> `XML`
* The `JSON Put` example doesn’t work. Use `--request PUT`

Maybe do the tutorial again? Or read up on how HTTP works a bit more?
