### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by valentijnkap** [cmda-be/course-17-18#453]
It was good tutorial for using options for curl and it displayed the principles on HTTP requests very well. 

## Cheat sheet
*HTTP status*
For every request on HTTP protocol you get a status code back to tell the client what is wrong. The meaning of all of these code can be found on [HTTP Status Codes — httpstatuses.com](https://httpstatuses.com/)

*GET - request*
Asks data from the server it has been running on. It is a HTTP method.

*The ‘curl’ command*
It stands for crawl url and can be used to get information from websites or to download files.  It has been designed to work without user interaction. more info here:  [What Is Curl And Why Would You Use It?](https://www.lifewire.com/curl-definition-2184508) 

Examples of its use:
```sh
$ curl http://example.com
```

*Adding verbose*
If you want to have more information about the request from url you can use verbose. It gives a header of the http request and the content back. It looks like this:

```sh
$ curl http://example.com --verbose 
```

*Using CURL options*
There are many ways to retrieve data from the curl options. You can find a lot of them on [curl - How To Use](https://curl.haxx.se/docs/manpage.html)

A simple example on how to get the header content of a request is:

```sh
$ curl http://example.com --verbose --request OPTIONS
```

*Using the DELETE request*
GET request is the most common but sometimes you want to delete content via the server. To do that you use the DELETE request. It looks like this:

```sh
$ curl -X "DELETE" http://example.com
```

*Information about HEAD*
Curl can use the command HEAD to get the head content of the request but it doesn’t send the body. It look likes this:

```sh
$ curl -X HEAD http://example.com
```

There is more about wat you can get back from the server. Another variant is `header`. It defines the content-type when it returns the data from curl. An example of its use:

```sh
$ curl localhost:1901 --header 'Accept: application/xml'
```

There’s also something like `gzip` content-type. It makes the content compressed and unreadable. But it isn’t supported by every client but you can always try. To get this type of content :

```sh
$ curl localhost:1901 --header 'Accept-Encoding: gzip'
```

*POST method*
With curl you can POST some data to the server. This can be done using the POST command like DELETE and HEAD.  It can be done like this:

```sh
$ curl http://example.com --request POST --data '{"title":"Wonder Woman"}'
```

*PUT method*
Same as POST method you can use the PUT  method to send some data to the server. But there is a difference between PUT and POST. 

`POST` is to add existent data to the server.

`PUT` is to  to put new data to the server.

```sh
$ curl localhost:1901/wonder-woman --request PUT --data '{"title":"Wonder Woman","plot":"Diana fights a war"}'
```

*Change existent data*
To change existent data you can use the PATCH method. You can se how in the example below:

```sh
$ curl localhost:1901/wonder-woman -X PATCH --data '{"description":"Diana leaves home to fight a war."}'
```

*Being authorized to change the API*
It is not always possible to POST or DELETE data to/from the server. You can use a token to be authorized to do so. An example on how to do it:

```sh
$curl -H "Authorization: token 5b8822b29" -X DELETE localhost:1901/evil-dead
```

**Comment by wooorm** [comment]
Nice! Some things to clarify:

* In `curl -X "DELETE" http://example.com`, the quotes around DELETE aren’t needed
* `POST is to add existent data to the server` and `PUT is to to put new data to the server` is not entirely accurate. POST adds data to a list, such as to add a movie to a list, and put is used to place or replace something at an exact point, so you can set the tenth movie, and if it already existed, it’s replaced.
* For authorization, tokens are a mechanism that some APIs use to check if you’re actually allowed to do something, be it posting or deleting, or something else entirely!

Anyway, I’m glad you liked it @valentijnkap!
