### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by jessiemasonx** [cmda-be/course-17-18#454]
I thought this was a great assignment. The explanations with every step were clear and understandable. I knew what I had to do and understood why. It's a great way to learn the basics of HTTP.

# Cheat Sheet

Curl is a command line application that can send HTTP requests. 
To send a GET request to / on localhost:1901 with Curl:  
>  curl localhost:1901

To inspect the headers sent to and from the API using Curl's verbose 
mode:  
> curl localhost:1901 --verbose  

__HEAD__ is like GET but tells the server not to send any data back. To send a HEAD request to /:
> curl localhost:1901 --verbose --request HEAD

__POST__ to / to add a movie to a list of movies  
> curl localhost:1901 --verbose --request POST  --data '{}'

__PUT__ is used to place a resource somewhere, whether it exists already or not. PUT places that something at exactly that place.
> curl localhost:1901 --verbose --request PUT --data '{}'

To change only a few things, use __PATCH__
> curl localhost:1901/wonder-woman --verbose --request PATCH --data ‘{“description":"Diana leaves home to fight a war."}'

DELETE deletes things
> curl localhost:1901/wonder-woman --verbose --request DELETE
Here you're deleting wonder woman

Sending a __GET__ request to Wonder Woman. To check if it's really deleted.
> curl localhost:1901/wonder-woman --verbose --request GET

To send a __GET__ request to / with an Accept header with the value application/xml
> curl localhost:1901/ --verbose --request GET  --header 'Accept: application/xml’

To send a __GET__ request to / with an Accept-Encoding header with the value gzip
> curl localhost:1901/ --verbose --request GET  --header 'Accept-Encoding: gzip’

GZipped data is not readable at all for humans.
__Deleting__ evil dead
> curl localhost:1901/evil-dead --verbose --request DELETE

**Comment by rijkvanzanten** [comment]
Good job 😄
