### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by ninavanbergen** [cmda-be/course-17-18#456]
I really liked this assignment because it wasn't that hard to understand and they gave good tips for writing the code. I actually enjoyed doing it haha. Hopefully it will stay that way.

## Cheat sheet

__Curl__ is a command line application that can send HTTP (Hyper Text Transfer Protocol) requests. Via curl kun je een GET request sturen naar localhost:1901:
__curl localhost:1901__

__GET__ = request a resource. 

__Verbose__ = is used to inspect the headers sent to and from the API:
__curl localhost:1901 --verbose__

__DELETE__ = is used to remove a resource:
__curl localhost:1901/wonder-woman --verbose --request DELETE__

__HEAD__ = is like GET but it tells the server not to send any data back. It is useful for checking if something exists. In the example below, you're sending a HEAD request to localhost:1901. 
__curl localhost:1901 --verbose --request HEAD__

__POST__ = is used to submit a resource. You use this to add something to a list:
__curl localhost:1901 --verbose --request POST --data '{"title":"Wonder Woman"}'__

__PUT__ = is used to create or replace a resource. You use this to put something precisely at a specific spot. The difference between __PUT__ and __POST__ is that with __PUT__ you're putting something to a specific place, and you use __POST__ to add something. If you use __PUT__ multiple times, it will overwrite the code, if you use __POST__ multiple times, it will be added to something. 

__curl localhost:1901/wonder-woman --verbose --request PUT --data '{"title":"Wonder Woman","plot":"Diana fights a war"}'__

__PATCH__ = is used to change only a few things:
__curl localhost:1901/wonder-woman --verbose --request PATCH --data '{"description":"Diana leaves home to fight a war."}'__

To check if 'wonder woman' is actually deleted, you need to send a GET request to 'wonder woman':
__curl localhost:1901/wonder-woman --verbose --request GET__

If you want to send a GET request to / with an Accept header that includes 'application/xml', you need to do this:
__curl localhost:1901/ --verbose --request GET --header 'Accept: application/xml'__

If you want to send a GET request to / with an Accept-encoding header, that includes the value 'gzip', you need to do this:
__curl localhost:1901/ --verbose --request GET --header 'Accept-Encoding: gzip'__

__Gzip__ = that is data that isn't readable at all for humans. If you request that than you'll get a lot of weird letters and marks back. 

If you want to delete 'evil dead', you need to use the DELETE request. Be aware that there may be some authorization problems, if you want to solve that, then you need to add __'Authorization: token 5b8822b29'__ to your code:
__curl localhost:1901/evil-dead --verbose --request DELETE --header 'Authorization: token 5b8822b29'__

__Some HTTP status codes that I saw in this assignment:__
200 = OK
201 = Something is created 
204 = There is no content 
400 = Bad request
401 = Unauthorized 
404 = Not found 
405 = Method is not allowed
410 = Gone
422 = Unprocessable entity

__Some HTTP headers:__
Accept and Content-type 
Accept-Encoding
Content-Encoding
Authorization

**Comment by rijkvanzanten** [comment]
Good job! 🎉
