### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#46]
# Git assignment

Goede tutorial over hoe de commands van git werken, het is even wennen aan de feedback die je krijgt. De uitleg vind ik persoonlijk erg duidelijk en helpt met het begrijpen van Git.

<img width="760" alt="screen shot 2018-02-06 at 16 19 26" src="https://user-images.githubusercontent.com/10829926/35867216-884a4b5c-0b59-11e8-9bdf-c939acd8b263.png">

**Comment by wooorm** [comment]
Good to hear!
