### ISSUE TITLE
Profile assignment

### ISSUE THREAD

**Issue by Senmetsu** [cmda-be/course-17-18#461]
https://github.com/Senmetsu/my-repo
<img width="566" alt="screen shot 2018-02-27 at 10 49 47" src="https://user-images.githubusercontent.com/15857436/36721871-69891f5a-1bac-11e8-9f49-7b82fdcee522.png">

**Comment by rijkvanzanten** [comment]
Hey @Senmetsu! I think you posted the wrong repo 🙂 
 
You've unfortunately missed the deadline, so I can't give you points for the attempt, but I'll happily give you some feedback if you comment with a link to your `dotfiles` repo 😄
