### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Sam-Guliker** [cmda-be/course-17-18#462]
<img width="550" alt="screen shot 2018-02-27 at 15 26 15" src="https://user-images.githubusercontent.com/15857436/36734008-9535cf4c-1bd2-11e8-8a86-a37cd898f8ca.png">
Everything after the 6th assessment was difficult but also learned alot.

**Comment by wooorm** [comment]
Woohoo you finished it! 🎉

**Comment by wooorm** [comment]
Awesome work, but unfortunately a tad bit too late! 😬
