### ISSUE TITLE
Package assignment

### ISSUE THREAD

**Issue by Sam-Guliker** [cmda-be/course-17-18#463]
https://github.com/Senmetsu/week2-npm 
Is this allright? 🤔

**Comment by wooorm** [comment]
Sweet, a bit to late, but here’s some feedback anyway!

* don‘t check in your node modules, instead, add  `node_modules/` to `.gitignore`
* don’t use the asterisks at the start for `*.DS_Store`, it’s not needed. Now it also checks for files called `foo.DS_Store` (but those don’t exist)
* adding `.git` to gitignore is not needed, it’s always ignored
* `email` and `url` in `package.json` don’t exist?! you can add an email (and a url) to the `author` property instead. See npm’s docs on `package.json` for more info
* if you’re linking from `package.json` to a repo on GitHub, you can do `"repository": "Senmetsu/week2-npm"`!
* keywords and description in `package.json` are supposed to be about the package!
* `"main": "index.js"` in `package.json` is not needed: that’s the default already
* bugs in package.json can just be `"bugs": "https://github.com/Senmetsu/week2-npm/issues"`, it’s a bit simpler
* the past tense of `read` in english is pronounced `red`, but still spelled as `read`!
* in your readme, don‘t copy-paste the code verbatim, rather, document it by writing some example code using it!

💪
