### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Sam-Guliker** [cmda-be/course-17-18#464]
<img width="829" alt="screen shot 2018-02-28 at 14 30 41" src="https://user-images.githubusercontent.com/15857436/36790147-36105f88-1c94-11e8-8197-6f4946d453cb.png">

leuk om met command-line te spelen 😄

**Comment by wooorm** [comment]
Super awesome that you finished it!
In the assignment, I asked for an HTTP cheat sheet:

> If you completed the tutorial, mark this assignment as complete by opening an issue on our GitHub issue tracker. In your issue, show us a cheat sheet you made of HTTP and how it works.

Could you post that below?

**Comment by wooorm** [comment]
@Sam-Guliker Ping!

**Comment by Sam-Guliker** [comment]
Oh oops, will make this tonight

**Comment by wooorm** [comment]
Pinggg!

**Comment by Sam-Guliker** [comment]
# Cheets

# Methods
You can send data via PUT  or POST.
With PUT or POST  you can create objects into the data and give them `keys` and `values`  
* PUT
* POST

### PUT
```
curl localhost:1901/wonder-woman -v --request PUT --data '{"title":"Wonder Woman","plot":"Diana fights a war"}'
```

### POST
```
curl localhost:1901 -v --request POST --data {"title":"Wonder Woman"}
```

## Read
With get you can `GET` the content via a request  

### GET
```
curl localhost:1901/wonder-woman -v request GET
```

## UPDATE
`UPDATE` gives you the oppertunity to update the data.  
### PATCH

```
curl localhost:1901/wonder-woman -v --request PATCH --data '{"description":"Diana leaves home to fight a war."}'
```

## DELETE
`DELETE ALL THE THINGS` just kidding, maybe :thinking:  
```
curl localhost:1901 /wonder-woman -v --request DELETE
```

## OTHER
### VERBOSE
Use `verbose` to get more information
```
--verbose
```

## OPTIONS
Seperates `options` from the next
```
curl localhost:1901/wonder-woman -v --request OPTIONS
```

## XML, HTML or CSV
Types of Data
```
curl localhost:1901 -v --request GET --header 'Accept: application/xml'
```

```
curl localhost:1901 -v --request --header 'Accept-Encoding: application/gzip'
```

## Authorization
Getting access to delete somthing.
```
curl localhost:1901/evil-dead -v --request DELETE --header 'Authorization: token 5b8822b29'
```
