### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#466]
Inside the document below are the codes with comments. 

[cheatsheet_http.txt](https://github.com/cmda-be/course-17-18/files/1768570/cheatsheet_http.txt)

**Comment by wooorm** [comment]
Very nice! I like the cheat sheet.
For the XML part, you say: “De Accept opent een bestand als een XML bestand”, that’s not entirely true, as `--header 'Accept: application/xml'` is more like the client asking the server for XML.
And for authorization: some stuff is not possible for everyone, so a server gives you a token (or some other mechanism) that you can authenticate with: basically like “hey, this is my key, you can check if it’s valid”!
