### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by jesseDijkman1** [cmda-be/course-17-18#468]
## Cheat sheeeeeeeet 💩

```curl``` Command line application that sends http requests. 

```curl localhost:1901``` Returns the ```<body>``` of requested page

```curl  localhost:1901 --verbose``` Returns info about the request (HEAD) and the content ```body``` 

```curl localhost:1901 (--verbose) --request METHOD``` Request something with a METHOD

```curl localhost:1901 (--verbose) --request POST --data '{}'``` Adds an empty object

**Methods**:
  - ```OPTIONS``` Find out which methods are supported
  - ```HEAD``` Get the info about the request
  - ```GET``` Get the page including head and body 
  - ```PUT``` Place resource on a certain spot whether it exists or not
  - ```POST``` Add something to a resource
  - ```DELETE``` Delete a resource 
  - ```PATCH``` Change a few things

**Status code**
  - _200-299_ Succes
  - _400-499_ Client Error

**Comment by wooorm** [comment]
Awesome Jesse! 💪
