### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by bengtbennink** [cmda-be/course-17-18#47]
YmVuZ3RiZW5uaW5rCg==

**Comment by wooorm** [comment]
Hey @bengtbennink! This code is for another assignment, not for the try git one!

**Comment by wooorm** [comment]
Did you finish the try git one? If so, what did you think?

**Comment by wooorm** [comment]
@bengtbennink Could you please reply to this message?

**Comment by bengtbennink** [comment]
It was a pretty good git if you ask me. Good for noobs like me to understand the basics.

**Comment by wooorm** [comment]
Good! I hope you like octocat as well, it’s way more useful and cool!
