### ISSUE TITLE
Transfer Assignment

### ISSUE THREAD

**Issue by patrickvdveldt** [cmda-be/course-17-18#470]
# CHEATSHEET HTTP

`curl` = It is a command line application that can send HTTP requests.

`curl localhost:1901` = Returns the body of the page.

`curl localhost:1901 --verbose` = To inspect the headers sent to and from the API using Curl's verbose.

### Methods

`curl localhost:1901 --verbose --request POST` = used to add something to a resource. (Like example: to add a movie to a list of movies).

`curl localhost:1901 --verbose --request PUT` = to add something on a certain spot, if it exists or not.

`curl localhost:1901 --verbose --request HEAD` = is like GET but tells the server not to send any data back. To send a HEAD request to /

`curl localhost:1901 --verbose --request DELETE` = to Delete some things

`curl localhost:1901 --verbose --request OPTIONS` = The OPTIONS method represents a request for information about the communication options available on the request/response chain identified by the Request

`curl localhost:1901 --verbose --request PATCH` = When you want to change some things

### HTTP Status Codes

* 200-299 OK
* 400-499 ERROR

**Comment by wooorm** [comment]
Awesomeee!
