### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by JimvandeVen** [cmda-be/course-17-18#471]
[CHEATSHEET](https://github.com/JimvandeVen/backend/blob/master/HTTP-cheat-sheet.md)

**Comment by wooorm** [comment]
Good work Jim!

P.S. do you remember the github prereq, where you had to sign up for GH?

> Take some time to set up your GitHub profile. Include your name, a profile picture, and a URL to your homepage. You’re allowed to stay anonymous online for this course by omitting sensitive information, but a good looking GitHub profile can help you get an internship or job later.
