### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Denniswegereef** [cmda-be/course-17-18#474]
# Cheatsheet

## request on HTTP
* `Curl localhost:xxxx`
     Fire a get request to the localhost
* `Curl --verbose`
     inspect headers from the request 
* `Curl --request GET`
     Get the data from the url
* `Curl  --request OPTIONS`
    See all the possible options to the request
* `Curl --request DELETE`
     Request a delete method
* `Curl--request POST`
     Send data to the host
* `Curl --request POST —data ‘{}’`
    Send a empty JSON object to the host
* `Curl --request HEAD`
     Send out a head request only (for example check if something exists)
* `Curl --request PUT`
     Put something in an existing JSON object
	`curl <host> —request PUT —data <data>`
* `Curl--request PATCH`
     Replace something 
	`curl <host> —request PATCH —data <data>`
* `Curl --header 'Accept: <format>'`
    Request a different type of format
	For example:
	`curl localhost:XXXX --header 'Accept-Encoding: gzip'`
	Another example with the Authorization
	`--header 'Authorization: token 5b8822b29'`

## Tips
* Gzip is a compression algorithm to reduce the file size of JSON data 
You can use it with the `accept-encoding header`

## Errors
* 422 Unprocessable Entity
    * Request was valid but there was something wrong with the data
* 401 Unauthorized 
    * You have no acces to fire a request to the server
	
<img width="558" alt="screen shot 2018-03-03 at 12 25 38" src="https://user-images.githubusercontent.com/12157616/36933731-918e3dca-1ede-11e8-867a-5aefe87a3cd4.png">

**Comment by wooorm** [comment]
Nice Dennis!

P.S. do you remember the github prereq, where you had to sign up for GH?

> Take some time to set up your GitHub profile. Include your name, a profile picture, and a URL to your homepage. You’re allowed to stay anonymous online for this course by omitting sensitive information, but a good looking GitHub profile can help you get an internship or job later.

**Comment by Denniswegereef** [comment]
@wooorm I've updated my profile picture and a short description now :)

**Comment by wooorm** [comment]
Sweet! 🤵
