### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Roene** [cmda-be/course-17-18#476]
# HTTP Status codes
## Succes
**200** OK 
**201** Created
## Client errors
**400** Bad request
**401** Unauthorized
**403** Forbidden
**404** Not found
**408** Request Timeout
**418** I'm a teapot
## Server errors
**500** Internal Server Error
**502** Bad Gateway
**504** Gateway Timeout
# HTTP Request
* OPTIONS --> Find out which methodes are supported
* HEAD --> Info about the request
* GET --> Get the page including the head & body
* PUT --> Place a resource somewhere whether it exists already or not
* POST --> Add something to a resource
* PATCH --> Change only a few things
* DELETE --> Delete a resource 
# Complete transfer exercise
![complete_transfer](https://user-images.githubusercontent.com/31709511/36934010-daa29f2a-1ee2-11e8-9fc2-30eb5ef2c6f6.PNG)

**Comment by wooorm** [comment]
Nice work Roene!

What’s the red dot on the top-left of the image though? 🤔
