### ISSUE TITLE
learnyounode assignment

### ISSUE THREAD

**Issue by Mennauu** [cmda-be/course-17-18#477]
I was sick for 2 weeks (couldn't even handle being behind the computer). I know it's late but I finished the course anyway. 

Up until "Juggling Async" I was able to complete the exercises without looking at tutorials or others who had finished the course. it took a long time but I managed. 

Especially the last assignment was difficult. It took too much time so eventually i gave up and looked at how others did it. 

You can find all codes I completed each exercise with on this page: https://github.com/Mennauu/learnyounode/blob/master/README.md

**Comment by wooorm** [comment]
Nice work @Mennauu! Awesome that you could finish so much without looking up examples, and great that you looked up examples for the stuff that was hard!
As you mentioned, it’s unfortunately late though, so no points.

I really dig how you solved all the problems, well done! 💪
