### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by nguyent047** [cmda-be/course-17-18#478]
# HTTP cheatsheet:

curl localhost:1901 - send a GET request to / on localhost:1901
* `--verbose` - inspect headers sent to and from the API
* `--data` - sending data in headers and values
* `--request` - request one of the following:

* `OPTIONS` - tells you which methodes are supported for a resource
* `DELETE` - deleting a resource
* `GET` - getting information
* `HEAD` - similar to GET, but tells the server not to send any data back
* `POST` - adding something to a resource
* `PUT` - place a resource whether it exists already or not
* `PATCH` - make changes to something

**Comment by wooorm** [comment]
Nice work Alyssa!

P.S. do you remember the github prereq, where you had to sign up for GH?

> Take some time to set up your GitHub profile. Include your name, a profile picture, and a URL to your homepage. You’re allowed to stay anonymous online for this course by omitting sensitive information, but a good looking GitHub profile can help you get an internship or job later.

**Comment by nguyent047** [comment]
Thanks for remembering me! I'm going to make changes to my GH profile soon!
