### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by jeroentvb** [cmda-be/course-17-18#479]
Good assignment to learn how HTTP works 👍 

Here's my cheat sheet:
# HTTP Cheat Sheet

* `curl [url] --verbose` - Verbose curl request

* GET / HTTP/1.1 - is a GET request over HTTP versions 1.1

* `--request OPTIONS` - returns (all) options

## Status codes
* 200 OK
* 201 Created
* 204 No content
* 400 Bad request
* 405 Method not allowed - method is not supported
* 422 Unprocessable Entity - valid request but sent data was invalid
* 401 Unauthorized
* 404 Not found
* 410 Gone

## POST stuff (with curl)
```bash
curl localhost:1901 --verbose --request POST --data '{"title":"Batman"}'
```
The '' are important

## Types of requests
* POST adds something
* PUT replaces something
* HEAD returns only HTTP data, no body (text) included. Head requests are useful for checking if something exists
* PATCH replaces/adds one property
* DELETE deletes an entry
  - `--header 'Authorization: token 273yvg435'` - to authorize a request
* GET fetches content
  - `--header 'Accept: application/xml'` - to get content in xml format
  - `--header 'Accept-Encoding: gzip'` - to get content that is gzipped

**Comment by wooorm** [comment]
Well done!

Note that put can also add something: just that it places something at an exact position. POST adds something to a list. PUT places something, whether it exists or not, at an exact place.

Also, OPTIONS is a request just like GET, HEAD, PUT... etc.
