### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by MonikaaS** [cmda-be/course-17-18#482]
Here is my cheatsheet, finally finished the assignment! 

It was a bit of a struggle because I constantly got the message: 
`curl: (7) Failed to connect to localhost port 1901: Connection refused` 

------

# HTTP METHODS:
`GET` = Request the data
`OPTIONS` = To find out which HTTP methods are supported for a resource
`DELETE` = Remove things
`HEAD` =  is like GET but tells the server not to send any data back. One of the things it is useful for is checking if something exists, even if it is not actually needed.
`POST` =  POST is used to add something to a resource.  So if / is a list of movies, POSTing to it should add a movie to the list!
`PUT` = used to place a resource somewhere, whether it exists already or not.
`PATCH`= Use it to only change a few things (you don’t have to put in all the data type’s such as title etc.)

# SUCCES: 
`200` = Everything is working ok
`201` =  Created
`204` =   No Content

# CLIENT MADE AN ERROR:
`400`=   Bad Request
`401` =   Unauthorized
`404 `=   Not Found
`405` =    Method Not Allowed
`410` =     Gone
`422` =    Unprocessable Entity (the request was valid, but there was something wrong with the data being sent to the server.)

**Comment by wooorm** [comment]
Nice! Well done 💪

The connection refused error is super weird! I’m wondering why that was happening 🤔
