### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by RobinStut** [cmda-be/course-17-18#485]
Was opzich wel te doen, alleen ik had niet door dat we zo exact moesten overtypen.

cheat sheet:

cUrl haalt die inhoud op van een site

Met verbose laat je alles zien in de site plus de header informatie

Met request option haal je alleen die header info op.

user-agent	wie maakt er contact
accept		wat voor data wilt die client?
200			status
date			datum
Allow		lijst met toegestane methodes
Head		stuurt geen data terug
POST		Je voegt iets toe
PUT			zet iets neer op een plaats

Jeez dat ding is gevoelig, een spatie na —data is verplicht (vb. —data ‘{}’)

**Comment by wooorm** [comment]
Pretty short for a cheat sheet, compared to this one https://github.com/tiimgreen/github-cheat-sheet or this one https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet! That makes it harder to remember this stuff the following weeks!

But glad you figured it out anyway!
