### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by MartijnReeuwijk** [cmda-be/course-17-18#486]
![av3d5gn_460s](https://user-images.githubusercontent.com/15121010/36970566-56e75350-2069-11e8-82c3-c5f5c04767c2.jpg)
Was do able got stuck on a few ' and " pretty infuriating but all is well

Cheat-sheet Made in google drive don't know how it will look in github 

Curl | Haalt data van het internet
-- | --
--verbose | Haalt de gewone date  van de site
--request | Aanvraag
--request OPTIONS | Haalt alleen de metadata
--request DELETE | Delete request
--request HEAD | Vraagt de Head aan.
--request POST | Stuurt data ??
POST --data '{}' | In data stuur dat
PATCH | Update een server
'Accept-Encoding: gzip' | Encode met Gzip kan ook met iets anders

**Comment by MartijnReeuwijk** [comment]
Cheatsheet looks nice straight from My google docx so i can add more later.

**Comment by MartijnReeuwijk** [comment]
Don't steal my meme please

**Comment by wooorm** [comment]
Wait, so are you going to post some more stuff? 🤔

**Comment by khualu** [comment]
Nice meme.

**Comment by wooorm** [comment]
@MartijnReeuwijk Pingg!

**Comment by MartijnReeuwijk** [comment]
Not in this post but il add more to my own Docx
