### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by vallleynl** [cmda-be/course-17-18#488]
## Cheat sheetje

--verbose
--data
--header

--request
DELETE
PATCH
GET
PUSH
HEAD
OPTIONS
POST

**Comment by wooorm** [comment]
Pretty short for a cheat sheet, compared to this one https://github.com/tiimgreen/github-cheat-sheet or this one https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet! That makes it harder to remember this stuff the following weeks!

But glad you figured it out anyway!

P.S., do you remember the github prereq?

> Take some time to set up your GitHub profile. Include your name, a profile picture, and a URL to your homepage. You’re allowed to stay anonymous online for this course by omitting sensitive information, but a good looking GitHub profile can help you get an internship or job later.
