### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#49]
Ik vond de opdracht niet heel handig omdat ik niet heel goed kon leren van het overtypen van de lines. Als ik meer uitgebreidere uitleg zou kregen bij de commando's die je moest invoeren dan zou ik hier veel meer van leren.

**Comment by wooorm** [comment]
Ahh, I get that. Maybe you’d like this one though? https://learngitbranching.js.org
