### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Rowin206** [cmda-be/course-17-18#490]
Finished transfer assignment
<img width="564" alt="screen shot 2018-03-05 at 13 29 28" src="https://user-images.githubusercontent.com/33234293/36975148-7cd3d01a-2079-11e8-840a-c34d4b53b20c.png">

# Cheatsheet transfer 

## API (for movies)
Means: server returns data (In this case: JSON data)

## Localhost & curl

Curl: command line app, that can send HTTP requests. More options than browser.

Sending a http request in your webbrowser: localhost(bv: :1901) to reach the server. 

curl localhost:1901 in your terminal to get 
the same response, but in the terminal instead of your webbrowser. 

## Head 
API sends info about the request, aka headers. They don’t display that information, like <head> element in html. 

You can get the information with: 
—verbose 

Document starts with: GET = request line
*: data 
>: request
<: response

## Find out which options are supported for a resource

curl localhost:1901 --verbose --request OPTIONS

Status codes in the range of 4xx = error
Status codes in the range of 2xx = everything is ok, but no need for the server to send any data back

HEAD = same as get, without the body. 
POST = add something to a resource
PUT = place a resource somewhere, if it exists or not
PATCH = change only a few things

### API returns: 
JSON data
XML data
HTML or CSV or other data, based on what the client wants

Client can support some kind of coding, so the server will send compression alsorithm. Gzip is popular compression. 

You can authorise a request by using a token.

**Comment by wooorm** [comment]
SWEEET!
