### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by MartijnReeuwijk** [cmda-be/course-17-18#492]
Listing 
I think it went pretty well but i need some help with the Tree i tried to make it work with a Modual but it didn't work. would like some Feedback thx :)
This is my github link:
https://github.com/MartijnReeuwijk/staticserverv1

**Comment by rijkvanzanten** [comment]
Hey @MartijnReeuwijk!

Are you sure your server is working properly? I get the 404 page for every page I try to open 🙁

**Comment by wooorm** [comment]
🤔
