### ISSUE TITLE
Transfer Assignment

### ISSUE THREAD

**Issue by superstephan1** [cmda-be/course-17-18#493]
# Cheat sheet http:

>curl: Curl is a command to send http requests.
>curl localhost:1901 sends a request to your local http server.

>Post = push data to server
>Options request= returns http options.

## Http request methods:
HEAD: same as Get but returns only HTTP headers and no document body.
PUT: Uploads a representation of the specified URL.
DELETE: Deletes the specified resource.
OPTIONS: Returns the HTTP methods that the server supports.
CONNECT: Converts the request connection to a transparent TCP/IP tunnel.

## Http status codes
1XX - Informational responses
2XX - Success
3XX - Redirection
4XX - Client errors
5XX - Server errors

## Debugging
—verbose = Sort of diagnostic mode

**Comment by wooorm** [comment]
Nicely done! 💪

P.S., do you remember the github prereq?

> Take some time to set up your GitHub profile. Include your name, a profile picture, and a URL to your homepage. You’re allowed to stay anonymous online for this course by omitting sensitive information, but a good looking GitHub profile can help you get an internship or job later.
