### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by Karinliu** [cmda-be/course-17-18#494]
https://github.com/Karinliu/listening

The first four were doable. Even though I had to do  a lot of research on the internet. But de last one where the server should respond with a nice looking list of files in the /images directory i did not know how to do it.

**Comment by rijkvanzanten** [comment]
Hey @Karinliu! Quick tip for next time, add the installation and usage instructions to the readme 🙂

**Comment by rijkvanzanten** [comment]
Good job! The code looks solid. The package you use to read the filesystem (`fs`) also has methods available to read directories. Maybe this [answer on StackOverflow](https://stackoverflow.com/questions/2727167/how-do-you-get-a-list-of-the-names-of-all-files-present-in-a-directory-in-node-j) can help you out?
