### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by khualu** [cmda-be/course-17-18#495]
**curl**: 'link' gets you basic information from a server
**--verbose:** gets you the invisible information about your GET request
**--request:** makes it possible to ask information from a server with some commands that are made possible. 
**HEAD:** gets meta-data bout the information that is on the server
**DELETE**: lets you delete a part (or the whole bunch) of the information on the server. You might need a special authorization for this. 
**OPTIONS**: Shows you which commands you can use in the server. 
**POST**: Makes a new category. This was in json for now.
**PUT**: lets you add information to the server, while reposting the information that already existed. 
**PATCH**: lets you add information without having to repost the information that was already on the server
_For these last three options you need to add the --data to the command, and since it was in json, we had to put the json opject in it '{}' _

**Comment by wooorm** [comment]
Sweet!
