### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by labraksam** [cmda-be/course-17-18#496]
# **TRANSFER NOTES** 

## Methods
**GET** 
give me the thing, from localhost:1901 

**HEAD** 
HEAD is like GET 
tells the server not to send any data back.
same as GET but without body

**POST**
used to add something to a  resource 
list of movies > POST should add a movie to the list. 

**PUT**
places resources somewhere

**POST**
adds something to a resource 

**PATCH**
sends a patch > change something 

## Status

HTTP/1.1 200 OK 
HTTP 	protocol 
/1.1 	version
200 	status version
OK 	reason phrase 

4xx range > client error 
2xx range > request successful, but no content > no need for the server to send any data back

**Comment by wooorm** [comment]
SOO MANY CAPS!

**Comment by labraksam** [comment]
OEPS, not finished yet :D

**Comment by labraksam** [comment]
now it is. WITH LOTS OF CAPS.

**Comment by wooorm** [comment]
Sweet! Well done Sam!
