### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by joostflick** [cmda-be/course-17-18#500]
# Cheat sheet
#### GET
Receive data from a specified url

#### HEAD
Does the same as GET but tells the server not to return a message-body in the response

#### POST
Add something to an already existing resource

#### PUT
Place a resource somewhere. If there is something at that position replace it

#### PATCH
Update a resource, either partial or as a whole

#### DELETE
Speaks for itself, delete something

#### 200 - OK
Request is succesful

#### 301 - Moved Permanently
The url you requested is permanently on another address

#### 400 - Bad Request
Server did not understand the request

#### 403 - Forbidden
Although the server knows the client the client does not have the rights to visit this url

#### 404 - Not Found
You requested a resource that the server is unable to find, possibly because of a wrong url

#### 500 - Internal Server Error
Something went wrong on the server.

**Comment by rijkvanzanten** [comment]
Good job 😄
