### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Bauke777** [cmda-be/course-17-18#501]
# Curl Cheatsheet

Curl can be used as a CLI user agent to make HTTP requests with the terminal

A typical Curl-command could look something like this

```curl localhost:1901```

A curl command without arguments will give you the content of the requested document. By adding arguments like `--verbose` you can also show HTTP headers.

## Curl arguments

`--verbose`	Shows you the HTTP header of the request

`--request <method>`	Sends a HTTP request tot the URL using a specific method

`--request OPTIONS`	Sends a HTTP request and requests the available methods of the URL

`--request DELETE`	Sends a HTTP request using a DELETE method

`--request HEAD`	Sends a HTTP request using a HEAD method (Request only the head)

`--request POST`	Sends a HTTP request using a POST method (Sending data)

`--request POST --data '{}'`	Sends a HTTP request using a POST method with data in JSON-format

`--request PATCH`	Sends a HTTP request using a PATCH method (Update data)

**Comment by Bauke777** [comment]
I'm not quite sure if all above is correct, maybe someone can review my issue?

**Comment by rijkvanzanten** [comment]
LGTM!

The only thing I'd alter is `--verbose`. You're right in terms of `cURL`, but `--verbose` is used in many CLI tools and generally provides additional details as to what the program is doing 👍
