### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by LindadeHaan** [cmda-be/course-17-18#503]
[Link to repo](https://github.com/LindadeHaan/listing-assignment.git)

I thought the first part of the assignment was the part I could do, but the second part was hard.  
I tried to do the part with the assets folder, and I thought it worked, but it didn't. I tried to fix it, but I couldn't do it.
The last part with the list, I had no idea how to do that. I tried to figure it out, but I didn't quite understand how to do it.

**Comment by rijkvanzanten** [comment]
Feedback:
* I don't have the Nexa Light font 🙁 Green Times New Roman ftw!
* Be careful with the messy indentation. It doesn't affect the code functionality directly, but it makes it very easy for you as a programmer to make new bugs 
* Add installation / usage instructions to the readme, so people who aren't familiar with your server structure know how to get it up and running

As for the last part: the same module you use to read files (`fs`), also [has some methods available](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) to read the filenames in a folder. Maybe that can help you get further along?
