### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by Jmbjojo** [cmda-be/course-17-18#505]
Useful tutorial!

* API: is a server that returns data
* Curl: is a command line application that can send HTTP requests
* --verbose code: Show hidden information sent from the server
* OPTIONS: give all commands supported by HTTP
* Status 422: Unprocessable Entity
* Status 201: Created, a success code for new resources
* POST: is used to add something to a resource
* PUT: is used to place a resource somewhere, whether it exists already or not
* PATCH: To change only a few things

* HTTP methods: OPTIONS, HEAD, GET, POST, PUT, PATCH, and DELETE
* HTTP status codes: 200 OK, 201 Created, 204 No Content, 400 Bad Request,
401 Unauthorized, 404 Not Found, 405 Method Not Allowed, 410 Gone, and 422
Unprocessable Entity
* HTTP headers: Accept and Content-Type, Accept-Encoding and
Content-Encoding, and Authorization
* How to use Curl to make requests, set headers, and send data to a server

HTTP is a standard protocol, not all serversuse the same methods or status codes.  For example, OPTIONS and PATCH areoften not used, and 400 Bad Request is often used instead of other 4xx errors.

**Comment by rijkvanzanten** [comment]
Good job! 🎉
