### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by iSirThijs** [cmda-be/course-17-18#507]
I did the assignment in lab, but didn't make a cheatsheet back then 😕. Didn't feel like doing it again. Did practice it a lot by calling the slack API for another project 💃

**Comment by rijkvanzanten** [comment]
Heya @iSirThijs! What did you do with the Slack API? 😄

**Comment by wooorm** [comment]
You could also still make a cheat sheet about HTTP! what methods there are, some useful status codes, headers, etc...

**Comment by wooorm** [comment]
@iSirThijs Pinggg!

**Comment by iSirThijs** [comment]
Sorry, forgot to reply 😬 . 

@rijkvanzanten I had to sent some POST request for a slack app I'm developing for work. 

@wooorm I will try to built a cheatsheet if time allows me to, maybe when I'm working on the Slack API again for the other project.

**Comment by wooorm** [comment]
Hey Thijs! You didn’t finish this assignment. I’m glad you did the tutorial and practiced with slack, but I would’ve liked a cheat sheet! 🤷‍♂️
