### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by sterrevangeest** [cmda-be/course-17-18#509]
I couldn't finish the assignment. 😞 

I have spend a lot of time understanding the plain-server, which I think I do understand now.  I tried some things then, but that was harder than I expected.

I want to finish the assignment because I just want to understand it, but I just need a little bit more time. 

[This is my repo right now.](https://github.com/sterrevangeest/plain-server.git)

**Comment by rijkvanzanten** [comment]
Hey @sterrevangeest! 

Right of the bat, it's very hard for me to figure out what you build or what is @wooorm's.. 

Could you let me know what you did and how you did it? Thanks 🙂

**Comment by wooorm** [comment]
Ping!

**Comment by sterrevangeest** [comment]
I have used the plain-server. I tried to write some code by myself, that code didn't work, but it did helped me to understand what I did wrong by comparing my code with the plain-server example. I understand that you can't give me points for this, and that it's hard to figure out what I build.  
It was a process changing and writing new lines again. It is a little bit hard to show that. So in the end I used the plain server as an example, because that server did work. 

I think I understand a lot of the code about HTTP and Node, but I just find it hard to write new code by myself.
