### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by vallleynl** [cmda-be/course-17-18#51]
<img width="790" alt="screen shot 2018-02-06 at 16 33 38" src="https://user-images.githubusercontent.com/23484332/35867963-80ff8928-0b5b-11e8-9f49-b2a536daa564.png">

Leuke hulpzame tutorial, alleen jammer dat je kan _"cheaten"_ door gewoon te klikken op de code.

**Comment by wooorm** [comment]
Ahh, yeah that’s true, I hope you didn’t do that though! 😉
