### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by Techdemo** [cmda-be/course-17-18#514]
# Listing Assignment 

Really enjoyed the assignment but unfortunately I didn't finished it. The plain server did work but after line 16, my error messages got crazy. (unread was undefined all of the time). 
I will work on this assignment another time, because I really enjoyed it. 

[here is the link to my repo](https://github.com/Techdemo/Listing-assignment/tree/master)

**Comment by rijkvanzanten** [comment]
Hey @Techdemo!

Good job 😄 

## Feedback

### Repo
* Add installation and usage instructions to your readme, so someone who is not familiar with your project's structure (eg. me) knows how to get it up and running 
* Don't check `node_modules` into `git`. The dependencies will be managed through `npm` and all have their own repo's. No need to make your repo messy by having the dependencies in there 😄 

### Code
* Watch your indentation. While it doesn't effect code performance or functionality, it makes it way harder to figure out which `{` goes with which `}`. 

### Functionality
* The server doesn't seem to.. work? I get empty responses from the server. I got the feeling `res.end()` gets called before your server is done reading the file. Did you test if the server works correctly?
