### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by ninavanbergen** [cmda-be/course-17-18#518]
I didn't understand the assignment, and I needed a lot of help to get through it. I couldn't finish it because it was too hard to understand for me.. so I am thinking about going to homework class on friday, maybe they can help me because I just can't do this by my self I think..

Anyway, here is my [repository](https://github.com/ninavanbergen/listing.git)

**Comment by rijkvanzanten** [comment]
Hey @ninavanbergen!

Do you understand what is going on in your `index.js` file, or is it all a big mystery?

You can always reach out on Slack if you have questions too!
