### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#519]
Hi Guys,

I'd got some issues with the code. First of all a new language is always difficult. Sometimes I don't know exactly what the solution is. After some time (mostly several hours) and some moodswings I got a solution. In one sentence: "It was hard enough but I need too much time for this.".

The exercise was hard but not too hard in my opinion. It was the perfect way to learn some NODE.js 

Below the github link to my repository:

https://github.com/GuusDijkhuis/listing

**Comment by rijkvanzanten** [comment]
Heya!

> First of all a new language is always difficult
You have experience in other languages? 😄

**Comment by rijkvanzanten** [comment]
## Feedback

### Repo
* Add a readme❗️ 

### Code
* Looks solid!
* Try moving the 404 page to a separate HTML file.

### Functionality
* Does as advertised, which isn't a lot, but works

Did you try implementing the file listing part of the assignment?
