### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by khualu** [cmda-be/course-17-18#52]
a2h1YWx1Cg==

**Comment by wooorm** [comment]
Hi @khualu! Is it correct that you didn’t finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for this week? Especially note this part of the slack prereq:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.

**Comment by wooorm** [comment]
Thanks @khualu!

**Comment by wooorm** [comment]
P.S., don’t forget the markup assignment!
