### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by nguyent047** [cmda-be/course-17-18#524]
Hereby I present you [the polar bear server](https://github.com/nguyent047/polarbear/tree/master).

I actually quite enjoyed this exercise, even though it took me longer than 5 hours and, once again, I'm wondering if I did it right. There are some things I would've done differently if I had more time, though.

1. When using `curl localhost:8000/images/avatar.png --verbose --request GET` in Terminal, it gives a neat response, including 200 OK and content-type... yet after that the screen fills up with loads of characters. I still haven't figured out why yet, but it kind of annoys me.
2. I added two style.css files to this project, both have the same content. It's a bit messy, I'm planning to fix it soon.
3. I would have loved to add a license, .gitignore, package.json etc., but I don't think I want to be sleep deprived any longer. I might add them another time.

As for feedback, I don't really have much. Maybe that's because it's late.

**Comment by rijkvanzanten** [comment]
Hey @nguyent047! 

Good job 😄 

## Feedback

### Repo
* Awesome! You're one of the few who actually wrote a useful readme 😄 👍 

### Code
* Nice and concise 👍 
* Smart solution of listing the files by just hardcoding the names. Why bother reading the directory programmatically if you know the files in there in advance already 😄 

Just to make sure, are those images licensed to be used in this way or did you make them yourself? You uploaded them to a public file repository, which the original author probably doesn't like (if they aren't yours) 😅

**Comment by nguyent047** [comment]
Hey @rijkvanzanten 

Thanks for the feedback!
I agree. The assignment should've specifically asked for my server.js to read the directory if they wanted me to do so after all. 😄

The images are from [Freepik](https://www.freepik.com/about). Freepik is a search engine for free vector designs, though I have to credit the author of the illustrations (which I have done now, sorry, that totally slipped my mind 😅). Do you think it might be better if I create my own images instead?

**Comment by rijkvanzanten** [comment]
Better? Not necessarily, but that way it's 100% sure you won't run into licensing issues ever 🙂
