### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by FJvdPol** [cmda-be/course-17-18#525]
# Transfer Assignment

# HTTP cheatsheet

## Curl
```
curl pagename
```
Haal een pagina van een server op en print de response (in de terminal in dit geval)

```
curl pagename --verbose
```
Hetzelfde als hierboven, maar print de request en response headers mee.

## Methods
```
curl pagename --verbose --request OPTIONS
```
Standaard bepaald curl welke method er gebruikt moet worden voor een request. Je kunt dit zelf bepalen door `--request methodname` aan de curl command toe te voegen.
Er zijn een beperkt aantal opties, bepaald door de server, deze kun je uitlezen in de response headers.

Wanneer een methode niet wordt ondersteund door de server/api, dan krijg je netjes een error op je dak:
```
HTTP/1.1 405 Method Not Allowed
```

De HEAD method geeft je alleen de headers die bij de request en response horen. Niet heel interessant dus.
Behalve als je alleen wil checken of een item bestaat. Zo ja, statuscode = 200, zo nee, statuscode = 404

## Requests and responses
De request is iets als dit:
```
OPTIONS / HTTP/1.1
```
Waarbij options the methode is die je toepast, de losse "/" de route, en vervolgens het protocol en de versie daarvan.

De response is iets als dit:
```
HTTP/1.1 200 OK
```
Opnieuw het protocol met versie, vervolgens een status code en status message. In dit geval is alles goed.

## Posting data
```
curl pagename --verbose --request POST
```
Dit geeft een error omdat je niet meegeeft wat je wil posten.
```
curl pagename --verbose --request POST --data '{}'
```
Dit geeft een error omdat je geen title property hebt aka lege data
```
curl pagename --verbose --request POST --data '{"title": "value"}'
```
Dit post netjes de data en voegt het toe aan de lijst

In plaats van POST kun je PUT gebruiken, die een locatie waar je hem heen stuurt overschrijft in plaats van toevoegd aan een mogelijk bestaande lijst.

## Updating data
```
curl pagename --verbose --request PATCH --data '{"property": "value"}'
```

## Deleting data
```
curl pagename/item --verbose --request DELETE
```
zorg er wel voor dat randoms niet authorized zijn! Anders kan het zo zijn dat je database byebye is.

Je kunt wel een authorization header aanmaken en een speciaal token bepalen waardoor het wel kan.
```
--header 'Authorization: token 5b8822b29'
```

## Downloading data
```
curl pagename/item --verbose --request GET
```
Returns 410 gone if it doesn't exists

```
--header 'Accept: type'
```
type kan zijn application/xml bijvoorbeeld. Hiermee bepaal je hoe de response er uit ziet.

**Comment by rijkvanzanten** [comment]
Awesome! 🎉
