### ISSUE TITLE
Listing assignment

### ISSUE THREAD

**Issue by deannabosschert** [cmda-be/course-17-18#527]
Wasn't able to test it though; kept receiving the message that localhost refused the connection

### Repository
https://github.com/deannabosschert/listing_week3

**Comment by deannabosschert** [comment]
Sorry for the late response, been sick for the past two days..  Changed them both to request/response. I'm aware that there are a lot more things wrong/missing in the code but haven't been able to pinpoint them. Probably missing a few crucial things but keen to find out

**Comment by deannabosschert** [comment]
Fixed it, should work now. Will now make sure everything's from the assignment is actually in it

**Comment by rijkvanzanten** [comment]
> Will now make sure everything's from the assignment is actually in it

Hey @deannabosschert! Guess this didn't go according to plan? 😅

**Comment by rijkvanzanten** [comment]
## Feedback

### Repo
* Good little readme. Contains the useful things without the fluff 👍 

### Code
* Watch your indentation. While it doesn't sound like much, it can actually help you in coding as it makes your code way more readable. For example, the `onRequest` function. It ends in three `}` on the same line.. No way of knowing to what `{` they belong!
* What is [line 41](https://github.com/deannabosschert/listing_week3/blob/master/server.js#L41) supposed to do?
* [Nice use of the `in` operator](https://github.com/deannabosschert/listing_week3/blob/master/server.js#L32) 🙂
