### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by gitelig** [cmda-be/course-17-18#529]
# Cheatsheet transfer

### Create 
  * Put
> curl localhost:1901/wonder-woman -v --request PUT --data '{"title":"Wonder Woman","plot":"Diana fights a war"}'

>  **"PUT is nice for saving a 
whole resource, but you need to send other properties (like title) along as 
well, even if they did not change."**

  * Post
> curl localhost:1901 -v --request POST --data {"title":"Wonder Woman"}
>  **"Submit a resource"**

### Read
  * Get
> curl localhost:1901/wonder-woman -v request GET
### Update
* Patch
> curl localhost:1901/wonder-woman -v --request PATCH --data '{"description":"Diana leaves home to fight a war."}'    
> **"To change only a few things, use PATCH"**
### Delete
> curl localhost:1901 **/wonder-woman** -v --request DELETE

### Other  
* Verbose
>  --verbose
>  -v

* Options
> curl localhost:1901/wonder-woman -v --request OPTIONS

* XML, HTML or CSV
1. > curl localhost:1901 -v --request GET --header **'Accept: application/xml'**
2. > curl localhost:1901 -v --request --header  **'Accept-Encoding: application/gzip'**

* Authorization
curl localhost:1901/evil-dead -v --request DELETE --header **'Authorization: token 5b8822b29'**

**Comment by rijkvanzanten** [comment]
Good job! Unfortunately, you missed [the deadline of this assignment](https://github.com/cmda-be/course-17-18/blob/master/week-3.md#transfer)
