### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by theonejonahgold** [cmda-be/course-17-18#53]
# Mijn markdown dingetje
Een mooi lijstje met interessante informatie
- Dit is leuk
- Ik heb geen inspiratie

Nog een lijstje
1. Woah een één!
2. Woah een twee!
3. Omg een drie!

Hier is een link naar een hond

![Small white doggo in grass field](https://www.petmd.com/sites/default/files/small-dog-breeds.jpg)

```bash
echo 'ECHO'
```
☝️ print ECHO

1. Een lijst
    * In een lijst
        * In een lijst

**Comment by wooorm** [comment]
Very nice!
