### ISSUE TITLE
Transfer assignment

### ISSUE THREAD

**Issue by aman233** [cmda-be/course-17-18#530]
curl example.com = reads url in html
--verbose: reads the header and gives extended information about what is done there.
-- request: request a task such as OPTIONS, HEAD, POST, PATCH, GET, (in some cases or with approval) DELETE
             * OPTIONS: reads what is possible with --request
             * HEAD: Works like get but only reads the header instead reading everything
             * POST: Let's you upload data to a server
             * PUT: Let's you put data into the things in a safe way(correct url required)
             * PATCH: Let's you update data without touching other things(correct url required)
                 (PPP)> use --data '{}' and put what you want to post between the brackets
              (they're sort of the same but understood differently by HTTP)
             * GET: You get a response from the server. 
             * DELETE: Let's you delete data if you have permission

--header: used to communicate with the header of a server. You can use it to add or change stuff
(--request GET --header 'Accept*(-if applicable): *(application/) whatever

**Comment by rijkvanzanten** [comment]
Hey @aman233! Could you clean up the cheatsheet a bit using markdown? Makes it way more _readable_ 😄
