### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by LindadeHaan** [cmda-be/course-17-18#534]
[Shelter Linda](https://github.com/LindadeHaan/shelter)

I only did the fist two bullet points of the assignment because I thought the assignments were a bit vague. 
And because of private issues I couldn't concentrate enough to fully understand the assigment.
So I thought is was a pretty hard assignment.

**Comment by rijkvanzanten** [comment]
Hey @LindadeHaan!

Did you write any of this by yourself? I notice [your `get` function](https://github.com/LindadeHaan/shelter/blob/master/server/index.js#L39-L62) is eerily similar to the one @theonejonahgold made..........

Ref @wooorm:

@LindadeHaan:
https://github.com/LindadeHaan/shelter/blob/master/server/index.js#L39-L62

@theonejonahgold:
https://github.com/theonejonahgold/shelter/blob/master/server/index.js#L47-L69

**Comment by LindadeHaan** [comment]
I looked at some others code, to understand what had to be done. 
And i googled a lot.

**Comment by wooorm** [comment]
Looks like this: https://gist.github.com/wooorm/64a4d94014984f005afe740b321ef6b8

**Comment by wooorm** [comment]
👋

**Comment by wooorm** [comment]
Hey Linda! I’m glad you started, and I get that it’s hard, but it a) doesn’t work, b) isn’t as far as you should be, and c) using someone else code without a citation is **not ok**!
