### ISSUE TITLE
Shelter Assignment

### ISSUE THREAD

**Issue by iSirThijs** [cmda-be/course-17-18#535]
Hello

I've spent around 12 hours (8 hours on Friday and today 4 hours) on this assignment. I've come to the conclusion that I'm lacking in javascript knowledge and it's affecting how long it takes to do the assignments. I've haven't read all materials for front-end yet, so I've decided to get back to that and get up to date on that. 

So [here's](https://github.com/iSirThijs/shelter) what I've got so far though.

**Comment by rijkvanzanten** [comment]
> around 12 hours (8 hours on Friday and today 4 hours)

Yikes! That's a long time.. Do you have a clear idea of the specific JavaScript related things you want to work on?

**Comment by rijkvanzanten** [comment]
Your `delete` code isn't working as expected. It's trying to run the function `validate` on L47 which is undefined: https://github.com/iSirThijs/shelter/blob/master/server/index.js#L47

**Comment by iSirThijs** [comment]
@rijkvanzanten I've made a new commit: the delete code should work now

I'm behind on the homework of Frontend 2, which is of course, javascript.

**Comment by rijkvanzanten** [comment]
You only respond stuff to the client when the item exists in `get`, meaning the browser will time out on a 404:

https://github.com/iSirThijs/shelter/blob/6169be9253a45e2c84c93346828acfa43a49fe56/server/index.js#L37-L43

**Comment by iSirThijs** [comment]
Correct me if wrong, but  the `errorHandling` ends the response by sending a 400/404/410. So it shouldn't time out. 

Maybe only a  `return` in an else statement?
