### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by Denniswegereef** [cmda-be/course-17-18#536]
I started it before the weekend but was quite busy to find some time to make progress. That means I have to do a little bit more this week but that's okay I can manage that.

I completed the first 4 bullet points but it took me some time to find out how I can manage errors and how the application is working..

Link to my current repo
https://github.com/Denniswegereef/shelter

**Comment by rijkvanzanten** [comment]
Hey @Denniswegereef!

* You store the ID of an animal in the variable `url`. That naming might be a bit confusing. I recommend calling it `id` instead.
* The notFound function you wrote isn't used anywhere!
* Seeing you use the error object you create right away, there is no need storing it in the function scope.

**Comment by wooorm** [comment]
Hey this looks sweet! Nicely done

* nodemon is a nice addition!
* tip: remove `console.log` from your code, use something like [`debug`](https://www.npmjs.com/package/debug) for debugging!
* What’s [`devare`](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/server/index.js#L28) 🧐
* [tip: respond with json if requested in all](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/server/index.js#L36-L42)
* Your [`delAnimal`](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/server/index.js#L93-L103) function doesn’t do anything on already removed animals, doesn’t handle unfound animals, crashes on invalid identifiers, and sends a 204 back **as an error** if successful 🤔 messy!
* What’s the [`field`](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/server/index.js#L114) property?
* Tip: place inputs in a label, that way you don‘t have to use `for` and `id` to link them together!
* You’re not using `id` on inputs, so now they aren‘t linked at all!
* Use [placeholders](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/view/form.ejs#L21) for sample values, not for labels (that’s what labels are for)
* Why [set `value` on the intake, age, weight, primary color, and secondary color](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/view/form.ejs#L28)?
* Use [`checked` on checked checkboxes](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/view/form.ejs#L46)!
* You don’t need [`type=submit` on buttons in forms](https://github.com/Denniswegereef/shelter/blob/430713e172416003b2810830b68c326511d4249b/view/form.ejs#L55): they’re submit buttons by default
* There’s `type=date` for date inputs, that’s more useful that text!
* Weight can be decimal, but not with your input (set `step` to `any` or `0.1` to allow decimals)
* There’s no link to the form anywhere i can click


Good luck this week with storage! 💪
