### ISSUE TITLE
Shelter assignment.md

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#538]
## Shelter

Learned alot about working with express, was a very good exercise and fun project. but i always find it very hard to start and write the full code myself but i've found alot of help in the sheets.  And asking fellow students. Made it all the way to the form function and got that working which is pretty cool, spent alot of time figuring out the data input with body-parser. 

learned alot see the commits for info

[My Shelter](https://github.com/Marijnone/shelter)

**Comment by rijkvanzanten** [comment]
Good job 😄 

* Love how you added a Progress document
* You've installed and required the `slug` package, but don't use it
* Good job on getting the namespacing work!
* You forgot the `name` attribute on the text input for the name, which also causes the form handler code to error on creation of a new item.
* You could add a catch all `.use('*')` at the end of the "express stack" to create a global 404
* You might want to consider naming certain functions a little more descriptive. `form` could (IMO) both mean 'render form', or 'send form', or 'process form', or anything regarding a form really.
* the indentation of the `add` function is all over the place, makes it a bit hard to read
*

**Comment by rijkvanzanten** [comment]
* Your `remove` function only sets the status to 204 on a successful delete, but doesn't respond to the client. Therefore, the request times out
