### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by BasPieren** [cmda-be/course-17-18#54]
De Try Git tutorial is een prettige tutorial om te volgen. Alles word duidelijk uitgelegd en geeft een goed overzicht van de basis van Git. Het is wel veel informatie om in één keer te onthouden maar dat word gewoon een kwestie van het vaak doen.

**Comment by wooorm** [comment]
Yup, true, practise makes perfect!

**Comment by wooorm** [comment]
Oh, and don’t forget the run assignment!
