### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#540]
The shelter assignment is not too bad but it cost much time. After all I came further than I thought. The first bullet point was a misunderstanding on my part. I've done the one with db.remove(). After the get function de db.remove was a lot easier, it was almost the same, but I'd an issue with the errorcodes. 
At least I'd learned something, and that's what I want.

[Klik dan!](https://github.com/GuusDijkhuis/shelter)

**Comment by rijkvanzanten** [comment]
Hey @GuusDijkhuis! Have you tried if the app actually works? I tried running it with `npm start` but it immediately errors out.. 

```
~/Development/shelter [master]
☛  npm start

> shelter@1.0.0 start /Users/rijkvanzanten/Development/shelter
> node server

/Users/rijkvanzanten/Development/shelter/server/index.js:9
  .set('views', 'view');
  ^

SyntaxError: Unexpected token .
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shelter@1.0.0 start: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shelter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rijkvanzanten/.npm/_logs/2018-03-13T13_42_21_053Z-debug.log
```

**Comment by GuusDijkhuis** [comment]
I've got some `; ` after each line in module.exports = express(). So I removes all the `;` and the error is removed.

**Comment by wooorm** [comment]
This looks like a great start @GuusDijkhuis, well done!

* You’re rendering the results of the list of animals twice: https://github.com/GuusDijkhuis/shelter/blob/3ebe91dbf8446143a9d6eb38b4e9250a2c8ee3ef/server/index.js#L34-L41. You should enable the one or the other! (you can see an error in your terminal, right?)
* I don’t get JSON when requesting one animal (`curl http://localhost:1902/89590 --verbose` gives HTML)
* DELETE doesn’t work through HTML, so the goal was to respond with JSON in the `remove` function, but you’re rendering HTML!
* [You’re sending a 404 back when removing an animal with an invalid id](https://github.com/GuusDijkhuis/shelter/blob/3ebe91dbf8446143a9d6eb38b4e9250a2c8ee3ef/server/index.js#L96), that should be a 400 bad request
* [You’re sending a 400 back when an animal is not found](https://github.com/GuusDijkhuis/shelter/blob/3ebe91dbf8446143a9d6eb38b4e9250a2c8ee3ef/server/index.js#L108), that should be a 404 not found
* [You‘re handling 204 as an error if you successfully delete an animal](https://github.com/GuusDijkhuis/shelter/blob/3ebe91dbf8446143a9d6eb38b4e9250a2c8ee3ef/server/index.js#L105). a 204 is successful, not an error. Also: 204 means there’s no content to send back, so if you send a 204 you shouldn’t send data back
* What’s the [`server/start`](https://github.com/GuusDijkhuis/shelter/tree/master/server/start) directory you added 🤔
* You [installed `views`](https://github.com/GuusDijkhuis/shelter/blob/3ebe91dbf8446143a9d6eb38b4e9250a2c8ee3ef/package.json#L20), but you’re not using it anywhere? What do you need it for? 🤷‍♂️


Other than all the above points, you’re well on your way. Good luck completing this and with the storage assignment! 💪
