### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by maanlamp** [cmda-be/course-17-18#541]
🍴[Look at my forked repo](https://github.com/maanlamp/shelter),
[Or at the comparison between both repo's](https://github.com/cmda-be/shelter/compare/master...maanlamp:master)

# Overview
* Did not enjoy the assignment at all. 👎
* Took way more than 6 hours (around 2 full afternoons to be precise), so I ran into some time management issues; luckily I'm the only one to be blamed for that. 😅

The assignment was excruciating. I have general experience in programming, but not with express. Everything was new for me: not only the code you wrote, but also the whole express doohickey. In the end I probably read more than I actually typed, which, in my book, is not really enjoyable (although insightful). Even after the countless hours of reading, I still feel like I don't understand half of what I did.

My console was screaming at me with warnings that I couldn't possibly have invoked, I used the Node FileSystem when express probably has it's own methods for serving images and many more things... like I said: excruciating.

On the other hand, I think this is showing me that I _definitely_ :clap: _do_  :clap: _not_ :clap: like back-end programming, so I'll stick to front-end. I guess that's good?

## p.s.
I'm wondering though: if this assignment takes _me_ multiple afternoons, then how would someone with _0 experience_ do this at all? I'm just not sure wether you're accounting for the 90% of the class that barely knows how to use var... or am I wrong in assuming they lack enough knowledge? 🤔

**Comment by rijkvanzanten** [comment]
> Did not enjoy the assignment at all. 👎

Sorry to hear that 😞 

> My console was screaming at me with warnings that I couldn't possibly have invoked

Hate to break it to you, but running Node without any script doesn't throw any errors, so something must've happened

**Comment by rijkvanzanten** [comment]
> Did not enjoy the assignment at all. 👎

Sorry to hear that 😞 

> My console was screaming at me with warnings that I couldn't possibly have invoked

Hate to break it to you, but running Node without any script doesn't throw any errors, so something must've happened 😜

> On the other hand, I think this is showing me that I definitely 👏 do 👏 not 👏 like back-end programming, so I'll stick to front-end. I guess that's good?

Ay ay ay, that's a bold statement. Working on a big scale front-end project nowadays requires _a lot_ of Node usage too! Between all the bundlers / transpilers and other buzzwords, you will see that you actually use a lot of Node in the day to day. Also, when building front-end only single page apps, you'll most likely use a router of some sorts, which oftentimes works very similar to express!

> I'm wondering though: if this assignment takes me multiple afternoons, then how would someone with 0 experience do this at all?

That's a very valid question! We aren't too strict when grading these assignments, and we're convinced that it's a very good experience to get thrown a major curveball like this at school every now and again. If we would only keep it at `var`s and `function`s at school, you'd be completely nowhere when trying to build a "real" project.

**Comment by rijkvanzanten** [comment]
* Try not to mix `var`s and `let` / `const`. It's good practice go stick with either `var` or `let`/`const`.
* When starting the app, I'm immediately greeted by two deprecation warnings:
  ```
  body-parser deprecated bodyParser: use individual json/urlencoded middlewares server/index.js:17:8
  body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
  ```
* The CSS isn't being loaded
* Always add `<label>`s to form fields. 
  <img width="1292" alt="screen shot 2018-03-13 at 9 53 53 am" src="https://user-images.githubusercontent.com/9141017/37345937-7709dbbc-26a4-11e8-93ef-975ef586ae1b.png">
* Use appropriate form elements for certain fields. If there's only a choice of 3, you could use radio buttons or a select instead of a text input
* Awesome use of object destructuring and promises in combination with `async` `await`!
* Make sure to also add a `reject` clause to your `exists` function in case `fs.stat` barfs
* `resolve(err === null);`. Calling `resolve` is by itself a sign that the function succeeded. Consider passing something more useful, like the actual file information in the `resolve`
* You only push a single `_err` object into the `errs` array in your `add` function. Why bother with an array in the first place?
* If your `error.ejs` template only works with an array, consider refactoring it to also accept a single object, or send your single object wrapped in an array as follows to cleanup your code a bit: `{errors: [errs]}`
* Overall, good job!

**Comment by maanlamp** [comment]
> Hate to break it to you, but running Node without any script doesn't throw any errors, so something must've happened 😜

Yep, it happened when I imported the whole body-parser thing. Still have no clue what the errors mean.

>Try not to mix vars and let / const. It's good practice go stick with either var or let/const.

I _never_ use var. Any instance of it is from the original code. I just didn't bother to change it because it might break things, and it works as it is 😅

> When starting the app, I'm immediately greeted by two deprecation warnings

Yep, those are the body-parser errors. No clue whhat to do with/about those.

> The CSS isn't being loaded

It did load for me... I don't know how that happened?

> Always add <label>s to form fields.

Again, because I was quite unhappy during the assignment I didn't bother to do a lot of things I really should have; sorry.

> Use appropriate form elements for certain fields. If there's only a choice of 3, you could use radio buttons or a select instead of a text input

Didn't think about that at all... whoops 😅

> Make sure to also add a reject clause to your exists function in case fs.stat barfs
resolve(err === null);. Calling resolve is by itself a sign that the function succeeded. Consider passing something more useful, like the actual file information in the resolve

This was a bit trivial. If the function didn't throw an error, that means my promise should return true, else (if there is an error) it should return false. So even when fs.stat errors, it should resolve the promise. At least, that was my train of thought. After all, I just wanted to check if a file exists; I didn't actually want to use the stats object.

> You only push a single _err object into the errs array in your add function. Why bother with an array in the first place?

>If your error.ejs template only works with an array, consider refactoring it to also accept a single object, or send your single object wrapped in an array as follows to cleanup your code a bit: {errors: [errs]}

The template wanted an errors array -- I gave it one :)
Lazy programming, sorry.

Again, thanks for helping me improve!

One more question: I didn't figure out how to load images with express, even when using express.static(). How should I have done it (because I'm sure my Node FS method isn't as simple)?

**Comment by wooorm** [comment]
> Yep, it happened when I imported the whole body-parser thing. Still have no clue what the errors mean.

They were warnings, the readme of body-parser explains ’em ;)

> One more question: I didn't figure out how to load images with express, even when using express.static(). How should I have done it (because I'm sure my Node FS method isn't as simple)?

https://github.com/theonejonahgold/shelter/blob/bde77e0fa57abd00e4b7ad3c5a420cda4d7ca536/server/index.js#L27

**Comment by maanlamp** [comment]
>https://github.com/theonejonahgold/shelter/blob/bde77e0fa57abd00e4b7ad3c5a420cda4d7ca536/server/index.js#L27

Pretty sure that's the first thing I tried... I must've made a silly mistake 🙁
