### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by Mimaaa** [cmda-be/course-17-18#545]
It's not finished yet, but I learned quite a lot.

Things that I still want to do: 
* Add remaining methods
* Refactor code (for example: adding a error handling function which makes the code much cleaner)
* Add appropiate styles
* Add code comments
* Support PUT
* Support PATCH

[My Repo](https://github.com/Mimaaa/shelter)

**Comment by rijkvanzanten** [comment]
Good job 😄 

* Nicely split up commits
* Not a huge deal, but you shouldn't use `nodemon` for production sites. In most projects, `npm start` would be the command to start the project for production usage, while something like `npm run dev` is used for development mode. I recommend leaving `npm start` as is and adding `npm run dev` for nodemon 👍 
* (This also broke the start command for me, seeing I installed the dependencies with `npm install --production)
* Code looks very neat! ✨ 
* Try to avoid "weird" ternary operators. They can be very useful for small assignment based operations like:
  ```js
  var isDead = true;
  var age = isDead ? 22 : 'n/a';
  ```
  But try to use them sparingly. IMO `declawed: body.type === "cat" ? body.declawed === "yes" : undefined` is hard to understand
* Nice accessible markup in the form
* Tip: look into [`debug`](https://npmjs.com/debug) to replace all the console.logs with
* I know you got it from a stackoverflow answer, but even then. Never copy and paste code directly. That one function you copied uses a `const`. Your whole server works without ES6 except for that one copied function. Also, it uses a `comma operator` in the return, which is very hard to read. 
* Also, the error that function throws `"Something went wrong"` is very _very_ generic. You know exactly what went wrong there (the mimetype wasn't jpeg). Try to make the error message more useful by providing useful information.
* After adding a new animal, I get redirected to that animal. Unfortunately, the image itself isn't uploaded?
* Deleting works 👍 (There isn't a way to delete from the interface though)

**Comment by Mimaaa** [comment]
Bit too late, but thanks for all the feedback. Definitely going to try fixing everything up. 👍
