### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by Bauke777** [cmda-be/course-17-18#547]
I'm kind of stuck on the 404 part https://github.com/Bauke777/shelter

**Comment by wooorm** [comment]
Hey @Bauke777, looks like a good start, but I’m feeling like you didn’t put in considerable time or effort: it looks like my code, with some `onerror` stuff (probably inspired by someone else?) on top...

For feedback: don’t use code from someone else (`onerror`) if you don’t understand it. Remove them, and [try rendering a template like you already do in other places](https://github.com/Bauke777/shelter/blob/01e2573ddad12085c13b62b11bf7ea1e6477aff5/server/index.js#L26) 🤷‍♂️
