### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by jessiegouw** [cmda-be/course-17-18#548]
Here is mine [**Shelter**](https://github.com/jessiegouw/shelter) assignment. It's not done for sure, but I still want to try to let the whole server work properly because I do like the assignment and I want to understand every single bit of nodejs and express.

**Comment by wooorm** [comment]
This looks like a great start @jessiegouw, but it’s buggy!

* What’s [`Icon`](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/Icon%0D) 🤔
* Don’t [include `path` in `package.json`](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/package.json#L22), it’s included in node: no need to install it with npm
* I’m missing some docs on what you did in the readme!
* You're creating two express servers: [one here](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/server/index.js#L4) and [one here](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/server/index.js#L11)
* You’re rendering all animals three times: [for `/`](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/server/index.js#L17), [`/view`](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/server/index.js#L19), and on [`/db`](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/server/index.js#L27)!
* You’re rendering the [list twice](https://github.com/jessiegouw/shelter/blob/44a78f16684b854a1ab870005652cddf47903557/server/index.js#L34-L40): include the one or the other!
  <img width="1386" alt="screen shot 2018-03-16 at 13 12 34" src="https://user-images.githubusercontent.com/944406/37520022-bd3049b8-291b-11e8-8cff-028a89ea0e13.png">
* The `get` and `onerror` functions are (nearly) identical to Jonah’s code. I’m glad you mentioned him in the readme, but that sucks! I at least expect you to change code you find to your own style, make it your own, and not include things you don’t really use!
* cool favicon!
* You removed the `<title>` element from the templates!
* the form doesn’t have any labels!
* everything in the form is in one big fields!
* there’s many fields required, even if they’re actually not required!
* I’m missing Staten Island Animal Care Center!

>  It's not done for sure, but I still want to try to let the whole server work properly because I do like the assignment and I want to understand every single bit of nodejs and express.

Glad to hear that but then you need to start working on it! Good luck Jessie! 💪
