### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by valentijnkap** [cmda-be/course-17-18#549]
Nice assignment! Learned a lot from the existing code but it was good for me to dive in the express module. Here's my [repo](https://github.com/valentijnkap/shelter)!

**Comment by rijkvanzanten** [comment]
Go to bed! 😴

**Comment by wooorm** [comment]
Hey this looks like a great start @valentijnkap! I love how you documented your thought process in the readme, well done 👍 I didn’t know you could do `req.param('id')`! I’ve only seen examples like so: `req.param.id`!

To me it feels like a great start, but not significantly done yet, so I’m not giving points for this assignment; I hope you agree!

Good luck this week with storage! 💪

**Comment by valentijnkap** [comment]
Hey @wooorm . I do agree with your decision! But I am more than happy that you like my readme. its nice to hear.
