### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by ReiniervanLimpt** [cmda-be/course-17-18#550]
https://github.com/ReiniervanLimpt/shelter

I felt a bit demotivated after last weeks lecture but the subjects made a lot more sense when i started working on the assignment. My biggest issue was forming a mental model around what exactly the HTTP methods of last weeks listing and transfer assignments were for (maybe because i did not finish those assignments either?).

My shelter assignment is far from finished but i am now more confident in my ability to comprehend what we've been doing over the last couple of weeks :^). I have already installed the slug and body-parser dependencies so i could work on adding a form (as mentioned in the lecture) but i got stuck on the step before that.

I know i have a lot of catching up to do and i will continue to work on this assignment, taking notes along the way.

time spent: 7 hours

**Comment by rijkvanzanten** [comment]
You missed the deadline by a whopping 2 minutes 😱

**Comment by ReiniervanLimpt** [comment]
i tried...

**Comment by rijkvanzanten** [comment]
Haha no worries, it’s fine 😉

**Comment by wooorm** [comment]
Hey @ReiniervanLimpt, this looks like a good start, you’re making some connections in the code already that show you have some understanding of what’s going on, but you should definitely start adding more stuff soon!

> I know i have a lot of catching up to do and i will continue to work on this assignment, taking notes along the way.

Please do!

* [You’re including `slug`, but it’s not used anywhere](https://github.com/ReiniervanLimpt/shelter/blob/31ac0a6f653c3ca22fa34f420e871e829ff02e00/server/index.js#L6)
* is [`db.all` needed here](https://github.com/ReiniervanLimpt/shelter/blob/31ac0a6f653c3ca22fa34f420e871e829ff02e00/server/index.js#L41)?
* don’t leave `console.log`s in the code you hand in!
* `doetEigenlijkHelemaalNiksVolgensMijDusWaaromGeefIkHierEenParameterMee`: see [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Description)
* There already exists a [`result` here](https://github.com/ReiniervanLimpt/shelter/blob/31ac0a6f653c3ca22fa34f420e871e829ff02e00/server/index.js#L65), so why create a new one?
* [These weren’t needed](https://github.com/ReiniervanLimpt/shelter/blob/31ac0a6f653c3ca22fa34f420e871e829ff02e00/view/error.ejs#L14-L15), as the image already contains useful text!

Good luck!
