### ISSUE TITLE
Storage assignment

### ISSUE THREAD

**Issue by Murderlon** [cmda-be/course-17-18#555]
Everything should be in there though I didn't have to time to refactor some things for better error handling.

I continue to dislike SQL queries and especially the arbitrary boiler plate code for pooling connections across routes with `mysql`.

https://github.com/Murderlon/shelter

**Comment by rijkvanzanten** [comment]
Hey @Murderlon!

Do you have a database dump and some install instructions so I can check it out? Thx :)

**Comment by wooorm** [comment]
@theonejonahgold Ping!

**Comment by wooorm** [comment]
@Murderlon Ping!

**Comment by Murderlon** [comment]
MySQL was set up using Docker through Kitematic.

<img width="1293" alt="screen shot 2018-03-25 at 17 45 16" src="https://user-images.githubusercontent.com/9060226/37876956-53c3d518-3054-11e8-9215-b241aeae3c2f.png">

I used a script to populate the db.

```js
require('dotenv').config();
const pool = require('./server/mysql');
const data = require('./db/data.json');

pool.getConnection((err, connection) => {
    data.map(({id, ...animal}) => {
      connection.query('INSERT INTO animal SET ?', animal, (err, done) => console.log({err, done}));
    })
    connection.release();
    // Handle error after the release.
    if (err) throw err;
  });
```

Which basicly resulted in a non-relational copy of the db in MySQL. I know, the assignment was to make it relational but unfortunately I didn't have a lot of time when I made this.

<img width="1680" alt="screen shot 2018-03-25 at 17 47 41" src="https://user-images.githubusercontent.com/9060226/37876989-a6a294fe-3054-11e8-9dba-e13a223ce4f7.png">

**Comment by rijkvanzanten** [comment]
This is unfortunately not enough information to get up and running. I still don't know what's supposed to go in your `.dotenv` files or how to replicate your setup..

Even with trying to get it up and running by manually figuring out the `.env` contents, I get an unhandled error as soon as I try to open the page

```
~/Development/shelter [master]
☛  npm start

> shelter@1.0.0 start /Users/rijkvanzanten/Development/shelter
> node server

listening on http:localhost:1902
/Users/rijkvanzanten/Development/shelter/server/index.js:28
    connection.query('SELECT * from animal', done);
               ^
```

I also don't know how you setup your database (what columns / datatypes / etc), and as you already mentioned: 

> I know, the assignment was to make it relational but unfortunately I didn't have a lot of time when I made this.

> I continue to dislike SQL queries and especially the arbitrary boiler plate code for pooling connections across routes with mysql.

Check out [Bookshelf](http://bookshelfjs.org) and alleviate the pain
