### ISSUE TITLE
Storage assignment

### ISSUE THREAD

**Issue by admirai** [cmda-be/course-17-18#557]
Its now 23:36 and I've created my first database with relevant data. 
I've watched some video's about MySQL and learned more about databases and their purpose. 
For now I only added one animal to the database.(the other 7 are in the making)
I'm happy that I managed to do it, because I was a bit depressed after the shelter assignment that didn't work out for me.

[My First Database](https://github.com/admirai/shelter/blob/master/my-first-database.sql)

**Comment by rijkvanzanten** [comment]
Hey @admirai! Good job on the SQL setup. Looks good 🙂 

The assignment was to update your shelter submission so it would use your newly created SQL database.. So unfortunately, I can't give you any points for just the database.
