### ISSUE TITLE
Shelter assignment

### ISSUE THREAD

**Issue by ninavanbergen** [cmda-be/course-17-18#560]
Here is my [link](https://github.com/ninavanbergen/shelter) to my repository

**Comment by rijkvanzanten** [comment]
Good job! 😄 

## Feedback
* Try to use Git / GitHub for it's intended purposes. It really makes a difference!
* There is no way from the interface to navigate to the `/add` route
* Good job on the comments! 
* > Has heeft titus gemaakt en dat boeit niet
  
  😂 
* CSS is not working
* You don't respond anything to the client on a successful delete
* You can't have two inputs in the same label:
  ```html
  <label>
    Sex
    <input type="radio" name="sex" value="female">
    Female
    <input type="radio" name="sex" value="male">
    Male
  </label>
  ```
  This will break the functionality of the labels themselves. Instead, try wrapping multiple inputs and multiple labels into a `<fieldset>` for a more semantic solution:
  ```html
  <fieldset>
    <legend>Sex</legend>
    <label><input type="radio" name="sex" value="female">Female</label>
    <label><input type="radio" name="sex" value="male">Male</label>
  </fieldset>
  ```
* Try to keep names and comments in English. It's easier to find solutions to problems if you think about and discuss them in English 🇺🇸 


All in all, really well done! Code is very concise, nicely organized and well commented.
