### ISSUE TITLE
Storage assignment

### ISSUE THREAD

**Issue by Marijnone** [cmda-be/course-17-18#561]
I found it pretty hard to debug sql and after googling around found the ```debug:true``` option which makes it easier to debug your sql queries. With that turned on i could see which table names where incorrect or had the wrong data types. Got the delete function working which was kinda complex but looking at the slides and working with classmates. Only thing i could not figure out was how to get my db working with a second table using left joins. Also could not manage to export my db?? tried the example as given in de assingment. But ofcourse SQL keeps giving me errors. I do have this image ![db](https://imgur.com/lLpcpNI.jpg)

[link to repo](https://github.com/Marijnone/shelter)

**Comment by rijkvanzanten** [comment]
> Also could not manage to export my db??

Have you tried [`mysqldump`](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html)?

Unfortunately, this image alone doesn't give me enough info to work with 🙃 I don't know what datatypes, what lengths, what relations, etc..

**Comment by rijkvanzanten** [comment]
## Feedback
* Cleanup the readme a bit. Right now, there is a lot of wrong and outdated information, and the order doesn't really make any sense.
* The remove button on single animals doesn't seem to do anything
* CSS/JS aren't working 😭 
* Code looks pretty good! Nicely lint free.
* The "thanks to Tim Ruiterkamp for explaining and helping" section isn't being used and can be removed completely

All in all, does as advertised!

_It was a true pain in the ass to get the DB up and running without the instructions, but luckily you just figured out how to create database dumps on Windows_
