### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by bengtbennink** [cmda-be/course-17-18#58]
YmVuZ3RiZW5uaW5rCg==

**Comment by wooorm** [comment]
Hi @bengtbennink! Is it correct that you didn’t finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for this week? Especially note this part of the slack prereq:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.

**Comment by bengtbennink** [comment]
Hey,

Yes I did do al the prereqs for this week but I’m not totally sure that I’ve filled in all the correct GitHub things.

My GitHub: bengtbennink
My slack: benninkbengt@gmail.com <mailto:benninkbengt@gmail.com>

**Comment by wooorm** [comment]
You didn’t send your information over slack to Laurens, I think.

P.S. If you reply to github emails, the world can see it. That’s fine, just thought you should know!
