### ISSUE TITLE
Package Assignment Review

### ISSUE THREAD

**Issue by Razpudding** [cmda-be/course-17-18#6]
Hmm is it necessary for students to understand what the code does? Because in that case we need to change this ex. so it asks students to include this package and to run it on some strings. I'm pretty sure they wont follow from just reading the code.
I don't expect anybody to realize that `repeat-string` needs to be added to the dependencies without running the code for instance.

I also doubt they'll spend 3 hours on reading about package files. Maybe we need to add more steps like: Write code that uses this package. Ah and I've just realized that's what you want them to do with 'Take ± 3 hours to create a project around the below code:'. That needs to be more explicit! I initially thought that just means write the package and readme.

Ok so my proposed steps would be:
- Create git repo holding the index.js file (hint:git setup source)
- Write code that uses this package (hint: require)
- Test the packages different functions
- Think about what the package does and then write the readme. Commit it
- Now run npm init and fill out the basic metadata
- Open up package.json and add important metadata like dependencies, license etc.

**Comment by wooorm** [comment]
As discussed on Slack, we’ll see how this goes with the first vague assignment, profile, the week earlier! I made a few changes in the slides to make some of your concerns more clear.
I also feel like the assignment already lists some of your steps?
Let’s revisit after the first week!
