### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by vallleynl** [cmda-be/course-17-18#61]
Is cool maar uitleg kan beknopter en als je een typefield aanklikt scrolt ie steeds naar boven, heel irritant.
<img width="1109" alt="screen shot 2018-02-06 at 16 44 42" src="https://user-images.githubusercontent.com/23484332/35868579-366bc974-0b5d-11e8-8fb2-cebe6f0dfc64.png">

**Comment by wooorm** [comment]
Haha, thanks! Well done!
