### ISSUE TITLE
The last commit specifies bash instead of sh. This causes issues on windows :bug:

### ISSUE THREAD

**Issue by Razpudding** [cmda-be/course-17-18#66]
What's the right way to label this bug and connect it to this commit? 2102761119d92d6ec5c86fa937fc230837c4d2c6

**Comment by wooorm** [comment]
Weird, in my class I had it the other way around!!!

**Comment by wooorm** [comment]
I’m guessing it’s that they haven’t set up the sub shell properly. I’ll see in my other class how it goes!

**Comment by wooorm** [comment]
@Razpudding I didn’t run into this today at all. I think the people who did that, actually didn’t enter bash first on their Windows computer. And they should have!
