### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by labraksam** [cmda-be/course-17-18#68]
De uitleg is helder. Het is alleen veel om direct te onthouden. Omdat je eigenlijk geen fouten kan maken door dat het antwoord al word laten zien, gaat het best snel. Als je wel fouten kon maken zou het leren misschien sneller gaan.

**Comment by wooorm** [comment]
Ahh, yeah I get that. I hope practise will make perfect!

P.S. Don’t forget to hand in the

**Comment by labraksam** [comment]
thanks for reminding! 👍
