### ISSUE TITLE
Assignment General Remarks

### ISSUE THREAD

**Issue by Razpudding** [cmda-be/course-17-18#7]
If we want students to consume certain resources, we shouldn't list them under "tips". As the amount of (new) content in this course is overwhelming we can't expect most students will go over the tips section.
I would propose to include any resource we feel is crucial to understanding in the ass(can we switch this term to something that abbreviates better next year? 🍑) itself. For instance if you want students to write their own package.json, they need one single resource that covers this topic well. this resource is now listed under tips (https://docs.npmjs.com/files/package.json). I would include reading it as a step in the exercise.

**Comment by wooorm** [comment]
Done! Let me know if you feel more tips should be inlined!

**Comment by wooorm** [comment]
And I don’t think anything is wrong with peaches 🍑😉
