### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by valentijnkap** [cmda-be/course-17-18#72]
Both of them where good exercises to practice and to understand what's happening. 

**So here are my links:**
* [Introduction to GitHub](https://services.github.com/on-demand/intro-to-github/you-completed-github-flow)
* [GitHub Pages from the Command Line](https://services.github.com/on-demand/github-cli/merge-pull-request-github-showcase)

**Comment by wooorm** [comment]
Hey @valentijnkap! Do you have a link to your PR from the intro to GH part?

**Comment by valentijnkap** [comment]
You can fin my PR [here](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14358)

**Comment by wooorm** [comment]
Great!
