### ISSUE TITLE
Markup Done

### ISSUE THREAD

**Issue by jesseDijkman1** [cmda-be/course-17-18#74]
# = <h1>
###### = <h6>

> = "Citaat"
> 
> "2e Citaat (Spatie hoeft niet)"

**Bold**

_Italics_

1. Zo
2. Kan 
3. Een 
* Lijst  
  * Worden
  * Gemaakt

**Comment by wooorm** [comment]
Wow, what’s going on with the headings?!

**Comment by jesseDijkman1** [comment]
I forgot you can't see it in editor-mode

**Comment by wooorm** [comment]
Ahh, yeah the HTML is rendered as actual HTML here (so you can’t see them), but if you use the web inspector here on github you’ll see they are actual extra H elements!

<img width="351" alt="screen shot 2018-02-07 at 12 43 43" src="https://user-images.githubusercontent.com/944406/35914737-9eaa4b8a-0c04-11e8-93ea-ce6e52be875c.png">
