### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by timruiterkamp** [cmda-be/course-17-18#75]
### 1e voltooide opdracht
[Github pullrequest](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14359)

### 2e voltooide opdracht
[Github pages site](https://github.com/timruiterkamp/timruiterkamo.github.io)

**Comment by wooorm** [comment]
Your PR looks great, but it seems your GH pages doesn’t work: <http://timruiterkamo.github.io>. Hmm, any idea why?

**Comment by timruiterkamp** [comment]
Whoops! There was a typo, but the page is still not completely visible. I will submit the correct link in a few minutes !

**Comment by wooorm** [comment]
You can just comment here btw if it starts working! And: caching of GH sometimes takes up to 10 minutes!

**Comment by timruiterkamp** [comment]
Ah okay, i think the link will display correctly then in 10 minutes. The problem was that i called the repo timruikterkamo instead of timruiterkamp.github.io. And it should be the same as the username so that's why i got the 404 page.

**Comment by wooorm** [comment]
Okay! It could also be that you need to change the settings of your profile, to host pages from master instead of another branch?

**Comment by timruiterkamp** [comment]
I have looked into the possibility of the wrong settings but it says that the website is being build from the master branch. I've added a photo with the settings.

I'm going to re-do the steps to see if i maybe missed something.  
![screen shot 2018-02-06 at 19 39 34](https://user-images.githubusercontent.com/10829926/35877495-b57697d6-0b75-11e8-9718-2c7a7498a543.png)

**Comment by wooorm** [comment]
Hmm, maybe you don’t need Jekyll, if you just host HTML/CSS(/JS)?

**Comment by timruiterkamp** [comment]
It works again with HTML and Css, just need to add content and styling now haha 😄

**Comment by wooorm** [comment]
Ahh, what was wrong?

**Comment by timruiterkamp** [comment]
The lack of content in the index.html was the problem!

**Comment by wooorm** [comment]
Ah, you also linked yo `https://timruiterkamo.github.io` instead of `https://timruiterkamp.github.io` (note the kam~~o~~p)!
