### ISSUE TITLE
Run assignment

### ISSUE THREAD

**Issue by jessiegouw** [cmda-be/course-17-18#8]
amVzc2llZ291dwo=

**Comment by wooorm** [comment]
@jessiegouw Nice! How did it go?

P.S. Could you do the prereqs first? If you can make it to class this week, we’ll start doing the assignments there, no need to do them before class!

**Comment by jessiegouw** [comment]
@wooorm The half of it I already knew and the other half I just searched on google lol.

Already did the prereqs before going to work today and I'll be attending the classes this week!

**Comment by wooorm** [comment]
Ah okay, don’t forget the slack part:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.
