### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by lauraesmee** [cmda-be/course-17-18#80]
Vond ik het makkelijk? Ja. Vond ik het leerzaam? Nee. Uit deze opdracht begrijp ik nog niet helemaal wat ik echt precies doe en wat git dan doet. Ondanks dat ik het wel goed doorneem, misschien meer een kwestie van meer oefenen.

**Comment by wooorm** [comment]
Ahh, I get that! I think that the octocat assignment will make things clearer!
