### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by labraksam** [cmda-be/course-17-18#81]
It is an easy way to learn markup in this way. I think its useful that you first get an example and then you have to make something yourself. 

I learned to make the following things; 
- **bold** an _italic_ 
- ## Headers 
- [Links](https://github.com/labraksam)
- Images! 
- >Block quotes 
- unordered lists
- ordered lists
- & last but not at least, paragraphs 
 
:)

**Comment by wooorm** [comment]
Awesome! 🎉
