### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by Outerspace0** [cmda-be/course-17-18#82]
# I learned how to make a header 

1. Making an ordered list
 With a paragraph and a soft break.

>Making a blockquote
>
> With a hard break

* Making an unordered list
  * With  
  * Multiple  
  * Sub items

[An inline link](https://www.youtube.com/watch?v=U9t-slLl30E)

I also learned to make [a reference link][reference link]

[reference link]: http://orteil.dashnet.org/cookieclicker/

And how to put an image in a Markdown document:  
![Doggo](https://i.imgur.com/WaQGkR3.jpg)

**Comment by Outerspace0** [comment]
I'm not sure if this is the right way or whether I was supposed to include a screenshot of the last page.

**Comment by Outerspace0** [comment]
Ik weet niet zeker of dit de juiste manier is, of dat ik een screenshot van de laatste pagina moest plaatsen.

**Comment by rijkvanzanten** [comment]
Heya @Outerspace0!

Yep! This is exactly the right way to submit the assignment 🙂 👍 

🎉
