### ISSUE TITLE
Try Git assignment

### ISSUE THREAD

**Issue by GitGitGitta** [cmda-be/course-17-18#83]
Nice! I like the extra "advice" in the right bottom corner for additional tips & tricks. Personally, I do think it's a shame that the text-editor is forgiving: made a huuuugeeee typo in my code once and it worked anyways – I reckon it wouldn't actually work in the terminal like that.

**Comment by rijkvanzanten** [comment]
> I reckon it wouldn't actually work in the terminal like that

Probably not! As long as you know the mistake you made you should be fine 😉
