### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by theonejonahgold** [cmda-be/course-17-18#84]
- [introduction to github pr](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14379)
- [on demand github pages pr](https://github.com/githubschool/on-demand-github-pages/pull/2173)

I liked the exercises! Too bad the continuous integration on the second tutorial broke down on some github pages because they were deleted, so I removed the config files causing the tests to break and now people can merge again. 😋

**Comment by rijkvanzanten** [comment]
Awesome! 🎉
