### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by remcopasma** [cmda-be/course-17-18#89]
![image](https://user-images.githubusercontent.com/33932618/35911937-80adc4c6-0bfb-11e8-8084-f3ede273b8e0.png)

**Comment by wooorm** [comment]
Hi @remcopasma! Is it correct that you didn’t finish the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites) for this week? Especially note this part of the slack prereq:

> Get your Slack set up properly, and then send your lecturer a direct message including your real name, student number, class, and GitHub username. We’ll use this info to link your GitHub and Slack to our administration files.

**Comment by wooorm** [comment]
Sweet!
