### ISSUE TITLE
Learn Markdown assignment

### ISSUE THREAD

**Issue by GuusDijkhuis** [cmda-be/course-17-18#9]
Learned:
- Italicize
- Bold
- Headers
- Links
- Images
- Blockquotes
- Lists
- Paragraphs

**Comment by wooorm** [comment]
Nice, thanks Guus!

P.S. You don’t need to do the assignments before class. But do make sure to finish all the [prereqs](https://github.com/cmda-be/course-17-18/blob/master/week-1.md#prerequisites)!
