### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by vallleynl** [cmda-be/course-17-18#90]
**Pin:**
_Was goed te doen en leuk_
https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14387

**Firstpage:**
_Goed om te weten!_
http://vallleynl.github.io/

**Comment by wooorm** [comment]
Hey you already did your portfolio a few days ago! Nice, did you learn anything new now?

**Comment by vallleynl** [comment]
Yeah, tried to make another github.io using vallley2.github.io, but only now figured out i had to put the full repo behind it: https://vallleynl.github.io/vallleynl2.github.io/

**Comment by wooorm** [comment]
Yeah! You can only have on website on `username.github.io` (namely the code at `user/username.github.io`). If you have other projects, like `username/project`, they will live at `username.github.io/project`!
