### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by iSirThijs** [cmda-be/course-17-18#98]
Done! 😄 :octocat: 

[Introduction to GitHub exercise.](https://github.com/githubschool/open-enrollment-classes-introduction-to-github/pull/14399)

[GitHub Pages from the Command Line](https://github.com/githubschool/on-demand-github-pages/pull/2175)

[GitHub Page iSirThijs](https://isirthijs.github.io)

edit: added GitHub pages link

**Comment by wooorm** [comment]
Yay!! 🎉
