### ISSUE TITLE
Octocat assignment

### ISSUE THREAD

**Issue by jessiegouw** [cmda-be/course-17-18#99]
Liked the assignments! The second one reminded me of the the fact that your branch always needs te be merged with the master branch, it makes a lot of sense. :octocat:

**Comment by wooorm** [comment]
Sweet! Could you provide me with a link to both your PRs for the record?

**Comment by jessiegouw** [comment]
Links to my PRs
* [Map](https://github.com/jessiegouw/jessiegouw.github.io/pull/1)
* [GH pages](https://github.com/githubschool/on-demand-github-pages/pull/2169)

**Comment by wooorm** [comment]
Very nice! Awesome, Jessie!
